### ISSUE TITLE
Bitbucket auth

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#1]
This issue has been migrated from : 
https://github.com/mike-goodwin/owasp-threat-dragon/issues/23
and was opened by @dskrvk:

Bitbucket (which my team happens to use) is a fairly popular alternative to Github. Would be great to have an integration with that as well.

**Comment by dskrvk** [comment]
FWIW, we're no longer using Bitbucket.

**Comment by jgadsden** [comment]
Hello @dskrvk - OK, thanks, good to know. I am migrating the issues to the OWASP area and did not want to lose track of this one as someone may want to use bitbucket

**Comment by jabberwock** [comment]
Has this been completed?

**Comment by jgadsden** [comment]
Hello @jabberwock - this is still on the issue list, but we do not think we can get it in for version 2.0 (which we are working to get done this year). Are you back to using Bitbucket?

**Comment by jabberwock** [comment]
Hi @jgadsden 
I'm new to this thread and yes, we use BitBucket and are looking to use Threat Dragon with it. :) Thank you!

-j

**Comment by jgadsden** [comment]
Are you able to help with the coding? All contributions are very welcome
I can flag it as a Priority, but at the moment it would be in 2.1 rather than 2.0

**Comment by steve-winter** [comment]
I am working on this - login now works, working through the repository interactions now. Will create a PR when ready but any comments welcome.

https://github.com/steve-winter/threat-dragon/tree/%231-Bitbucket

**Comment by jgadsden** [comment]
Hello @steve-winter , superb thank you for taking this on. I have added you to the project contributors and assiged this to you as well
