### ISSUE TITLE
provide gitlab and bitbucket access on the demo site

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#1009]
**Describe what problem your feature request solves**:
The demo site only supports github, it would be good to configure it to provide gitlab and bitbucket as well

**Describe the solution you'd like**:
provide gitlab and bitbucket login on the demo site

**Additional context**:
the environment variables in the heroku docker container need additions for gitlab and bitbucket

**Comment by Suvendu-UI** [comment]
Hey @jgadsden when i was opening the website locally with both the server and vue it was already showing the login via Bitbucket and Gitlab.  I think there is some issue in official server.
![Screenshot 2024-07-13 203311](https://github.com/user-attachments/assets/1b5e2f97-272b-48e0-b6f9-f2e5e9e85fdb)

**Comment by jgadsden** [comment]
Thanks @Suvendu-UI , the issue is how we can reasonably configure the demo application for Bitbucket and Gitlab access.

We have the login buttons determined from `td.server/src/controllers/configcontroller.js` :

```
    bitbucketEnabled: env.get().config.BITBUCKET_CLIENT_ID !== undefined && env.get().config.BITBUCKET_CLIENT_ID !== null,
    githubEnabled: env.get().config.GITHUB_CLIENT_ID !== undefined && env.get().config.GITHUB_CLIENT_ID !== null,
    gitlabEnabled: env.get().config.GITLAB_CLIENT_ID !== undefined && env.get().config.GITLAB_CLIENT_ID !== null,
```

so it would seem to be a case of providing env var BITBUCKET_CLIENT_ID, but the problem is due to Bitbucket requiring the env var BITBUCKET_WORKSPACE which is specific to a repo
It looks possible for the GITLAB_CLIENT_ID , there does not seem to be the same repo specific env vars

**Comment by jgadsden** [comment]
The GitLab access needs GITLAB_HOST which points to s specific gitlab repo, and so this can not be provided for the general access demo site, similar to the Bitbucket requirement for a BITBUCKET_WORKSPACE pointing to a specific Bitbucket repo
it is only possible to provide GitHub access for the demo site, along with local access, as this is the only one that does not need repo specific details
