### ISSUE TITLE
Document dotenv file for use with docker

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#102]
**Describe what problem your feature request solves**
If 'export' is prepended to the environment variable declaration in a `.env` file then this will stop docker from finding these variables. This still works when running from the command line, just when running using a docker container

**Describe the solution you'd like**
Document that this is the case, otherwise Threat Dragon does not run within the docker container

**Additional context**
We need to use `export` when declaring the environment variables from the command line, and this is shown in `setup-env.md` and the `example.env` correctly shows that `export` is not used

**Comment by lreading** [comment]
I just finished a large rewrite of `setup-env.md` that will be attached to a PR for #73 that covers this very topic. :) 

I will link the issue when the PR is opened, just finishing up some testing with docker.
