### ISSUE TITLE
PDF Report save as type field with wrong .pdf extension resulting in *..pdf for the wildcard

### ISSUE THREAD

**Issue by spdw** [OWASP/threat-dragon#1023]
In the save dialog by default all existing pdf files shall be shown. Instead no pdf files are shown, because the PDF file extension is wrongly coded, see screenshot on Windows for the desktop application
![image](https://github.com/user-attachments/assets/5fa9769e-6bf8-466d-9092-65cfc7c416a5)
Looks like in https://github.com/OWASP/threat-dragon/blob/2f06c93f7228a474fe80b344bbbf8232be801396/td.vue/src/desktop/menu.js#L347 the extension shall be 'pdf' and not '.pdf'.

**Comment by jgadsden** [comment]
Thanks @spdw for spotting this bug, do you want to go ahead and fix it or I can do it if you like?
