### ISSUE TITLE
Deployed web app UI issues and unable to import existing model

### ISSUE THREAD

**Issue by fabgilson** [OWASP/threat-dragon#1043]
**Describe the bug**:

The web app visibly has some CSS issues and does not allow to open an existing model when logged in as a local user (button does not respond).

The website was working fine a week ago.

We console says: 
```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an 
allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at new Function (<anonymous>)
    at l.d (index.js:89:30)
    at l.p (index.js:148:47)
    at l.u (index.js:142:46)
    at Object.code (ref.js:19:47)
    at J (index.js:464:13)
    at index.js:185:25
    at k.code (index.js:439:13)
    at k.block (index.js:568:18)
    at R (index.js:185:13)
```

**Expected behaviour**:

Import a JSON model to continue working on it.

**Environment**:

- Version: 2.2.0-latest
- Platform: Web
- OS: MacOS
- Browser: chrome, firefox

**To Reproduce**:

Go to https://www.threatdragon.com/#/dashboard (local session), click on "open an existing model".

**Any additional context, screenshots, etc**:

![image](https://github.com/user-attachments/assets/9dd77d99-6d5f-41f9-9420-9562991fe5be)

**Comment by jgadsden** [comment]
oops, apologies @fabgilson , the csp is blocking access
many thanks for reporting this, much appreciated

**Comment by jgadsden** [comment]
this is being corrected in pull-request #1045

**Comment by jgadsden** [comment]
all working again now, thanks again @fabgilson

**Comment by fabgilson** [comment]
Thanks for fixing it so quickly! It's a great tool!
