### ISSUE TITLE
Exported model does not comply with the JSON scheme

### ISSUE THREAD

**Issue by mi0x** [OWASP/threat-dragon#1046]
**Describe the bug**:
Exporting the model may lead to `vertices` in the JSON model that contain decimals, when importing the model it expects an integer and will lead to an error message.

**Expected behaviour**:
Either the vertices must be exported as `integer` (no decimals), or the vertices must change of type in the schema so it is able to import vertices as a `number`.

**Environment**:

- Version: 2.2.0
- Platform: Web App and Desktop App
- OS: Only tested on Windows, but looking at the code, it should apply to all: MacOS / Windows / Linux
- Browser: Chrome, Firefox, Safari

**To Reproduce**:
One of my co-workers managed to export a model that had decimals in the vertices values using the same setup as me (Desktop App, Windows machine, version 2.2.0). It is still unknown what action led to these decimals, I have tried many things but have not found how to reproduce it.

**Any additional context, screenshots, etc**:
The model contains vertices values where the 'x' or 'y' contains a decimal:

```
"vertices": [
    {
        "x": 739.5,
        "y": 640
    }
]
```

The error message after importing the model:
![image](https://github.com/user-attachments/assets/e0b0947c-c035-4244-8ead-df07f05c0272)

**Comment by jgadsden** [comment]
Thanks for finding this @mi0x , and it is a bad thing to have happen
It is just a warning, if I understand correctly, so can be ignored - but it is still a high priority blocker bug
I agree that either the schema should be changed or the save functionality changed, not sure which
I think it can be repeated by turning the snap grid off when editing the diagram
