### ISSUE TITLE
"Reason for out of scope" missing in PDF report

### ISSUE THREAD

**Issue by srcnuzn** [OWASP/threat-dragon#1063]
**Describe the bug**:

PDF report does not contain "Reason for out of scope" for "Out of Scope" elements.

**Expected behaviour**:

PDF report contains "Reason for out of scope" which is important for documentation purposes.

**Environment**:

- Version: 2.2
- Platform: Desktop App
- OS: Windows 11

**To Reproduce**:

Have element in DFD with "Out of Scope" checkbox checked and "Reason for out of scope" filled.
Do PDF export.

**Any additional context, screenshots, etc**:

![image](https://github.com/user-attachments/assets/48754a80-5dc4-422e-b5fd-d7d4c1b13fe8)

**Comment by jgadsden** [comment]
thanks for this bug report @srcnuzn , it is related to #937 and I think both can be fixed together; planning this for version 2.3 due to be released Q3 2024
