### ISSUE TITLE
Improve Drag and Drop of Components

### ISSUE THREAD

**Issue by srcnuzn** [OWASP/threat-dragon#1065]
**Describe what problem your feature request solves**:

I have to select the _text_ of a component in the components view in order to drag and drop it into the canvas.
It is not possible to drag and drop by clicking other parts of the component.

**Environment**
Version 2.2
Windows 11
Desktop App
4K Monitor

**Describe the solution you'd like**:

I want to select any part of the component for drag and drop.

**Additional context**:

![2024-08-22_11h50_31](https://github.com/user-attachments/assets/7d5df0aa-dc18-49b1-8e28-52eb519d136a)

**Comment by jgadsden** [comment]
The is behavior inherited from the AntV/X6 drawing package. When we tried to change it the rubberbanding stopped working, but it may be worth trying again, or it may be solved when the migration to AntV/X6 happens ( see #722 )
planning for version 2.4 due for release in Q4 2024

**Comment by srcnuzn** [comment]
For me personally, it's not too important. Reported it in case it's a low hanging fruit.

**Comment by jgadsden** [comment]
does not apply to process, trust boundary box or trust boundary curve
only applies to actor, store and data flow
not sure why, but probably means there is a fix
