### ISSUE TITLE
Add keyboard shortcut for save [CTRL + S]

### ISSUE THREAD

**Issue by srcnuzn** [OWASP/threat-dragon#1066]
**Describe what problem your feature request solves**:

I have to use the UI button in order to save.

**Describe the solution you'd like**:

I would like to simply hit CTRL + S.

**Additional context**:

![image](https://github.com/user-attachments/assets/ce6a17e3-5169-4752-bcc0-3fb5e1105385)

**Comment by jgadsden** [comment]
Good point @srcnuzn , and we used to have this for Threat Dragon version 1.6.x - it should be possible to reinstate this, possibly in version 2.3
