### ISSUE TITLE
Improve selection of edges and creation of bendpoints

### ISSUE THREAD

**Issue by srcnuzn** [OWASP/threat-dragon#1067]
**Describe what problem your feature request solves**:

Currently, it does not feel intuitive to select a data flow edge or a trust boundary. I have to select the text or the endpoint in order to access the properties. If i click anywhere else on the line, a bend point is immediately created. Often, I don't want to create a bend point but just select the data flow / trust boundary to edit properties.

**Describe the solution you'd like**:

 I would prefer a UX similar to Miro. When clicking the edge, the properties are shown. When clicking on the circle between two bend points, a new bend point is created.

**Additional context**:

- In Threat Dragon, clicking on line immediately creates bend point.
![2024-08-22_13h07_53](https://github.com/user-attachments/assets/05c64041-eea1-47cb-9b3b-ef792c1f76f6)

- In Miro, clicking on line selects the line first and enables to edit properties. Bend points can then be created afterwards.
![2024-08-22_13h08_30](https://github.com/user-attachments/assets/3e2def12-75c8-4039-8bfc-20f7eff830cc)

**Comment by jgadsden** [comment]
yes, I agree that this has been a long standing problem with the AntV/X6 drawing package
we have not yet managed to find a solution, it may be that migrating the package to version 2.0 (see #722) may help , really not sure either way
this is related to issue #785 , which suggests updating the docs to help with this (irritating) problem with selecting dataflows

**Comment by srcnuzn** [comment]
Once I got used to it, it's fine (lower prio for me personally). Was just very confusing in the beginning. Maybe a selection work around could be to have an outline view (list) of all elements in the canvas.

**Comment by jgadsden** [comment]
This is fixed in pull request 'Migrate to version 2.x antv/x6' #1099, where the selection of dataflows and trust boundary curves is greatly improved
