### ISSUE TITLE
How do you configure the web application for https?

### ISSUE THREAD

**Issue by ericfitz** [OWASP/threat-dragon#1098]
I have the web application installed on a virtual machine in a cloud provider.

The VM guest is running RHEL.

I've configured DNS such that there's an A record pointing to the public IP address of the guest.

I've used certbot (LetsEncrypt) to obtain a certificate and private key for the host using DNS validation.

The certificate is in /etc/letsencrypt/live/$HOSTNAME/fullchain.pem and the private key is in /etc/letsencrypt/live/$HOSTNAME/privkey.pem

But I can't find any configuration anywhere in the code or in the documentation how to configure the web application so that it will use this certificate/key combination.  This is something that node can do but when the server is started the paths to the certificate and private key must be provided.

The env file has options to support SERVER_API_PROTOCOL=https and to configure the listening port but no options to point to the certificate and private key.

td.server/src/config/https.config.js hints that https might be proxied by Heroku in front of the application.

I'd appreciate any help.   I'm happy to write up instructions for the public facing documentation if we can get this to work.

Thank you,
Eric

**Comment by jgadsden** [comment]
this is a very good point
at present the config SERVER_API_PROTOCOL forces the request to use https, but that is all it does
we assumed that the application is running in an environment where this is sufficient - but I agree that is not a good assumption at all

**Comment by ericfitz** [comment]
It's not the answer that I wanted but it is the one I expected :-D

I think for my use case I'll just stand up Nginx as a local reverse proxy and do https there.

Thanks!
