### ISSUE TITLE
local model storage (for the webapp)

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#11]
This issue has been migrated from : 
https://github.com/mike-goodwin/owasp-threat-dragon/issues/126
and was opened by @Trolldemorted  : 

Would it be a lot of work to support local storage on the webapp like the electron client does?

This would be great for quick demos for audiences which are unwilling to allow write access to their github repositories, or do not have a github account.

**Comment by lreading** [comment]
Closing, as this is completed in the v2-development branch.
