### ISSUE TITLE
New threat by type/context throws error on edges

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#1110]
**Describe the bug**:
New threat by type and new threat by context throw an error when using them on an edge.  The new threat button is disabled, so I suspect this is an unintended workflow.

**Expected behaviour**:
Should we disable these buttons when the "New Threat" button is disabled?  I'm not sure how this is used.

**Environment**:

- Version: 2.2.0-latest
- Platform: Web App
- OS: Ubuntu 24.04
- Browser: Vivaldi (chromium based)

**To Reproduce**:

1. Create a new Diagram
2. Add a trust boundary curve
3. Select the edge (tb curve)
4. Click either "New Threat By Type" or "New Threat By Context"
5. Attempt to save
6. Threat is not saved, and there are errors in the console

![image](https://github.com/user-attachments/assets/81b71c58-bde1-4d93-8ada-909b111115e9)

**Any additional context, screenshots, etc**:

**Comment by jgadsden** [comment]
good point - the new threat button is disabled for an out of scope component or no component selected
we can disable the threats by context / type along with the new threat button

**Comment by Gauravsinghrajputt** [comment]
assign me for this issues

**Comment by lreading** [comment]
Awesome, thanks @Gauravsinghrajputt !

**Comment by jgadsden** [comment]
taking this on as we need it for the version 2.3 release this week
