### ISSUE TITLE
Migrate to express version 5.x

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#1116]
**Describe what problem your feature request solves**:
Threat Dragon has begun to break if the td.server package-lock file is updated

**Describe the solution you'd like**:
Probably need to update express to version 5.x to avoid these dependency problems

**Additional context**:
The [migration documentation ](https://expressjs.com/en/guide/migrating-5.html)provides some guidance

**Comment by kartik-212004** [comment]
I'm interested in working on this issue and would appreciate being assigned to it.
