### ISSUE TITLE
Request for a 'Return' button for home screen when in the Diagram Mode

### ISSUE THREAD

**Issue by tom-seward** [OWASP/threat-dragon#1133]
**Describe what problem your feature request solves**:
When in diagram mode you have to close and reopen the project to get to the back to the home screen to then run the report.

**Describe the solution you'd like**:
When in the diagram mode, it would be great to have the 'Return' button similar to the one you get when in Report mode to get back to the home screen

**Additional context**:
<img width="1624" alt="Screenshot 2024-11-28 at 08 56 13" src="https://github.com/user-attachments/assets/ad92ee85-eb94-48fd-9d1b-ca74e5933a00">

**Comment by jgadsden** [comment]
Thanks for this suggestion @tom-seward , it is somethig that we can certainly add, I will mark this for the next release version of 2.4

**Comment by satwiksps** [comment]
Hi ! I am currently working on this issue

**Comment by jgadsden** [comment]
Hello @tom-seward , could you make sure you are using a version 2.x Threat Dragon? From the screenshot it looks like a version 1.6.x version
Using version 2.x I think the path through the application will already do what you want
