### ISSUE TITLE
Inconsistent use of actions/download-artifact

### ISSUE THREAD

**Issue by kingthorin** [OWASP/threat-dragon#1136]
It seems the repo/project uses both 4.1.8 and 4.1.7 even within the same workflow (ex: release). Is this intentional for some reason?

![image](https://github.com/user-attachments/assets/72613f0a-f73b-4fb8-bbaf-2c20185c85a4)

**Comment by jgadsden** [comment]
Well spotted @kingthorin , and I agree there is no reason to use different versions of download-artifact and it is not intentional
I can raise a PR for it, unless you would like the honor?

**Comment by kingthorin** [comment]
I'm happy to tackle it.

Honestly GitHub sent another email about the artifact v3 actions being deprecated today. So I searched all my forks. Which is why I noticed 😉
