### ISSUE TITLE
Add extra value for Priority field, and change default value

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#1143]
**Describe what problem your feature request solves**:
The priority value for the threats default to Medium and the other options are Low or High
We should extend the values to Critical and TBA, and adjust the default away from Medium

**Describe the solution you'd like**:
Have values available:

- Critical
- High
- Medium
- Low
- TBA

and default to TBA rather than Medium

**Additional context**:

**Comment by fparuce** [comment]
Hi there! Can you assign this feature to me?

**Comment by jgadsden** [comment]
Hello @fparuce , thanks for taking this on
There are various I18N files to fix-up as well
