### ISSUE TITLE
Recognize Private Repos

### ISSUE THREAD

**Issue by brandon-secid** [OWASP/threat-dragon#117]
**Describe what problem your feature request solves**
TD Web doesn't seem to recognize private repos, I'd prefer not store Threat Model data in a public repo on certain projects. Anyway to get this to work for private repos?

**Describe the solution you'd like**
I'd like to store Threat Model data in a private repo. 

**Additional context**
None.

**Comment by lreading** [comment]
Threat Dragon can recognize and use private repositories if you set the `GITHUB_SCOPE` environment variable to `repo`.  This value defaults to `public_repo`, which will only read public repositories.

More info on environment variables is in [setup-env.md](https://github.com/OWASP/threat-dragon/blob/main/setup-env.md#all-variables)

**Comment by brandon-secid** [comment]
D'oh, my bad @lreading , I knew it had to be possible and missed that env variable in the settings. Thanks! This worked.
