### ISSUE TITLE
Custom style sheets

### ISSUE THREAD

**Issue by elouet** [OWASP/threat-dragon#129]
**Describe what problem your feature request solves**
Current reports have very simple layout, somewhat roomy, and could be improved, for instance by being edited in another tool (LaTeX, MS Word, you name it...).

**Describe the solution you'd like**
In order to improve tool output reusability (i.e. in other documents), it could be nice to be able to use custom style sheets for the report. 

**Describe alternatives you've considered**
This does not necessarily mean changing the tool itself, maybe HTML export would be enough.

**Additional context**

**Comment by jgadsden** [comment]
The HTML export is provided by pull request #664 , now able to close this issue
