### ISSUE TITLE
Spellchecker

### ISSUE THREAD

**Issue by adampurkiss** [OWASP/threat-dragon#130]
**Describe what problem your feature request solves**
My spelling is really bad

**Describe the solution you'd like**
Built in spellchecker. No need for anything fancy, just enough to catch blatant issues like Chrome or the like picks up on when I typed this feature request.

**Describe alternatives you've considered**
Copy and paste everything from the desktop version to notepad ++ or similar and run spell check on it

**Comment by ShubhamPalriwala** [comment]
@jgadsden @lreading Are we planning to use some npm package and solve this issue? Or are we thinking of something else here?

**Comment by jgadsden** [comment]
Agreed @ShubhamPalriwala , it would be using a package to do this rather than writing anything ourselves - and ideally work with the I18N

**Comment by lreading** [comment]
My (personal) preference is to only use packages for things that are non-trivial to create/implement.  That said, a spell-checker sounds like a nightmare to try to write. :grin:  I'm 100% behind finding a good package, and as Jon mentioned, ideally one that plays nicely with internationalization.

**Comment by storkinsj** [comment]
I think a spell checker may not be a good idea.  

Most dictionaries don't include tech terms. If you want to write this, it will of course bloat the size (unless it pulls it from the cloud), and you'll have to create an entire dictionary of tech words like firewall, sha1, cipher suite (not sweet !) ... etc. Try dictating the elements of your threat model into siri just to see what you get.

If you really want to do it... like REALLY (there are many other more critical things at this juncture but even as a future feature)... it has to come with a tunable dictionary. Of course many checkers have that, but we probably will have a constant chore to update the dictionary with new tech terms that honestly will never be 100% up to date. However, it would be a fun file to contribute edits to... and lol we'd probably see more contributes to that than any other piece of  the project.

I did find this; a computer science one may live somewhere.... https://pubs.acs.org/doi/10.1021/ed2002994

**Comment by jgadsden** [comment]
I _think_ there are spell checkers and spell checkers ... ideally there is one that ignores stuff it really has no idea about, but checks obvious attempts at normal english. I guess that is a spell helper :)

**Comment by lreading** [comment]
I think the desire for a spell-checker is most needed in the description/mitigation fields, where most users would be writing plain sentences with only a bit of jargon.  I think even if the spell-checker is picking up on tech terms that aren't recognized (similar to how chrome or notepad++ does), it would still be an improvement and aligns with what most people are already used to.  

I don't agree that it needs a tunable dictionary, maybe as a nice-to-have though! I wouldn't try to stop anyone from tuning it or maintaining said dictionary, but I don't think that's what people are asking for here.

**Comment by jgadsden** [comment]
We may get the chromium spellchecker by default with electron:
https://www.electronjs.org/docs/latest/tutorial/spellchecker

**Comment by ShubhamPalriwala** [comment]
As per the discussion, I agree with the point that the chromium spellchecker that comes with electron will be a good start to solving this issue.
We can later work on a full-fledged dictionary that has all the words that are usually used by the users.

**Comment by storkinsj** [comment]
One more comment on the spell checker:

My guess (and I don't actually know because I'm not a UX designer nor have I studied HID) is that once people get used to seeing misspellings... the type we're hinting about in this thread... they will miss the real misspellings. 

The net/net will be we'll always be looking at red squiggles every time we use the tool. 
If we decide to go this path, let's make it optional.
Also, since Sidekick and turbo lighting (REALLY dating myself here) back in the 80s and 90s, I have never worked with a spell checker that didn't have a way to add words. If you create a spell checker for a tech editor and don't add this, I think adoption will be extremely low- unless it's not optional. In that case, be ready for the issue to be logged. IMHO! :-)

**Comment by jgadsden** [comment]
@storkinsj I appreciate your (very healthy) scepticism on spell checkers ... now you point it out I have gotten used to ignoring the red squiggly line. It may be that electron applies it to Threat Dragon unless we configure it out, finding out should be part of the electron development.

It would be good to make sure we have your input on this when it comes to be implemented - if it is OKK I will assign a few of us to this issue.

**Comment by storkinsj** [comment]
Similar discussion going on [over here ](https://github.com/jgraph/drawio-desktop/issues/420)with a solution. 
Looks like not everyone wants it off or on, but it's doable to make it switch.

**Comment by jgadsden** [comment]
Closing this because we now have spellchecking for version 2.0 - but opened #375 because the spellchecker could get irritating
