### ISSUE TITLE
PDF report has sliders around diagram

### ISSUE THREAD

**Issue by elouet** [OWASP/threat-dragon#131]
I have a diagram that spans the entire input window on the application. When the report is presented as HTML inside the application there is no problem. When I create a PDF, however, the diagram is cut and surrounded by sliders (not operative of course), as shown below : 

![report](https://user-images.githubusercontent.com/436633/99400554-60b58f80-28e7-11eb-9c75-54db3533ad75.png)

**Comment by jgadsden** [comment]
Closing this because it is fixed in version 2.0
