### ISSUE TITLE
User modifiable library of threats would be really handy

### ISSUE THREAD

**Issue by adampurkiss** [OWASP/threat-dragon#134]
Its great that I can create a process with a number of "common" threats and then duplicate this to save copy and paste/editing the json directly but what would be really useful is some library of threats that can be expanded upon locally. So on top of just looping through the 6 STRIDE items you could have "Manage threats" have another item called "Add pre existing threat". This could list all threats on the current model as well as a library of threats so things like "add audit logging" could be done easily be added as a threat without all that manual editing. 

This addresses both the ability to copy and paste a threat between nodes as well as encouraging the community to build up these libraries for you. You can use JSON to drive this and ideally have some sort of grouping to make it easy to look up items

You then have the ability to add search, etc to the UI down the road.

**Comment by jgadsden** [comment]
We are very unlikely to implement this - Threat Dragon is a lightweight tool and this feature is more towards the Microsoft TMT scale.
Closing this as a Won't Do because we can not compete (and shouldn't) compete with the features provided by MS TMT
