### ISSUE TITLE
Communication encryption missing from report

### ISSUE THREAD

**Issue by adampurkiss** [OWASP/threat-dragon#135]
Although data flows can be marked as secure there is not visual queue or indication in the report that the flow is secure leading to questions about is the channel secure, etc.

As a first pass additional details in the report to indicate protocol and encryption would be great. 

Additionally a padlock/broken padlock icon on the diagram would help as a visual indicator that the flow is encrypted at least

**Comment by lreading** [comment]
After thinking about this for a bit, I'm leaning towards an implementation that replaces the arrow-head with a padlock on process flows if it's encrypted.  I think this will be better than trying to place the padlock somewhere along the process flow line, as the line will likely already have a label on it.  

With that said, I'd also like to highlight when communication is **not** encrypted, as I think that's more valuable to point out from a threat-modeling perspective.  I'm not sure the broken padlock will be easy enough to differentiate from the regular padlock.  Additionally, adding them both makes the sample graph feel very busy.

Does anyone have suggestions for the implementation of the UI components for this?  This is a great suggestion, I just want to make sure it's implemented in a way that doesn't take away more than it adds. :smile:

Here's an idea of what I was playing with as far as lock icons in place of arrow heads:
![Screenshot from 2021-05-25 22-08-14](https://user-images.githubusercontent.com/5851985/119592050-c22e4d80-bda5-11eb-96c9-8c99d9bf9c37.png)

**Comment by jgadsden** [comment]
I am not sure about the locks (open or closed) for the encryption - it does feel immediately obvious what it means.

It would be good to show if the protocol uses encryption, if the protocol is shown on the data flow then we may be able to indicate it that way

**Comment by lreading** [comment]
Because there is so much overlap between this and #150, I will be closing this and tracking it as part of that issue / discussion. :smile:
