### ISSUE TITLE
Print to PDF has scroll bars

### ISSUE THREAD

**Issue by adampurkiss** [OWASP/threat-dragon#136]
Print to PDF has scroll bars on the diagram cutting off parts of the image that should be visible.

**To Reproduce**
1. Create diagram the does not fit perfectly on the screen
2. Generate Report
3. Save PDF
4. Open PDF and see that the image has scrollbars rather then reformatting image to fit to PDF (possibly by increasing paper size)

**Expected behavior**
The image should fit the paper. Ideally a more complex image would resize paper rather than shrink. Failing that consider save to HTML

**Environment:**
 - Platform: Desktop
 - OS: Windows
 - Version 1.3.1

**Additional context**
As an alternative I have been able to print to PDF using third party software and it does the right thing on the models I have used at least.

**Comment by jgadsden** [comment]
this is similar to #131 and has been fixed in version 2.0
