### ISSUE TITLE
Remove Link does not always work.

### ISSUE THREAD

**Issue by adampurkiss** [OWASP/threat-dragon#137]
In Windows version 1.3.1 when you delete a number of links you can get "stuck" with a link that wont delete until you press save, exit diagram and go back in. Unfortunately this does not always happen so I have not ben able to come up with foolproof steps

**To Reproduce**
1. Create a model where you have > 4 processes along with 2 or more data flows per process
2. Delete more than one data flow link
3. At some point the remove link button stops working
4. Save
5. Close Diagram
6. Open Diagram
7. Delete link

**Expected behavior**
Delete should always work

**Environment:**
 - Platform: Desktop
 - OS: Windows
 - Version 1.3.1

**Comment by juankb1024** [comment]
I was able to reproduce this in Mac 11.5.2 with version 1.5.3.

I made a diagram, duplicated that diagram, opened the diagram and tried to delete a link.

After saving, closing and opening it again, it worked.

**Comment by jgadsden** [comment]
Thanks @juankb1024 , I will see if I can repeat it. We are updating our version of JointJS in #236 and this may get solved during that update.

**Comment by jgadsden** [comment]
Closing this as a Won't Do
We have replaced the drawing library for version 2.0 onwards, so we no longer have this problem (just different problems)
