### ISSUE TITLE
Take asset checkbox before generating threat suggestions

### ISSUE THREAD

**Issue by asumupper** [OWASP/threat-dragon#139]
When we put the assets and data flows into the diagram, we are allowed to set  a few checkboxes. If we ask the application to generate threat suggestions, it does not take them into consideration, thus suggesting a "Tampering" threat to a data flow that has been marked as "encrypted" in one of its checkboxes.

**Comment by jgadsden** [comment]
Issue #187 and pull request #310 satisfy this issue - so closing
