### ISSUE TITLE
Too many GitHub permissions required

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#14]
This issue has been migrated from : 
https://github.com/mike-goodwin/owasp-threat-dragon/issues/148
and was opened by @madchap : 

When wanting to try TD, it asked me for the following GitHub permissions, which in my opinion are too much:

![image](https://user-images.githubusercontent.com/5468769/81498330-93d9ef00-92c4-11ea-96c3-ab3fde9644da.png)

As a result, I personally didn't want to grant so much.

Maybe it is possible to ask for less and achieve what is needed?

Cheers!

**Comment by mykter** [comment]
Per-repository access is the main thing I'd look for here. I'm fine with giving this level of access to a specific repository that I've chosen, but not to all my repos.

**Comment by agostbiro** [comment]
Please prioritise this! It's a hard blocker preventing the use of the project and in general sets a poor example.

**Comment by jgadsden** [comment]
Hello @mykter and @agostbiro - I understand your frustration. This is specific to threat dragon version 1.x , which is the branch off main that has only security or highest priority fixes applied.

We are working on version 2.x now, and this does not have the problem described here. We expect version 2.0 to be released within a couple of months or so. Apologies for not giving the response that you were looking for

**Comment by jgadsden** [comment]
Closing this as it is handled by issue #5
