### ISSUE TITLE
EOL for AngularJS

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#141]
@fkl-rt writes
Threat Dragon is built on AngularJS which is reaching EOL in June 2021, if I understand their announcements correctly ([1], [2]).
Are there any plans to switch to the newer (not-backwards compatible) Angular.io release or to any other framework?

[1] https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c
[2] https://github.com/angular/angular.js/issues/16895

**Comment by lreading** [comment]
Due to the pandemic and pressure from the engineering community, EOL has been extended.  Regardless, work is underway to migrate the project to Vue.js

**Comment by lreading** [comment]
Closing this as v2 is written in Vue, and is currently our entire focus, there will be no further 1.x releases.  We are hoping to get v2 out early this year.
