### ISSUE TITLE
Reinstate zoom feature

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#144]
The zoom feature was removed temporarily, issue https://github.com/mike-goodwin/owasp-threat-dragon-core/issues/94 . 
It has also been migrated from  https://github.com/mike-goodwin/owasp-threat-dragon-core/issues/95 : 
This feature needs to be reinstated so that:
* when zooming in it is possible to scroll across the paper
* when zoomed out, the paper size is adjusted when dragging elements across the paper
* it is possible to pan across the whole diagram when zoomed in, see issue https://github.com/mike-goodwin/owasp-threat-dragon-core/issues/72 
* anchors on the elements are scaled correctly when zoomed in, see issue https://github.com/mike-goodwin/owasp-threat-dragon-core/issues/73 
* dead space can not be created by zooming in and adding elements, see issue https://github.com/mike-goodwin/owasp-threat-dragon-core/issues/60

**Comment by lreading** [comment]
Closing, as this is completed in the v2-development branch.
