### ISSUE TITLE
Drag whole trust boundaries

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#146]
@thomaskonrad reports:
I cannot drag whole trust boundaries: When I point at a trust boundary, the cursor indicates that I can drag and drop the whole boundary, but instead, a new point is added to the curve, which I then drag. I could not find out a way to move a whole trust boundary at once.

**Comment by lreading** [comment]
Closing, as this is completed in the v2-development branch.

v2 introduces different shapes for trust boundaries: the current curved line, as well as a box.  The curved line can be selected by clicking on the arrow head / connector, and the box will be highlighted.  From there, you can move the entire box, stretch, rotate, etc.  You can still add points to the curved line.

The trust boundary box acts as any other box on the graph.
![Screenshot from 2021-11-05 00-38-23](https://user-images.githubusercontent.com/5851985/140458974-17e3903d-d760-48d7-9f82-397aa397564e.png)
