### ISSUE TITLE
Data Flow arrows misaligned

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#148]
@thomaskonrad reports:
Data Flow arrows are misaligned: The arrows seem to point towards the direct line between two objects, instead of the direction of the very last part of the curve. That makes it misaligned when it's curved.

**Comment by jgadsden** [comment]
@lreading this looks like one that will be solved with the version 2.0 drawing package. Assigning it to you if that is OK by you?

**Comment by lreading** [comment]
Confirmed as resolved in v2, closing.
