### ISSUE TITLE
Make trust boundaries closed

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#151]
This issue has been migrated from : 
https://github.com/mike-goodwin/owasp-threat-dragon-core/issues/74
and was opened by @adamshostack : 

Arc trust boundaries are ambiguous. For example, in the sample diagram, one arc can be extended to split "background worker process", another can be extended to bisect "database."

Closed boundaries (such as boxes) are more clear, and should be the default shape.

**Comment by lreading** [comment]
I will be closing this in favor of #54 which will be close when v2 is released. :smiley:
