### ISSUE TITLE
Provide bi-directional data flow

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#154]
It would be good to be able to specify bidirectional data flows, as well as the existing single direction data flow, as it would make some diagrams look less busy and would not detract from the information in the threat model

**Comment by jgadsden** [comment]
There is no need for bi-directional arrows, as nobody in the Threat Dragon community has specifically asked for them (except @jgadsden ;) )

**Comment by Lytes** [comment]
Made a search to see if there was a feature for this, breaks my heart tbh

**Comment by jgadsden** [comment]
Oh! @Lytes it is really good that you want this. I was the originator of this issue, because personly wanted it - but there seemed no interest from the community so I closed it
Very happy to open this issue again and I hope it attracts some developer interest

**Comment by pana15** [comment]
Was this feature ever included? I'd be extremely happy to have this as well...

**Comment by jgadsden** [comment]
All done, this was included in Pull Request "Diagram style updates" #742, September 2023
