### ISSUE TITLE
Select and move multiple elements

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#155]
This issue has been migrated from : 
https://github.com/mike-goodwin/owasp-threat-dragon-core/issues/45
and was opened by @p- :

Like the title says: it would be cool if selection and move of multiple elements would be supported.
(If it is supported: I'm sorry I couldn't figure out how 😉 )

**Comment by lreading** [comment]
Closing, as this is completed in the v2-development branch.
