### ISSUE TITLE
draw.io and/or visio integration

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#16]
This issue has been migrated from : 
https://github.com/mike-goodwin/owasp-threat-dragon/issues/150
and was opened by @gbiagomba : 

Hello,

This is more of a request than an issue. But is there anyways to open a visio file oran xml file from draw.io into this tool? If no, is it possible to have that added?

**Comment by jgadsden** [comment]
Not able to open visio files or xml files at present, @gbiagomba , but there is possibly a draw.io based version of threat dragon coming along later in the year which will replace our use of jointjs. We then may be able to open these files along with the TD json files, so will keep an eye on this.

**Comment by gbiagomba** [comment]
Thank you 😊

**Comment by ivandov** [comment]
Based on this statement:

>  but there is possibly a draw.io based version of threat dragon coming along later in the year which will replace our use of jointjs

and the tagging for `version-2.0` being added ... is it safe to assume the latest available version `v1.5.8` does not have support for integration with draw.io diagrams?

My architecture diagrams are all already in the draw.io format. It'd be great if I could import those and use threat dragon as a means to extend them with threat modeling details.

**Comment by lreading** [comment]
That is correct, `v1.5.8` does not have a draw.io/Visio integration.  The `version-2.0` may be a misnomer as well, as I don't know if this will make it into the first v2.x release.   Unfortunately, I don't have a timeline for when it may be added.

If someone wants to pick this up, `v2-development` is where you can branch from currently. :smile:

**Comment by jgadsden** [comment]
Agreed, we initially thought that we would use a draw.io / mxgraph drawing package in version 2.0, but mxgraph itself became unsupported and maxgraph (its successor) is stalled

This means no immediate draw.io compatibility, but it is something that will be good to have soon

**Comment by jgadsden** [comment]
closing this because it is unlikely to be worked on
