### ISSUE TITLE
Disable threats for trust boundaries

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#161]
**Describe the bug**
When adding threats, it should not be possible to add a threat to a trust boundary. 

**To Reproduce**
1. Creat a threat model woth a trust boundary
2. Click on LINDDUN
3. Add a threat
4. Incorrectly able to add a threat

**Expected behavior**
It should not be possible to add a threat, for example:
1. Creat a threat model woth a trust boundary
2. Click on STRIDE
3. Click on Add a threat
4. Unable to add a threat

**Screenshots**

**Environment:**
 - Platform: both Desktop, WebApp
 - OS: all
 - Browser all
 - Version latest

**Additional context**

**Comment by jgadsden** [comment]
Hello @MrWaggel , only because common orthodoxy is that threats should not be applied to trust boundaries (both curves and boxes)
I think you may be wanting something different? In that every component (and possibly data flows) _within_ a trust boundary box have the same threat assigned to them?

**Comment by MrWaggel** [comment]
Thanks for the fast response

> I think you may be wanting something different? In that every component (and possibly data flows) _within_ a trust boundary box have the same threat assigned to them?

Is this a possibility in TD?
