### ISSUE TITLE
Include SBOM

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#178]
**Describe what problem your feature request solves**
More organizations are requiring a SBOM for software they deploy into their environments.  There's also increased visibility around this in the US due to a [recent executive order](https://www.zdnet.com/article/linux-and-open-source-communities-rise-to-bidens-cybersecurity-challenge/).

**Describe the solution you'd like**
This can, and should be automated.  Because the front-end and back-end environment is strictly JavaScript and uses NPM for dependencies, I think it would make sense to use something like [@cyclonedx/bom](https://github.com/CycloneDX/cyclonedx-node-module).
Ideally, we could have the following formats:
- xml
- json
- human-readable

**Additional context**
In the v2-development branch, documentation is baked into the docker image.  We could include a human-readable version in the documentation, as well as maintaining an xml and json version alongside it.  If this is built as part of the docker image, then it would always be accurate to the current deployment/image.

**Comment by lreading** [comment]
Done in v2-development:
https://www.threatdragon.com/docs/home/trust/sbom.html

**Comment by jgadsden** [comment]
Looks good @lreading , and the idea is to apply only to version 2 for now? And then when version 2 goes live we have this in place

**Comment by lreading** [comment]
That's the approach I've been taking for now.  With the amount of changes needed on 2.0 branch, I could see it becoming quite the merge headache if we did too much on the main branch for now.

**Comment by lreading** [comment]
Closing as this is complete in v2
