### ISSUE TITLE
Free text/note

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/threat-dragon#189]
Hi,

It would be great to add some extra note and text around trust boundaries, visible but out of scope; it comes very handy for reminders while presenting the threats or wants to continue with something later. I see Microsoft threat modeling tool already has it... maybe it's a good inspiration to have the idea.

Bests, Ali.

**Comment by jgadsden** [comment]
Hello @Ali-Razmjoo - good idea, and it should not be too hard to do.

(we are always looking for contributors, so if you are able to add this then that would be great)

**Comment by lreading** [comment]
Hi Ali!

This is something that will be included in the 2.0 release that will be released at some point this year.  We've had some discussion on it [here](https://github.com/OWASP/threat-dragon/issues/128#issuecomment-853347589).  Please let me know if that aligns with what you were thinking. :smile:

**Comment by lreading** [comment]
Closing as this is complete in v2:
![Screenshot from 2021-11-05 00-22-15](https://user-images.githubusercontent.com/5851985/140457937-b0dbaf0f-d251-4341-b41f-49ce5ab768fd.png)
![Screenshot from 2021-11-05 00-22-41](https://user-images.githubusercontent.com/5851985/140457942-947fb742-76ab-451b-9e38-3b4a0a29b980.png)
