### ISSUE TITLE
Add N/A as Threat Level

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#195]
**Describe what problem your feature request solves**
Sometimes the "threat level" field is not applicable.  Currently, some users are using the mitigated property as a workaround, though that's a bit of a misnomer. 

**Describe the solution you'd like**
Add a "Not Applicable" option for the threat level.

**Additional context**
This suggestion was provided by Simon S

**Comment by jgadsden** [comment]
I agree with this suggestion @lreading (and many thanks to Simon S for suggesting this). We have two options at present  'Open' and 'Mitigated' so we have a third in the same block? Suggest 'NA' for brevity's sake?
