### ISSUE TITLE
Add Custom Score Field to Threats

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#196]
**Describe what problem your feature request solves**
Some users need to use quantitative scoring for their threats in order to meet regulatory requirements as well as internal security policies.

**Describe the solution you'd like**
Add a "custom score" field to threats that can be defined by the user.

**Additional context**
In theory, it would be great to have a quantitative scoring module added to Threat Dragon, however, it would be a non-trivial amount of work.  Threat scoring is a vast landscape, and this would need to be highly customizable in order to accommodate Threat Dragon users.  As a good start, we can add an optional field for "custom score", so that users are not forced to add scores to threats but also provides the flexibility to record any quantitative scoring they currently use.

This suggestion was provided by Simon S

**Comment by jgadsden** [comment]
Agreed @Gavitron , Simon was suggesting the score as an alternative to the Severity. The idea is that you could then apply a ranking or a CVSS score

If the Severity was changed to being Priority then that might be more useful, with an optional quantitative scoring of the threats

**Comment by Gavitron** [comment]
I would agree, priority is a great option. Especially when collaborating with product teams on the models, as they often care more about which order to address, than any specific scoring. :)   and an optional fixed-point score is an excellent idea too.
