### ISSUE TITLE
Severity Should Not be a Required Field

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#197]
**Describe the bug**
Severity is a required field, and defaults to "medium".  When threat modeling, the severity may be unknown at the time of recording the threat.  Additionally, some users may use a more complex severity system.

**Expected behavior**
Severity is not required.  After being selected, severity should be able to be un-set

**Environment**
N/A

**To Reproduce**
- Create a new threat
- Severity is recorded as medium by default
- Severity cannot be unselected

**Any additional context, screenshots, etc**
Thanks to Simon S for bringing this to our attention

**Comment by jgadsden** [comment]
This is a difficult one, and a very good point raised by Simon S.
We already have a block of 'High', 'Medium' and 'Low'. We could add a fourth 'NA' but with the possibility of adding a score as well #196 we may end up with a block of five ... which will look too complex?

Could we start using drop downs instead of radio buttons?

**Comment by lreading** [comment]
I think using drop-downs would be the simplest solution, as opposed to adding anything.  Using a dropdown, you could un-set the value after it is set, or leave it blank to begin with.

**Comment by Gavitron** [comment]
I was doing a threat modelling exercise with an SME, using Threat Dragon for the first time, and we were both confused by 'severity'.  For a given threat, we wanted to articulate things like

- low probability of actually happening
- high impact if it does
- a quantified risk score (ex: 0.0 through 5.0)
- priority of mitigating the issue (relative to all mitigations, L/M/H.)

and we weren't sure how to map all of that into the tristate of 'severity'.  

I suspect that's what this open issue is about too: https://github.com/OWASP/threat-dragon/issues/149 but am not certain of that author's intent.

for the time being, we will export our threats to a spreadsheet, and break out the dimensions there, but it would be great to see these dimensions pulled into TD 2.x 

thanks!

**Comment by jgadsden** [comment]
Hello @Gavitron - you make a very good point. Severity is not meaningful - or at least can not be quantified - in most threat analysis. Would it be better to regard 'Severity' as 'Priority' ? Then we could rename this field, while keeping backward compatible, and the values become useful

Open to suggestions @Gavitron , @lreading and @mike-goodwin 

We  would also have to look at the 'traffic light' for the threats listed in the left-hand pane, probably move from Red Amber Green

**Comment by lreading** [comment]
v2 now has the threat-edit modal and is labeled as `priority`, but the backing json is still `severity`.  Additionally, it is now a dropdown that also contains an empty value as an option.  Should we close this as done, or did we want to make further changes in v1?

**Comment by jgadsden** [comment]
Yes, this caused me a lot of thinking. We need to remain backwardly compatible with existing threat models and also the JIRA + TMT utilities, so in the end I left it as 'severity' in the json.

There must be better solutions though, maybe have both 'severity' and 'priority' that are synonymous and displayed on the edit box? I am very open to suggestions :)
