### ISSUE TITLE
Close Modals Using Escape Key

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#198]
**Describe what problem your feature request solves**
When navigating threat dragon, it would be nice to be able to use the escape key to close/cancel modals.

**Describe the solution you'd like**
The escape key will close (default to cancel) a modal window

**Additional context**
This suggestion was provided by Simon S

**Comment by lreading** [comment]
Version 2.0 is using [bootstrap-vue](https://bootstrap-vue.org/) which provides this functionality out of the box.

**Comment by jgadsden** [comment]
Excellent to see @lreading - and this will not be implemented in a 1.x release so we can totally wait for the 2.x release on this

**Comment by lreading** [comment]
Closing, as this is completed in the v2-development branch.
