### ISSUE TITLE
feature request: ability to import TM7 and export to SVG

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#2]
This issue has been migrated from : 
https://github.com/mike-goodwin/owasp-threat-dragon/issues/50
and was opened by @securestep9 : 

ability to import/export Microsoft TM7 format, SVG & PDF will make this tool far more mature and useful.

**Comment by jgadsden** [comment]
This is linked to ' draw.io and/or visio integration #16 '

**Comment by jgadsden** [comment]
Hello @muthukumaranbe this is the issue that we discussed earlier. It would be very good to have an import / export with MS TMT. It needs quite a bit of time to implement, and so far we have not had anybody to do this feature

**Comment by jgadsden** [comment]
Hello @tmart234 , thanks for the scripts in [TMTool/Scripts](https://github.com/tmart234/TMTool/tree/main/TMTool/Scripts) and in particular `model2csv.py`
We can certainly base the import and export on these ideas, and probably exporting to json

**Comment by tmart234** [comment]
I think we’d want to update this feature request to specifically say “import tm7 and export to svg and pdf”? That makes more sense. Importing tm7 is solved with https://github.com/OWASP/threat-dragon/pull/243 just need search for .tm7 files when importing w desktop app and pass json object instead of saving it locally.

**Comment by jgadsden** [comment]
Yes agreed @tmart234  - I will fix up the title.
We can print the report to PDF already, is this OK with you @securestep9 ?

**Comment by jgadsden** [comment]
This would be good to have in version 2.x

**Comment by jgadsden** [comment]
closing because it is unlikely to be imlemented
