### ISSUE TITLE
User session timeout not handled

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#20]
@danwiltshire  raised this issue in https://github.com/mike-goodwin/owasp-threat-dragon/issues/152 : 

When the user session times out, the application will let the user continue to work on a diagram but the Save function does not operate.

The user will need to refresh the page which will prompt for GitHub authentication resulting in lost progress.

Steps to reproduce:

Let browser idle or put device to sleep for a period of time
Continue working in Threat Dragon
Attempt to save progress.

**Comment by lreading** [comment]
Authentication is handled entirely differently in v2, and relies on JWTs and refresh tokens.  The user is given a toast notification if their refresh token expires as opposed to a page with a stack-trace.  Closing this as it's "done" in v2. :)
