### ISSUE TITLE
Upgrade from AngularJS to Angular

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#203]
**Describe what problem your feature request solves**
AngularJS end of life is December 2021
@lreading is working on the React version of Threat Dragon, version 2.0, and until that is ready it is desirable to migrate to Angular. This will remove time-pressure/deadlines from the version 2.0 development, with a better result.

**Describe the solution you'd like**
Follow the [Upgrading from AngularJS to Angular guide](https://angular.io/guide/upgrade#upgrading-from-angularjs-to-angular) to migrate to Angular 9 / 10 from AngularJS 1.8.x

**Additional context**

**Comment by lreading** [comment]
Closing as we will not be doing this upgrade.  2.0 is the next planned release, and is written in Vue.

**Comment by jgadsden** [comment]
Agreed, this is no longer needed as we now have version 2.0 using Vue
