### ISSUE TITLE
Change color of trust boundary

### ISSUE THREAD

**Issue by jdschoen** [OWASP/threat-dragon#207]
**Describe what problem your feature request solves**
Trust boundary is only green in color.  Threat modeling process that I prefer to follow is coloring trust boundaries where (blue is trusted and red is untrusted).  

**Describe the solution you'd like**
It would be great if when you click on a trust boundary and select to edit properties,  a drop down list of colors was available where you could select for the color of the trust boundary to display.

**Additional context**
Red and Blue are the only additional colors that I am specifically requesting.

**Comment by jgadsden** [comment]
Closing this as a Won't Do
We are removing the colors as much as possible from the diagrams. Depending on the context colors can be unhelpful, and there is discussion as to whether to remove the green from the trust boundary
