### ISSUE TITLE
Auto gap generated in Name property

### ISSUE THREAD

**Issue by jthDEV** [OWASP/threat-dragon#208]
**Describe the bug**
When I create a property name, the input field forces a blank after 12 characters

**Expected behavior**
Allows to also provide names with  

**Environment**
 - Version: [e.g. 1.3.1]
 - Platform: Desktop
 - OS: MacOS 
 
**To Reproduce**
Open Editor, create any object in a diagram and type in the name property. Instead e.g. "12345678901234" you will see "123456789012 3"
   
**Any additional context, screenshots, etc**
![Bildschirmfoto 2021-03-12 um 13 17 36](https://user-images.githubusercontent.com/20836127/110940564-653f0180-8337-11eb-8631-3dba8e904c40.jpg)

**Comment by jgadsden** [comment]
Hello @jthDEV , I have tested this with @lreading 's version 2.0 and it does not suffer from this behaviour

**Comment by jgadsden** [comment]
This is a 'Version 1.x only' and not present in version 2.x
Version 1.x is in a maintenance mode where we only apply security related patches, so if it is OK with you @jthDEV we can close this issue
