### ISSUE TITLE
Desktop: New model tests are skipped

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#213]
**Describe what problem your feature request solves**
The new-model tests for the Welcome Controller are skipped for the moment

**Describe the solution you'd like**
reinstate the new model tests

**Additional context**

**Comment by lreading** [comment]
Where the next planned release will be 2.0 (which will include a new desktop project), I think we can close this.  Thoughts @jgadsden ?

**Comment by jgadsden** [comment]
Agreed, this is no longer needed as we are concentrating on version 2.0
