### ISSUE TITLE
Desktop: PDF print tests are skipped

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#215]
**Describe the bug**
The tests for PDF print in 'test/spec/threatmodels/desktopreport_spec.js' are skipped using xit.

**Expected behavior**
It would be good to reinstate these tests

**Environment**
 - Version: 1.4.0
 - Platform: Desktop
 - OS: all of MacOS / Windows / Linux
 
**To Reproduce**
* clone github repo
* run command `npm test` at command line
* observe:
```
      PDF tests
        - should log an error
        - should save the PDF file with default file name
        - should save the PDF file with no default file name
        - should set the PDF options
        - should not save the PDF file on cancel
        - should not save the PDF file on null path
        ✓ should print the PDF file
        ✓ should handle a print PDF error
```

**Any additional context, screenshots, etc**

**Comment by lreading** [comment]
Where the next planned release will be 2.0 (which will include a new desktop project), I think we can close this. Thoughts @jgadsden ?

**Comment by jgadsden** [comment]
Agreed, this issue is no longer needed as version 2.0 will have different tests and a rewritten reporting feature
