### ISSUE TITLE
Desktop: Support for other character sets for files names + directories according to the OS default encoding

### ISSUE THREAD

**Issue by codeHorse87** [OWASP/threat-dragon#217]
As a result of [#59](https://github.com/OWASP/threat-dragon-desktop/issues/59) I propose to improve the support for utf-8 and unicode character sets in the file paths and names
I'm always frustrated when models can't be saved or opened when the target directory or model name includes non Latin1 characters 

**Describe the solution you'd like**

Support utf-8/unicode based on the default encoding of the operating system

**Describe alternatives you've considered**
Alternatively there can be a warning, or message to the user regarding the unhandled exception in [#59](https://github.com/OWASP/threat-dragon-desktop/issues/59) about the problem

**Comment by jgadsden** [comment]
This was also reported in #269 'Error on open invalidCharacterError'

**Comment by jgadsden** [comment]
the latest version of Threat Dragon supports extended (non Latin1) character sets
for example a model file `~/ÖVB/test.json` can be opened
