### ISSUE TITLE
Desktop: Unable to install snap package. Cannot find signature.

### ISSUE THREAD

**Issue by koberbe** [OWASP/threat-dragon#218]
**Describe the bug**
When trying to install the package threatdragon-1.3.0.amd64.snap, snap reports a signature error.

**To Reproduce**
1. Download "threatdragon-1.3.0.amd64.snap"
2. Run `snap install threatdragon-1.3.0.amd64.snap`
3. Output: `error: cannot find signatures with metadata for snap "threatdragon-1.3.0.amd64.snap"`

**Expected behavior**

**Screenshots**

**Environment:**
 - Device: laptop
 - OS: Kubuntu
 - Version: 20.04

**Comment by lreading** [comment]
We have begun to publish the snap directly to snapcraft: https://snapcraft.io/threat-dragon
The AppImage, deb or rpm will be the recommended installation methods for offline linux installs moving forward.
There's still a little work left to keep this 100% automated, but I will be working with the other maintainers closely to ensure that the snap store stays up to date until #112 is complete.

Closing this, as there's no signature issue when installing directly from the store.
