### ISSUE TITLE
Desktop: Landscape Diagram Export option

### ISSUE THREAD

**Issue by nickrmc83** [OWASP/threat-dragon#221]
**Is your feature request related to a problem? Please describe.**

👋  I've been using this great tool for a little while but we keep hitting a minor niggle which we'd love to see improved. When exporting reports using the Mac desktop app much of the time the diagrams include scrolls bars. It would be great to either be able to fit-to-width and/or output diagrams as landscape so that the scrollbars can be removed and so more space is available.

**Describe the solution you'd like**

The option to export diagrams in landscape to better support larger and more complex systems.

**Describe alternatives you've considered**

None

**Additional context**

**Comment by jauharbal** [comment]
Is Export option implemented on the Desktop version? been looking for the same but I couldn't find it.

**Comment by jgadsden** [comment]
Issue #127 duplicates this

**Comment by jgadsden** [comment]
This has been addressed in version 2.0.2 - the diagrams in the reports are scaled to fit and no longer have scroll bars
