### ISSUE TITLE
provide AutoUpdate for desktop installer

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#225]
This issue has been migrated from:
https://github.com/mike-goodwin/owasp-threat-dragon-desktop/issues/101

There is a branch for applying auto-updates using squirrel.  It should be cross platform for Windows, MacOS and Linux.
File `app/app.js` has been modified to not use autoupdate via PR OWASP/threat-dragon-desktop#102  because it was causing problems, but this modification can be undone when autoupdate is working:
```
//electron autoupdate
//Note: autoupdate has been disabled until this issue has been satisfied:
//      https://github.com/mike-goodwin/owasp-threat-dragon-desktop/issues/101
// app.run(['common', 'dialogs', 'electron', 'VERSION', require('./app/config.autoupdate')]);
```

**Comment by lreading** [comment]
This can probably be looked into again, as MacOS signing is done and Windows signing will be done in the very near future.

**Comment by jgadsden** [comment]
With both MacOS and Windows signing in place, this can be considered for version 2.0. It is not a pre-requisite for the version 2.0 release, but it would be nice to have.
It depends on having the electron wrapper in place

**Comment by jgadsden** [comment]
It may be easiest  to use electron's auto-updater:
https://www.electronjs.org/docs/latest/tutorial/updates

**Comment by jgadsden** [comment]
Decided to use electron/[update-electron-app](https://github.com/electron/update-electron-app)
