### ISSUE TITLE
Publish docker image to OWASP area on Docker Hub

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#242]
**Describe what problem your feature request solves**
Created a threatdragon user on Docker Hub: https://hub.docker.com/u/threatdragon
With container https://hub.docker.com/r/threatdragon/owasp-threat-dragon

**Describe the solution you'd like**
Ideally this would be in the OWASP area of Docker Hub: https://hub.docker.com/u/owasp

**Additional context**
It would be great if this was integrated with the build/release pipeline. Dockerhub do not do an organisation account that is able to cover all the users OWASP has. Waiting on Dockerhub for this one

**Comment by ShubhamPalriwala** [comment]
Any update with the OWASP area here?

**Comment by jgadsden** [comment]
OWASP have contacted Dockerhub, but Dockerhub do not do an organisation account that is able to cover all the users OWASP has. Waiting on Dockerhub for this one

**Comment by jgadsden** [comment]
This is not going to be done by dockerhub for OWASP, so all we can do is close it and wait for notification from OWASP in the future
