### ISSUE TITLE
Can't install Threat Dragon on Mac

### ISSUE THREAD

**Issue by adiun** [OWASP/threat-dragon#244]
**Describe the bug**
Previously I was able to install Threat Dragon on Mac by following [these instructions](https://github.com/OWASP/threat-dragon-desktop/wiki/FAQs#why-do-i-get-developer-can-not-be-verified-errors-after-installing-on-macos) but now after clicking `Open Anyway` I don't see an option to `Open`. It's the exact same prompt as before.

![image](https://user-images.githubusercontent.com/120026/127069801-bf414380-4d13-43da-8ef7-ce1d2e6e3b23.png)

**Expected behaviour**
Ideally, should just be able to open Threat Dragon Mac without unidentified developer warnings.

**Environment**
 - Version: 1.4.0
 - Platform: Desktop App
 - OS: MacOS Big Sur 11.4
 - Browser: Chrome

**To Reproduce**
* Download DMG, double-click to install, drag to Applications folder, and then open in Applications folder.

**Comment by jgadsden** [comment]
Hello @adiun  - yes, apologies for this. The MacOS images are now signed but not notarised. We are working on this, but until it happens could you follow this (newly  written) FAQ and see if it now works for you:

https://github.com/OWASP/threat-dragon/wiki/FAQs#why-do-i-get-developer-can-not-be-verified-errors-after-installing-on-macos

**Comment by jgadsden** [comment]
I have tried this out  and the new FAQ works. This should be sorted out in version 1.4.1 which is due August 2021 (ie this month).

Hope it is OK to close this now @adiun ? Please reopen if you cannot open the MacOS image
