### ISSUE TITLE
Support github enterprise

### ISSUE THREAD

**Issue by danielpops** [OWASP/threat-dragon#250]
**Describe what problem your feature request solves**
The github oauth configuration assumes that you're using github.com and doesn't work with github enterprise. 

**Describe the solution you'd like**
A configuration in .env (or equivalent for prod) that lets you specify a github enterprise url

**Comment by lreading** [comment]
Thanks for the great suggestion, @danielpops !

This seems like it could be a quick win.  Threat Dragon uses [octonode](https://github.com/pksunkara/octonode) to connect to github, and it appears to support enterprise with relatively little config.

I don't have access to an enterprise account: if I put together a PR, would you be willing to test it to ensure it's working as expected?

**Comment by jgadsden** [comment]
I am just about to release version 1.5.0 - delayed because of problems with electron-builder config file - so depending on how quick this win is it can go in 1.5.0 or if it is a bit slower we can do a version 1.5.1

**Comment by lreading** [comment]
@danielpops - if you have a chance, can you test out this branch? https://github.com/OWASP/threat-dragon/tree/feature/enterprise-github-config-250

I added config options for a Github enterprise hostname, and optionally port/protocol.  The only update you should need to test the change and the enterprise integration is adding `GITHUB_ENTERPRISE_HOSTNAME` to your env file

**Comment by danielpops** [comment]
@lreading hey, this seems to have *kind of* worked. I was able to authenticate through my github enterprise / sso credentials. However, the app isn't able to view the repos, with a `Bad credentials` error messgae

```
{
    "hostname": "e2c837b09ef2",
    "level": 50,
    "msg": "[HttpError: Bad credentials] {\n  statusCode: 401,\n  headers: {\n    server: 'GitHub.com',\n    date: 'Tue, 19 Oct 2021 02:00:48 GMT',\n    'content-type': 'application/json; charset=utf-8',\n    'content-length': '80',\n    'x-github-media-type': 'github.v3; format=json',\n    'x-ratelimit-limit': '60',\n    'x-ratelimit-remaining': '53',\n    'x-ratelimit-reset': '1634610711',\n    'x-ratelimit-used': '7',\n    'x-ratelimit-resource': 'core',\n    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',\n    'access-control-allow-origin': '*',\n    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',\n    'x-frame-options': 'deny',\n    'x-content-type-options': 'nosniff',\n    'x-xss-protection': '0',\n    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',\n    'content-security-policy': \"default-src 'none'\",\n    vary: 'Accept-Encoding, Accept, X-Requested-With',\n    'x-github-request-id': 'EDBE:5D3B:37E507:3E4037:616E26D0',\n    connection: 'close'\n  },\n  body: {\n    message: 'Bad credentials',\n    documentation_url: 'https://docs.github.com/rest'\n  }\n}",
    "name": "threatdragon",
    "pid": 7,
    "req_id": "3a58fc69-3010-49f7-8270-1230848bc8c9",
    "security": false,
    "time": "2021-10-19T02:00:48.801Z",
    "userName": "dpopes",
    "v": 0
}
```

The relevant yet redacted .env file i'm using:
```
GITHUB_CLIENT_ID=<the client id>
GITHUB_CLIENT_SECRET=<the client secret>
GITHUB_SCOPE=repo
NODE_ENV=development
SESSION_STORE=local
SESSION_SIGNING_KEY=<the signing key>
SESSION_ENCRYPTION_KEYS='[{"isPrimary": true, "id": 0, "value": "<the signing key>"}]'
```

I haven't yet dug into this at all, but can take a pass at debugging and try to suss out what might be going on if you like. I should also note that I've not actually tried getting this to work with public github, so I may just be missing something otherwise fundamental. Feel free to point me in the right direction for things that I may have likely messed up :)

**Comment by lreading** [comment]
Hey @danielpops thanks for taking a look!!!

Your `.env` file looks to be missing `GITHUB_ENTERPRISE_HOSTNAME`, however I suspect that was a bad copy/paste since you're able to authenticate against the enterprise account?

I can't make sense of why it's reaching out to api.github.com after authenticating against the enterprise account.  

ThreatDragon uses octonode to connect to GitHub.  According to [OctoNode's Documentation](https://github.com/pksunkara/octonode#build-a-client-from-a-different-host), you should be able to simply add a hostname parameter to the client and it will do the rest for you.  

All of the GH communication logic is in https://github.com/OWASP/threat-dragon/blob/feature/enterprise-github-config-250/td.server/src/repositories/threatmodelrepository.js#L5 and every call to the repository should be using the `getClient` function, which should be reading the enterprise info from the env.  

I'll be taking a closer look at how octonode works, make sure we're on a relatively recent version of it, etc etc. It's also very possible that I'm missing something here; please do let me know if that's the case!

**Comment by lreading** [comment]
I _think_ I found what I had missed! :sweat_smile:  Just the authentication piece of things... you know, nothing too important.

What's odd to me is that this would have the opposite effect of what you are seeing.  Currently it's authenticating against github.com, then _should_ be using the enterprise host for api calls.  Unless I misunderstood, what you're seeing is the opposite: it authenticates against the enterprise host then attempts to use github for API calls.

Threat Dragon uses passport / passport-github for auth.  I'll be using [this documentation](https://github.com/jaredhanson/passport-github#enterprise-corporate-github) to add the missing parameters to hopefully make authentication work.

I'll be updating the branch tonight to see if it does the trick for you.  I'll update this comment with more info when it's done, as it may require another env var.

**Comment by danielpops** [comment]
@lreading thanks again for the support, I'm happy to work through the issues with you.

With the HEAD of your branch I now get a 404 when browsing existing repositories or creating a new threat model (this is presumably the bug you're referring to?) =>
```
{"name":"threatdragon","hostname":"3d2ee32f5858","pid":7,"req_id":"b425501f-a2cc-4e66-9819-4cafb1291ac3","level":50,"security":false,"userName":"dpopes","msg":"[HttpError: Not Found] {\n  statusCode: 404,\n  headers: {\n    server: 'GitHub.com',\n    date: 'Tue, 02 Nov 2021 16:59:26 GMT',\n    'content-type': 'application/json; charset=utf-8',\n    'content-length': '89',\n    'x-oauth-scopes': 'public_repo',\n    'x-accepted-oauth-scopes': 'repo',\n    'x-oauth-client-id': '34329e031934f883ac33',\n    'x-github-enterprise-version': '3.0.4',\n    'x-github-media-type': 'github.v3; format=json',\n    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',\n    'access-control-allow-origin': '*',\n    'x-github-request-id': '4eea910a-ea6c-45d8-9bae-37610a313aa8',\n    'strict-transport-security': 'max-age=31536000; includeSubdomains',\n    'x-frame-options': 'deny',\n    'x-content-type-options': 'nosniff',\n    'x-xss-protection': '1; mode=block',\n    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',\n    'content-security-policy': \"default-src 'none'\",\n    'x-runtime-rack': '0.067535',\n    connection: 'close'\n  },\n  body: {\n    message: 'Not Found',\n    documentation_url: 'https://docs.github.com/enterprise/3.0/rest'\n  }\n}","time":"2021-11-02T16:59:26.805Z","v":0}
```

**Comment by lreading** [comment]
I don't believe that's the same.  Are you running `npm run build` before `npm run start`? 

As an aside, we should probably change the start command to do the build step as well... It's not super streamlined or intuitive at the moment.

**Comment by danielpops** [comment]
I've just been doing 

```
docker build -t dpopes-owasp-threat-dragon . && docker run -it --rm -p 3000:3000 -v $(pwd)/.env:/app/.env --init --name dpopes-owasp-threat-dragon dpopes-owasp-threat-dragon
```

I will give it another shot on a fresh setup and/or force an npm run build

**Comment by danielpops** [comment]
@lreading I tried the branch out on a fresh setup and still observe the same 404 when browsing existing repositories or creating a new threat model.

**Comment by danielpops** [comment]
@lreading hey, just following-up on this thread after a while of inactivity. Is there anything else I can do to help debug what's going on here?

**Comment by lreading** [comment]
Hey @danielpops  - I apologize, this fell off my radar. :) 

I'm at a bit of a loss here, and my GH enterprise trial expired.  It was one of those "works on my machine" type of deals, so I'm not entirely sure what went wrong or why.

We could take a look at the URLs it's connecting to as well and see if anything jumps out.  The 404 you posted is somewhat interesting, as it's pointing to the public documentation for GH Enterprise version 3, and I'm not sure why Octonode would be making a request there to beg with.

**Comment by jgadsden** [comment]
Hello @danielpops and @lreading 

Version 1.6 is intended to be the last 1.x version . Could we start afresh on this feature, but targeting version 2.0?

Testing Github Enterprise has been a real problem, so we may have to lean heavily on @danielpops , but on the up-side version 2.0 code is much easier to develop and debug .

Should we close this issue, and its associated PR, and @danielpops did you want to raise a new issue for version 2.0?

**Comment by danielpops** [comment]
@jgadsden sure, I can re-create this issue for the 2.0 release. I presume this is the `v2-development` branch?

**Comment by jgadsden** [comment]
Yes, thanks @danielpops , if you use the v2-development branch then this is the working version 2.x

**Comment by lreading** [comment]
Thanks guys! I'll take another swing at this in the v2 branch. :) I'll close this issue now and we can coordinate in the new one.
