### ISSUE TITLE
Windows: Cannot find module .....demo-threat-model.json

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#262]
**Describe the bug**
On Windows using the executable on the release page for version 1.5.3, when clicking the "Get started by creating a completely new, empty threat model" or "Explore a sample model" option, an error message is shown saying that it cannot find module `../../ThreatDragonModels/new-model/new-model.json`

You can still create a new model by navigating to File > New

This was graciously reported by our friend Simon.

**Expected behaviour**
A new model is created when clicking either option

**Environment**
 - Version: 1.5.3
 - Platform: Desktop App
 - OS: Windows (unknown version)

**To Reproduce**
- Click "Get started by creating a completely new, empty threat model." OR "Explore a sample model. This is a good option if you are new to Threat Dragon"
- An error is displayed

This seems to not affect the Linux snapcraft distribution.  I did not see this behavior when testing on MacOS with the signed/notarized release either, though it may be worth another check in case I missed something.

**Comment by jgadsden** [comment]
Ah, I know what has caused this and the fix is not too hard. Wish I had caught this before version 1.5.3 - all to do with consolidating the file set and shuffling files around , but then making sure it is cross-platform.

@lreading shall I take this on? I have a fix in mind

**Comment by jgadsden** [comment]
Having updated some code of mine, I realise that for some reason the threat model json files are not appearing in the windows installer.
