### ISSUE TITLE
v2 - Internationalization

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#278]
**Describe what problem your feature request solves**
Threat Dragon v2 should have support for internationalization and translations

**Describe the solution you'd like**
Support i18n in some way

**Additional context**
v2 should be architected in such a way that i18n is built into the application at the ground level.  The Threat Dragon community can help with translation files later.
Additionally, documentation should be added for how to help and/or add translations

I've intentionally scoped this to v2, as it's still in the early(ish) stages of development.

Reference: https://vue-i18n.intlify.dev/guide/#html

**Comment by jgadsden** [comment]
Good to see this, thanks @lreading, this is going to be appreciated by the Threat Dragon community

This will sort out the various issues when the file paths have (correctly) non Latin1 characters in them, and Threat Dragon does not handle these correctly.

@bubuaiyier , hope this gives context to #269

**Comment by lreading** [comment]
This is done in v2, though the only translation file is in English.  The v2 docs contain information on how to add a new translation or otherwise contribute translations.
