### ISSUE TITLE
Automate Release Notifications

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#291]
**Describe what problem your feature request solves**
Automate the release notifications in social/community channels

**Describe the solution you'd like**
Using the "release" GitHub action, make notifications on new releases of Threat Dragon.
- Slack
- Twitter (?)
- Somewhere else?

**Additional context**
The slack notification would go to #project-threat-dragon (feel free to join us if you're reading this!)
It looks like we could trigger a separate action when a release is switched from draft to published: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onevent_nametypes

If we do that, we should consider moving the snapcraft build/publish to that action as well since it is technically being released before the other channels.

**Comment by jgadsden** [comment]
Possibly follow this blog to tweet release status: https://blog.azcodez.com/twitter-tweet-bot-using-github-actions

**Comment by jgadsden** [comment]
Threat Dragon has left Twitter, and although it would be nice to have automation ... in a way it is also good to do this manually. Threat Dragon releases are not very often at all, so it is satisfying to be able to hand craft release announcements
