### ISSUE TITLE
Support for logical grouping of processes and data stores

### ISSUE THREAD

**Issue by kohlerbn** [OWASP/threat-dragon#292]
**Describe what problem your feature request solves**
Various processes and data stores can be grouped with a drawing object in order to show their logical association. For example, imagine a web server and database - should be represented as a process and a data store, but together are logically the server-side systems or the "application". 

**Describe the solution you'd like**
I'm thinking of some sort of a dotted line faded box that can wrap around current drawing objects to show their grouping.

**Additional context**
None.

**Comment by jgadsden** [comment]
closing this as it is unlikely to be implemented
