### ISSUE TITLE
List users of Threat Dragon

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#294]
**Describe what problem your feature request solves**
@mike-goodwin  points out that it would be interesting to get a feel for who and how many people are using Threat Dragon

**Describe the solution you'd like**
@mike-goodwin suggests a new page in the github repo listing people using threat dragon. (e.g. like this https://github.com/argoproj/argo-cd/blob/master/USERS.md)

**Additional context**

**Comment by ShubhamPalriwala** [comment]
@mike-goodwin Do we have a list of our users?

**Comment by jgadsden** [comment]
no list of users, and the only method we can think of is if companies contact us with an 'OK to use their name' for this page
We think it would be better to have a Threat  Dragon forum? a bit like OWASP ZAP's?
