### ISSUE TITLE
Desktop: electron from 9.4.4 to 11.5.0

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#296]
**Describe what problem your feature request solves**
Electron needs to be upversioned to 11.5.0, ideally the latest version (eg 15.3.0)

**Describe the solution you'd like**
```
cd td.desktop
npm install --save-dev electron@15.3.0
npm run build
```

**Additional context**
This is a major change that could break things. Needs to be tested (a lot) before we merge:

**Comment by ShubhamPalriwala** [comment]
Update:
Woah okay, so apparently all the test cases succeed after upgrading the electron version:
![image](https://user-images.githubusercontent.com/55556994/140635575-07d7f720-ce38-4571-a87b-094cff284e5c.png)

**However** the app is stuck on it's loading screen with multiple electron-specific errors in the console.
Looking and debugging those one by one 🐛

**Comment by jgadsden** [comment]
Thanks for doing this @ShubhamPalriwala , if there is any help I can give then feel free to ask

**Comment by jgadsden** [comment]
Agreed, that sums up the situation well

**Comment by jgadsden** [comment]
We may not do this for version 1.6.x , because most of our effort will now be getting version 2.0 ready for release.
We will also be using electron differently for version 2.x, based not on shared code but on wrapping the web application, so this probably can be closed now. Is that OK with you @ShubhamPalriwala ?

**Comment by ShubhamPalriwala** [comment]
Yeah peace! I'll look for some other issue to work on! Thank you for all the guidance and help here everyone!

**Comment by jgadsden** [comment]
@ShubhamPalriwala there is a lot of development for Threat Dragon version 2.0, if any of it interests you?
https://github.com/OWASP/threat-dragon/projects/4

**Comment by ShubhamPalriwala** [comment]
Hey thank you. There seems a lot of opportunities here. Anything that can be a good starting point for me according to you? Would love to start

**Comment by jgadsden** [comment]
Well, depends on how poly-lingual you are ... but there is the internationalisation, similar to one that @taoyiyang1 is working on: https://github.com/OWASP/threat-dragon/issues/350

and be sure to work off V2 development, I made a mistake just  now and branched off main instead of branching off :
https://github.com/OWASP/threat-dragon/tree/v2-development

also if you are familiar with electron ther eis #334 that is becoming urgent

**Comment by lreading** [comment]
I'm hoping to go through version 2 next week and create small, workable issues for the remaining items.  They will all be (labeled as version-2.0)]https://github.com/OWASP/threat-dragon/issues?q=is%3Aissue+is%3Aopen+label%3Aversion-2.0], so if you have the time/desire to grab one of them, all help is appreciated!

If you need any help, context or anything else, feel free to open an issue, tag Jon or myself on the issue, or you can (join us in Slack)[https://owasp.org/slack/invite] (#project-threat-dragon) as well.
