### ISSUE TITLE
Scan 3rd party dependencies with OWASP Dependency Check

### ISSUE THREAD

**Issue by derekhillhp** [OWASP/threat-dragon#303]
As part of a secure software build, we need to know the status (vulnerability and perhaps license type) of each 3rd party component that is included in the released product. OWASP Dependency Check solves that need and it should be incorporated as part of the build process / pipeline.
https://owasp.org/www-project-dependency-check/

An example of the need for this is this bug filed earlier. https://github.com/OWASP/threat-dragon/issues/256

**Comment by lreading** [comment]
We've decided to go with Trivy for this job.  Dependency Check is a wonderful tool, but Trivy is able to scan dependencies in our code as well as the image being built at the same time, so it seemed like a better fit at this time. 

Thanks again for raising the issue for us and the conversation in Slack.  Dependency management is critical, and an area where we definitely needed to improve.  #327 is going to bring us a long ways, but I'm sure there will be more work to do in the future!
