### ISSUE TITLE
Documentation - Clarify Docker Usage

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#313]
**Describe what problem your feature request solves**
The current documentation in the readme, docs and setup-env files are not clear enough regarding how to use Threat Dragon in the pre-made docker containers.

**Describe the solution you'd like**
Update all documentation to ensure that a specific tag/version should be used when running Threat Dragon

**Additional context**
Do we want to add a new "stable" tag or similar for the latest official release?
This need was identified in #311

**Comment by lreading** [comment]
@jgadsden - Thoughts on maintaining a "stable" tag in docker that is always the latest released version?

**Comment by jgadsden** [comment]
> @jgadsden - Thoughts on maintaining a "stable" tag in docker that is always the latest released version?

Yes, that makes a lot of sense - and 'stable' sounds a good clear term to use
