### ISSUE TITLE
Threat dragon online only uses public git repos to save threat models

### ISSUE THREAD

**Issue by huwjeffries** [OWASP/threat-dragon#324]
**Describe the bug**
When using threat dragon online (https://threatdragon.org/) it will only accept a public git repo to save the threat model. This is no good for a corporate environment as threat models can't be publicly available. We wanted to use the online version as it is said to be slightly better than the desktop version in terms of being able to move lines around with out it adding additional control points, having a better undo when this happens, larger settings cog on lines so you can enter a threat, etc. Please could you advise?

**Expected behaviour**
Ability to select private git repo. 

**Environment**
 - Online version in latest chrome browser 

**To Reproduce**
See description.

**Comment by jgadsden** [comment]
Hello @huwjeffries - could you try setting GITHUB_SCOPE? Set this to 'repo' if you want access to private repos, it defaults to public. There is some more info in the docs at https://docs.threatdragon.org/setup-env/

I do not have any private github repos myself, so could you tell me if it still tests out OK? It  was tested some time ago, and I hope it still owrks as expected

**Comment by lreading** [comment]
Hi @huwjeffries 
The threatdragon.org site is meant to serve as a demo area.  In the future, we may have a more permanent/reliable solution that is publicly available. Most users opt to host the web version in their own environment, or use the desktop version.  Threat Dragon saves all the models as JSON, so many organizations use source control alongside the web version for change/version management (I know you said you're avoiding additional control points, just thought it was worth mentioning!)

If you're hosting your own instance, there's [some configuration](https://github.com/OWASP/threat-dragon/blob/main/setup-env.md) that needs to be done, which is what @jgadsden was referring to.  I created a private repo to test this and it seems that setting GITHUB_SCOPE to `repo` still works as expected.  There's also multiple [deployment/installation methods](https://github.com/OWASP/threat-dragon#installing) including a [docker image.](https://hub.docker.com/r/threatdragon/owasp-threat-dragon)  The configuration docs also include an example docker-compose file that shows how to stand up the web version with [file-based secrets](https://github.com/OWASP/threat-dragon/blob/main/setup-env.md#file-based-secrets) (eg docker secrets if you're running in swarm mode, or in kubernetes)

Let us know if you have any other questions or if we can help!

**Comment by huwjeffries** [comment]
Thanks, that's good to know.

**Comment by jgadsden** [comment]
We can close this issue now, if that is OK with @huwjeffries ?

**Comment by huwjeffries** [comment]
Yes, please go ahead and close it.
