### ISSUE TITLE
使用npm start时发生错误 (An error occurred when using npm start)

### ISSUE THREAD

**Issue by taoyiyang1** [OWASP/threat-dragon#328]
![image](https://user-images.githubusercontent.com/53025630/146702767-4becc7d5-df48-44e1-bebf-e5434d28b3ce.png)
不知道怎么办了 help me

**Comment by jgadsden** [comment]
Hello @taoyiyang1 

Can you check that you are using the following commands?

```
git clone git@github.com:OWASP/threat-dragon.git
cd threat-dragon
npm install
npm start
```

I have attached my console output for you to compare
[console.txt](https://github.com/OWASP/threat-dragon/files/7743225/console.txt)

The difference between our two builds is : 

```
> threat-dragon-site@1.6.0 build:core
> ./node_modules/.bin/copyfiles --error --up 2 '../td.desktop/core/**/*' ./
```

where you seem to have an extra parameter to the build:core?

If it is still failing then I wonder if this is a problem with `./node_modules/.bin/copyfiles` not managing with extended character sets in the path names on Windows ... so could you try again but using a source tree path such as : 
`D:\temp\threat-dragon` ? So that extended character set  does not appear in the path

**Comment by taoyiyang1** [comment]
您好，我使用以下命令
`git clone --recursive git://github.com/owasp/threat-dragon.git
npm install
npm start`

附上我的控制台错误
[console.txt](https://github.com/OWASP/threat-dragon/files/7743507/console.txt)

希望您能看一下，告诉我出错的原因

感谢！

**Comment by taoyiyang1** [comment]
> 您好，我使用以下命令
git clone --recursive git://github.com/owasp/threat-dragon.git npm install npm start

附上我的识别错误
console.txt

希望你能看一下，告诉我出错的原因

谢谢！

**Comment by taoyiyang1** [comment]
> 你好@taoyiyang1
> 
> 您可以检查您是否正在使用以下命令吗？
> 
> ```
> git clone git@github.com:OWASP/threat-dragon.git
> cd threat-dragon
> npm install
> npm start
> ```
> 
> 我附上了我的控制台输出供你比较 [console.txt](https://github.com/OWASP/threat-dragon/files/7743225/console.txt)
> 
> 我们两个版本之间的区别是：
> 
> ```
> > threat-dragon-site@1.6.0 build:core
> > ./node_modules/.bin/copyfiles --error --up 2 '../td.desktop/core/**/*' ./
> ```
> 
> 您似乎对 build:core 有一个额外的参数？
> 
> 如果它仍然失败，那么我想知道这是否是`./node_modules/.bin/copyfiles`没有在 Windows 上的路径名中使用扩展字符集进行管理的问题......所以你能再试一次但使用源树路径，例如 : `D:\temp\threat-dragon`吗？这样扩展字符集就不会出现在路径中

您好，我使用以下命令
git clone --recursive git://github.com/owasp/threat-dragon.git 
npm install 
npm start

附上我的控制台错误
console.txt

希望你能看一下，告诉我出错的原因

谢谢！

**Comment by taoyiyang1** [comment]
> 你好@taoyiyang1
> 
> 您可以检查您是否正在使用以下命令吗？
> 
> ```
> git clone git@github.com:OWASP/threat-dragon.git
> cd threat-dragon
> npm install
> npm start
> ```
> 
> 我附上了我的控制台输出供你比较 [console.txt](https://github.com/OWASP/threat-dragon/files/7743225/console.txt)
> 
> 我们两个版本之间的区别是：
> 
> ```
> > threat-dragon-site@1.6.0 build:core
> > ./node_modules/.bin/copyfiles --error --up 2 '../td.desktop/core/**/*' ./
> ```
> 
> 您似乎对 build:core 有额外的参数？
> 
> 如果它仍然失败，那么我想知道这是否是`./node_modules/.bin/copyfiles`没有在 Windows 上的路径名中使用字符集进行管理的问题......所以你能再试一次但源树路径，例如： `D:\temp\threat-dragon`吗？这样扩展字符集就不会出现在路径中



> 你好@taoyiyang1
> 
> 您可以检查您是否正在使用以下命令吗？
> 
> ```
> git clone git@github.com:OWASP/threat-dragon.git
> cd threat-dragon
> npm install
> npm start
> ```
> 
> 我附上了我的控制台输出供你比较 [console.txt](https://github.com/OWASP/threat-dragon/files/7743225/console.txt)
> 
> 我们两个版本之间的区别是：
> 
> ```
> > threat-dragon-site@1.6.0 build:core
> > ./node_modules/.bin/copyfiles --error --up 2 '../td.desktop/core/**/*' ./
> ```
> 
> 您对 build:core 有额外的参数吗？
> 
> 如果它仍然失败，那么我想知道这是否是`./node_modules/.bin/copyfiles`没有在 Windows 上的路径名中使用字符集进行管理的问题......所以你能再试一次但源树路径，例如： `D:\temp\threat-dragon`吗这样？字符集就不会出现在路径中

你好，我使用以下命令
git clone --recursive git://github.com/owasp/threat-dragon.git
npm install
npm start

附上我的控制台输出错误
[console.txt](https://github.com/OWASP/threat-dragon/files/7743539/console.txt)


希望你能看一下，告诉我出错的原因

谢谢！

**Comment by taoyiyang1** [comment]
> 你好@taoyiyang1
> 
> 您可以检查您是否正在使用以下命令吗？
> 
> ```
> git clone git@github.com:OWASP/threat-dragon.git
> cd threat-dragon
> npm install
> npm start
> ```
> 
> 我附上了我的控制台输出供你比较 [console.txt](https://github.com/OWASP/threat-dragon/files/7743225/console.txt)
> 
> 我们两个版本之间的区别是：
> 
> ```
> > threat-dragon-site@1.6.0 build:core
> > ./node_modules/.bin/copyfiles --error --up 2 '../td.desktop/core/**/*' ./
> ```
> 
> 您似乎对 build:core 有一个额外的参数？
> 
> 如果它仍然失败，那么我想知道这是否是`./node_modules/.bin/copyfiles`没有在 Windows 上的路径名中使用扩展字符集进行管理的问题......所以你能再试一次但使用源树路径，例如 : `D:\temp\threat-dragon`吗？这样扩展字符集就不会出现在路径中

你好，我使用以下命令
git clone --recursive git://github.com/owasp/threat-dragon.git
npm install
npm start

附上我的输出错误
[console.txt](https://github.com/OWASP/threat-dragon/files/7743560/console.txt)


希望你能看一下，告诉我出错的原因

谢谢！

**Comment by taoyiyang1** [comment]
> 你好@taoyiyang1
> 
> 您可以检查您是否正在使用以下命令吗？
> 
> ```
> git clone git@github.com:OWASP/threat-dragon.git
> cd threat-dragon
> npm install
> npm start
> ```
> 
> 我附上了我的控制台输出供你比较 [console.txt](https://github.com/OWASP/threat-dragon/files/7743225/console.txt)
> 
> 我们两个版本之间的区别是：
> 
> ```
> > threat-dragon-site@1.6.0 build:core
> > ./node_modules/.bin/copyfiles --error --up 2 '../td.desktop/core/**/*' ./
> ```
> 
> 您似乎对 build:core 有额外的参数？
> 
> 如果它仍然失败，那么我想知道这是否是`./node_modules/.bin/copyfiles`没有在 Windows 上的路径名中使用字符集进行管理的问题......所以你能再试一次但源树路径，例如： `D:\temp\threat-dragon`吗？这样扩展字符集就不会出现在路径中

**Comment by taoyiyang1** [comment]
> 你好@taoyiyang1
> 
> 您可以检查您是否正在使用以下命令吗？
> 
> ```
> git clone git@github.com:OWASP/threat-dragon.git
> cd threat-dragon
> npm install
> npm start
> ```
> 
> 我附上了我的控制台输出供你比较 [console.txt](https://github.com/OWASP/threat-dragon/files/7743225/console.txt)
> 
> 我们两个版本之间的区别是：
> 
> ```
> > threat-dragon-site@1.6.0 build:core
> > ./node_modules/.bin/copyfiles --error --up 2 '../td.desktop/core/**/*' ./
> ```
> 
> 您似乎对 build:core 有一个额外的参数？
> 
> 如果它仍然失败，那么我想知道这是否是`./node_modules/.bin/copyfiles`没有在 Windows 上的路径名中使用扩展字符集进行管理的问题......所以你能再试一次但使用源树路径，例如 : `D:\temp\threat-dragon`吗？这样扩展字符集就不会出现在路径中

你好@jgadsden 
我使用以下命令
git clone --recursive git://github.com/owasp/threat-dragon.git
npm install
npm start

附上我的输出错误
[console.txt](https://github.com/OWASP/threat-dragon/files/7743586/console.txt)

希望你能看一下，告诉我出错的原因

谢谢！

**Comment by jgadsden** [comment]
Hello @taoyiyang1  - the problem seems to be a dependency of dtrace-provider and node-gyp. It looks like it is searching for Python but can not find it. Can you install Python on your development machine?

Otherwise if you are just wanting to run Threat Dragon, rather than build it from source, then you can download from the releases area : https://github.com/OWASP/threat-dragon/releases

**Comment by taoyiyang1** [comment]
> 你好@taoyiyang1 - 问题似乎是 dtrace-provider 和 node- gyp的依赖。看起来它正在搜索 Python 但找不到它。你能在你的开发机器上安装 Python 吗？
> 
> 否则，如果您只想运行 Threat Dragon，而不是从源代码构建它，那么您可以从发布区下载：[https](https://github.com/OWASP/threat-dragon/releases) : [//github.com/OWASP/threat-dragon/releases](https://github.com/OWASP/threat-dragon/releases)

好的，我现在来安装，谢谢你的回答

**Comment by taoyiyang1** [comment]
> 你好@taoyiyang1 - 问题似乎是 dtrace-provider 和 node- gyp的依赖。看起来它正在搜索 Python 但找不到它。你能在你的开发机器上安装 Python 吗？
> 
> 否则，如果您只想运行 Threat Dragon，而不是从源代码构建它，那么您可以从发布区下载：[https](https://github.com/OWASP/threat-dragon/releases) : [//github.com/OWASP/threat-dragon/releases](https://github.com/OWASP/threat-dragon/releases)

你好 @jgadsden 
我已经成功安装了 Python 运行npm install  npm start控制台依旧报错

控制台错误信息
[console.txt](https://github.com/OWASP/threat-dragon/files/7744198/console.txt)

因为需要不得不从源代码构建，希望你能帮到我

谢谢

**Comment by taoyiyang1** [comment]
hello @jgadsden 

I used VS to run the NPM install command successfully, but still reported an error when using the NPM start command, as shown in the top image

console message
[console.txt](https://github.com/OWASP/threat-dragon/files/7749313/console.txt)

**Comment by jgadsden** [comment]
Hello @taoyiyang1 , thankyou for looking into this. I will try and repeat your issue soon. I run MacOS and Linux, but not Windows, so repeating this problem is not so easy for me. I have an old and cranky Windows box that I will get out and see if I can repeat this.

It seems `copyfiles` is broken for some reason. Just to get you going do you want to replace line 6 in `td.site\package.json` from 
`    "build": "npm-run-all clean build:css build:min build:fonts build:core bundle",`
to 
`    "build": "npm-run-all clean build:css build:min build:fonts bundle",`

and then copy manually the core directory and directories under it to td.site? 
So copy `td.desktop\core` and all sub-dirs to `td.site\core` using your file manager

@andk123 or @lreading I guess you are OK building on your Windows machines?

**Comment by taoyiyang1** [comment]
hello @jgadsden 
Using the method you provided, I ran it successfully，But there was an error after login authorization，Could you please help me find out what the reason is? How to solve

![image](https://user-images.githubusercontent.com/53025630/146892694-8c6536e1-f92e-4e24-9d29-91985693ccac.png)

**Comment by jgadsden** [comment]
Hello @taoyiyang1 - we are getting closer, good to see. Have you followed the env instructions here:
https://github.com/OWASP/threat-dragon/blob/main/setup-env.md

**Comment by taoyiyang1** [comment]
> 你好@taoyiyang1 - 我们越来越近了，很高兴看到。您是否按照此处的 env 说明进行操作：[https](https://github.com/OWASP/threat-dragon/blob/main/setup-env.md) : [//github.com/OWASP/threat-dragon/blob/main/setup-env.md](https://github.com/OWASP/threat-dragon/blob/main/setup-env.md)

hello @jgadsden 

Yes, I created the OAuth application as documented, I don't know why I still get an error , I would like to know your private email address, let you have a look at the Settings in OAuth and the contents in. Env file

**Comment by taoyiyang1** [comment]
hello @jgadsden 

I have logged in successfully. The previous login error may be due to network reasons. Because I use a VPN proxy, I sometimes get login errors. 

I did this according to the online method, do you think it is effective
`td.serve\src\config\passport.config`

![image](https://user-images.githubusercontent.com/53025630/147047793-f64152d3-beba-4e2d-bd87-63b31df5dda5.png)

**Comment by jgadsden** [comment]
Superb @taoyiyang1 , I was getting round to replying to your earlier error but you have now fixed. it. Very interesting that you had a problem when working on a VPN - did you want to raise an issue for this specifically? It may be that we need another env setting for 'proxy' true or false (probably called something like GITHUB_PROXY)

There is still the problem you found with `npm install` in your environment. I will try and repeat this today and get back to you on what I find

Thanks again for your perseverance with Threat Dragon!

**Comment by taoyiyang1** [comment]
> 精湛的@taoyiyang1，我正准备回复您之前的错误，但您现在已修复。它。非常有趣的是，您在使用 VPN 时遇到了问题 - 您想专门为此提出问题吗？可能是我们需要另一个 'proxy' 的 env 设置为真或假（可能称为 GITHUB_PROXY 之类的东西）
> 
> 您`npm install`在环境中发现的问题仍然存在。我今天会尝试重复这个，然后就我的发现回复你
> 
> 再次感谢您对威胁龙的坚持！

hello @jgadsden 

I'm not going to raise this issue, but you can add it to your Env Settings.  I've summarized what you need to run successfully on Windows

1. Python needs to be installed  
2. Use VS instead of VS Code
3. When running NPM install with VS, you need to manually install two packages based on the error  
4. Error occurred in copyFiles
5. Using a VPN Proxy  

I have to solve these problems before I can run successfully

**Comment by jgadsden** [comment]
Many thanks for this @taoyiyang1 , and I can confirm what you see on my Windows machine as well. I will try and work back to find where these problems were introduced.

There are probably at least two issues to be raised - thanks again!

**Comment by taoyiyang1** [comment]
hello @jgadsden 
How can I get in touch with you.?

**Comment by jgadsden** [comment]
Hello @taoyiyang1 - sure, contact me any time at jon.gadsden@owasp.org. The contact details of the Threat Dragon leaders are listed at : https://owasp.org/www-project-threat-dragon/

thanks again for the issues you have found

**Comment by taoyiyang1** [comment]
hello@jgadsden 
I have sent you an email.  I don't know if you have received it.  The email suffix is QQ.com
