### ISSUE TITLE
Support github enterprise in version 2.0 codebase

### ISSUE THREAD

**Issue by danielpops** [OWASP/threat-dragon#329]
Describe what problem your feature request solves
The github oauth configuration assumes that you're using github.com and doesn't work with github enterprise.

Describe the solution you'd like
A configuration in .env (or equivalent for prod) that lets you specify a github enterprise url

**Additional context**
#250 was originally created and implemented in #252 but testing was inconclusive and the changes never merged. @jgadsden suggested to implement the feature in the version 2.0 codebase instead to leverage easier development and debuggability.

**Comment by danielpops** [comment]
Hi @lreading, just wanted to check back in on this. Any thoughts on if / when this might be revisited?

I'd love to use Threatdragon to maintain our company's threat models and store them in our internal github enterprise repo(s)!

**Comment by lreading** [comment]
I've been less active recently, my apologies!  Hoping to get more time onto this specific issue in the next month or so.

**Comment by jgadsden** [comment]
@danielpops and @lreading , this may not make in into version 2.0, so labelling it for version 2.x

**Comment by jgadsden** [comment]
Unlikely to get this into the imminent version 2.0 release, so pushing it back to version 2.x
