### ISSUE TITLE
Version 2.0: add scrolling

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#331]
**Describe what problem your feature request solves**
At the moment we can not scroll across the canvas. We can zoom out and place elements in parts of the canvas that are not accessible when we zoom back in

**Describe the solution you'd like**
It would be good to be able to scroll the canvas, ether by dragging an element or bumping the edge of the visible area of the canvas. Ideally the cursor / mouse pointer should stay within the visible area of the canvas

**Additional context**
This is probably already provided by antv/x6, and just needs enabling

**Comment by lreading** [comment]
I believe this is an easy config change, and would probably go here: https://github.com/OWASP/threat-dragon/blob/a400563b63ee5dc07da50b34d4913247a1e196cd/td.vue/src/service/x6/graph/graph.js#L9

Happy to knock this out quickly when I have a chance or anyone else can take it! :)

**Comment by jgadsden** [comment]
I think you have all the knowledge @lreading , so I will be a bit cheeky and assign it to you :)

**Comment by lreading** [comment]
Done! It should be deployed by the time you see this.  Vertical and horizontal scrolling is enabled by default now.  Additionally, mouse wheel works for vertical scrolling, and holding shift and using mouse wheel will scroll horizontally.

**Comment by jgadsden** [comment]
Agreed - works for me as well. Good to see this in place
