### ISSUE TITLE
v2 - desktop version

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#334]
**Describe what problem your feature request solves**
We should have a desktop version in place before version 2.0 release

**Describe the solution you'd like**
It would be good to use an electron wrapper for the web application, and this will provide the desktop version of the threat dragon application

**Additional context**
Note that the existing version 1.x threat dragon desktop uses common code with the web application, but does not wrap the web application itself.  This has caused an increase in development and test effort, so it would be good to change the way this is done. Refer to [this example](https://jojozhuang.github.io/tutorial/converting-web-app-to-desktop-app-with-electron/) but it can be done in various ways

**Comment by ShubhamPalriwala** [comment]
Hey,  I'd like to take this up! Would primarily follow the article mentioned as I'm new to electron but would be open to incorporating any changes suggested

**Comment by jgadsden** [comment]
Yes, sure, thanks for your help @ShubhamPalriwala - I can assign it to both of us as I am sure we can help each other

**Comment by ShubhamPalriwala** [comment]
Hey @jgadsden, so should we remove the entire existing desktop codebase and just have a simple wrapper around our web-app in our main.js inside our td.desktop?

**Comment by jgadsden** [comment]
Hello @ShubhamPalriwala , yes, that makes sense to me. What might be good is to move the td.desktop to another directory so that we can easily refer to it, and when all is working remove it then. Alls is good though, so I will go with what  you decide

**Comment by ShubhamPalriwala** [comment]
@jgadsden, I'm loading the following URL for our desktop application: `http://threatdragon.org/`
This is fine right or will we be using another URL?

**Comment by jgadsden** [comment]
We do not have direct control of http://threatdragon.org/ , so threatdragon.com is probably the better domain to use ... this is used to showcase the latest Threat Dragon web app and documentation

I will have a look at your code on the branch this evening, good to see progress so soon @ShubhamPalriwala !

**Comment by lreading** [comment]
From a discussion in Slack (just for visibility for others who may see this): The goal is to wrap `td.vue` in electron as opposed to loading a specific URL.  The vue site should be able to operate independently of any server.  Threatdragon.com is running on a very small Heroku instance, and might not handle the load well.  Also, that is used as a staging area and is published each time there is a push to the main branch, so it might not be considered stable. 

Thanks again, @ShubhamPalriwala

**Comment by jgadsden** [comment]
Hello @ShubhamPalriwala , the next thing to do is to make an electron wrapper for the td.vue web application. The td.desktop directory can then be retired, along with `td.desktop/main.js`
I will probably look at these next, for guidance:
https://stricker.digital/posts/electron-with-vue-and-webpack/
and
https://blog.logrocket.com/building-app-electron-vue/
and Vue seems to work well with electron

**Comment by jgadsden** [comment]
Agreed @lreading , I should have made it clear that there should be no need to use either threatdragon.org or threatdragon.com
The intention is to create a new file (probably in the td.vue directory) that is the electron window builder. My guess is that we will need other source  files to provide the functionality for the desktop application, similar to that provided by td.server for the web application
I need to look into this more ... concentrating on adding threat engine at the moment ... hope all this makes sense for you @ShubhamPalriwala

**Comment by ShubhamPalriwala** [comment]
So I researched for a while andI found a great vue package that solves the exact problem that we are tackling.
Will configure it acc to us and open a PR for the same soon!

**Comment by jgadsden** [comment]
@ShubhamPalriwala pull erquest #362 satisfies this issue, so do you want to have the honour of closing it?

**Comment by ShubhamPalriwala** [comment]
Haha! Thank you Jon.
