### ISSUE TITLE
v2 - Increase Graph Area

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#336]
**Describe what problem your feature request solves**
I feel like the graphing area needs a bit more real-estate. 
As it stands, the header/navbar takes up a lot more room than it needs to, and there is the warning banner that it is an unstable build.

**Describe the solution you'd like**
I'd like to retain a warning to potential users who stumble on the site (or are previewing it) so that they understand there may be adverse consequences if they save a threat model.  At the time of writing save is not implemented, but will be soon.

Some thoughts:
- Shrink the nav bar a bit to make more room
- Make the warning a dismissable toast message
- Move the title of the graph somewhere else, make it a bit smaller
- Raise the entire graph container (including stencil and properties pane) to just under the navbar

**Additional context**
I've said it before, I'll say it again: I am not a UI/UX expert.  Please provide any and all feedback, ideas, criticisms, etc. :smile: 

This screenshot shows the under-utilized space:
![Screenshot from 2021-12-30 23-39-05](https://user-images.githubusercontent.com/5851985/147803818-3fbb49e2-4c3a-4bad-a1f1-8231a8b2af7d.png)

**Comment by jgadsden** [comment]
Hello @lreading 

Agreed, now that you point this out it would be good to give the drawing canvas more room

The warning banner does not worry me - as it will be removed - but if it was a toast message then that would be cool

The title of the graph probably should be remain prominent wherever it is ... when I have a multi diagram threat model (not that often, but still common) then the dev team (which includes me) can get confused as to which diagram we are working on. So I like all the suggestions, but we need to make sure the title is prominent?

**Comment by lreading** [comment]
A quick mockup:
![Screenshot from 2021-12-31 00-18-27](https://user-images.githubusercontent.com/5851985/147804861-d180257b-64a8-4169-b97e-d0df6a83401d.png)

Looking at the result, I think we'd want to re-organize the main tool buttons a bit, with save/close to the far right.  I think the title is still prominent enough?

Another thing that I may mock up to see how it looks is putting the stencil underneath the graph, and leaving more horizontal width for the graph/properties pane.

**Comment by lreading** [comment]
I think this can be improved upon a bit more (especially the properties form), but if _feels_ a lot more spacious to me:
- Moved the buttons around a bit
- Moved the properties and threats under the graph (no more accordians, threats / properties are always visible)
- Removed the ability to multi-select with the box-drag feature that I referenced in #333 - It was interfering with the scroller quite a bit.  If we move forward with these changes, panning will work by simply grabbing an empty area as you described
- Added page breaks and page visibility to the graph (again, strange issue with panning/scrolling related to pages.  Also, we know some users print threat models)


![Screenshot from 2021-12-31 01-55-41](https://user-images.githubusercontent.com/5851985/147808657-42a3c50c-4d96-4225-84ad-4d04ecb3b3a0.png)

![Screenshot from 2021-12-31 01-55-59](https://user-images.githubusercontent.com/5851985/147808664-187b5c2c-2945-4f61-9f63-0bdb5c7d0b0e.png)


Looking forward to any and all feedback!  Changes are in the `v2/336-graph-ui-adjustments` branch

**Comment by jgadsden** [comment]
Well, having the properties and threats down below took some getting used to, but ~I think it is an improvement and we should go with it. There were reports that the lower section of the display was blank or not used, and this will help with that - also it creates a better 'dashboard' feel

It is good to have the title and  the buttons on the same level, and we now have canvas area to the right, which  helps to declutter the view.

So, my vote is to go with these changes

**Comment by lreading** [comment]
Again, I think the threats/properties panels could be improved quite a bit with regard to layout/design, but I think this is a good starting point. :) I agree it's going to take some of Threat Dragon's power users a bit of getting used to, but my hope is that the majority feel that it adds value and is worth it.  I'll add the toast alert and tidy up a bit before merging.
