### ISSUE TITLE
Version 2.0 - Report Feature

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#339]
**Describe what problem your feature request solves**
Version 2.0 should have a reporting feature with similar outputs to version 1.x

**Describe the solution you'd like**
- The report button generates a report
- Checkbox options for:
  - Show out of scope elements
  - Show mitigated threats
  - Include threat model diagrams
- Buttons at top/bottom (maybe sticky in the top-right for usability?)
  - Save PDF
  - Print
  - Return

**Additional context**
Some Threat Dragon users rely heavily on the reports, and some are still printing them.  The reporting feature is a must-have for the initial 2.0 release.

The Save PDF button will be implemented in #342

**Comment by lreading** [comment]
I think an executive summary would be nice on the report as well.  Maybe just some high-level numbers, such as identified threats, mitigated threats, unmitigated threats, etc.  Should I open a new issue for this or should I just take a swing at it while implementing the v2 reporting feature?

**Comment by jgadsden** [comment]
If you are implementing the reporting feature, then the executive summary can be part of the implementation. Version 2.0 will be perceived as different, so we can add an executive summary without surprising people.
Having said that if the executive summary proves a problem then pull it out as a feature on its own.

**Comment by lreading** [comment]
This has turned out to be a slightly larger chunk of work than I originally had hoped.  Here's my current plan:
- The report page will show an HTML-based report (for screen sharing, projectors, etc) and will look mostly the same as v1
- The report page will have a button to a printer-friendly version of the report.  This is an entirely separate view that is more optimized for print (less space, tabular data, cover page, date, etc)
- I've added a couple hacks to force a diagram into the v2 format so I can know where to read data from consistently.  While we're still hoping to not change the API, there will be new fields that are needed for generating the report.  I don't want to leave it in a broken state and come back to it, so it will be in a weird place for a bit (should still functionally work, just more of a concern when I get to #340 - hopefully soon!)

There's still quite a bit of work to be done, but I'm attaching a PDF version of the printer-friendly page for early feedback.  I'd much rather course correct now than later, any thoughts or suggestions are appreciated as always!!!

[report_for_feedback.pdf](https://github.com/OWASP/threat-dragon/files/7798745/report_for_feedback.pdf)

**Comment by jgadsden** [comment]
Looks good to me, just a few suggestions:
* I love Cupcake, and the mascot is one of the things that drew me to this project, but up to now we have left her off the report. I guess it was because these reports get sent to all sorts of external standards bodies, and we did not want to explain who she was each time ... Cupcake in or out, both fine with me
* The title sheet is a big improvement
* I like the executive summary, with both the high level description and the stats
* The elements that have no threats listed against them seem to clutter the report, possibly not list them?
* Showing the diagram often proved a problem - scaling it to fit the page width, landscape / portrait, going over age breaks, etc. Not sure how to solve this for all cases

**Comment by lreading** [comment]
> I love Cupcake, and the mascot is one of the things that drew me to this project, but up to now we have left her off the report. I guess it was because these reports get sent to all sorts of external standards bodies, and we did not want to explain who she was each time ... Cupcake in or out, both fine with me
Would we want to make a setting for hiding Cupcake?  I think it's a good branding opportunity and makes it very clear what software was used to generate the threat model/report, however I understand that some people may not appreciate the branding on their reports.  Happy to remove it all together if that is what's best though.

> The elements that have no threats listed against them seem to clutter the report, possibly not list them?
Agreed.  We probably want to reduce the amount of paper as much as possible, and they aren't really adding value.  You can see the entities exist and infer their type based on the graph.  I'll remove these.

> Showing the diagram often proved a problem - scaling it to fit the page width, landscape / portrait, going over age breaks, etc. Not sure how to solve this for all cases
This is still true, even with the x6 library.  I spent a lot of time to try to get it working in *most* cases.  Current limitations:
- It is always in portrait mode, rotating the graph to convert a single "page" to landscape proved problematic.
- Exporting as an SVG/JPEG/PNG is not working currently.  This is a problem with either the x6 library or our implementation of it.  There's a console error in Firefox when converting to an image.  I found a partial work-around, but we lose some labels which makes it unusable.  Ideally, if we can work with an image we might be able to just scale it in a div that stretches to 100%x100%
- I've only tested on Ubuntu 20.04/Firefox, nothing else.  I'm unsure if the constraints I've put on max width and height will work on other systems, TODO
- Really large diagrams will be small and difficult to read

The way it _currently_ works:
- Height defaults to 700px
- Width is the min value between the parent div width and another magic number (todo)
- The graph is resized with a little margin (width - 50) x (height - 50)
- The content in the graph is scaled to the new size
- The graph is frozen to prevent modification

I can say that the scroll bars are no longer a problem with this configuration, but I'm not super confident that it will work 100% of the time with all threat models. I think it's an overall improvement from where it was though, so I'll be interested to see it in use against some real-world graphs later.
