### ISSUE TITLE
v2 - Report PDF in Desktop

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#342]
**Describe what problem your feature request solves**
Implement the create PDF functionality in v2

**Describe the solution you'd like**
When viewing the report for a threat model in the _desktop_ application, a "PDF" button show show that exports the report as a PDF.

**Additional context**
In v1, this feature is not available in the web version.  I did some research and most of the libraries that are capable of converting HTML to PDF have quite a bit of overhead, whereas we get the PDF generation for (almost) free through electron.  On the web version, a user could choose to print and then save as a PDF via the system print dialogue. 

This will have to be done after the electron wrapper is created in #334

**Comment by lreading** [comment]
On linux (ubuntu 20.04), the regular print dialogue has an "output to file" option that saves the PDF of the page.  The CSS `@media` queries appear to work the same as they do on the desktop version.

I think the PDF button may be redundant.  I'm going to test this on macOS and Windows as well just to double check.  If it turns out to the work the same, I'd vote to remove this feature entirely.  It adds a little extra conditional logic and implementation details that we don't need, and we get the same "feature" by default. :smile:

@jgadsden @ShubhamPalriwala - Thoughts?

**Comment by jgadsden** [comment]
Yes, makes sense - we get a lot from Chromium/electron so it may be that it works similarly for the desktop app
If so then pruning sounds good to me 👍🏾

**Comment by lreading** [comment]
I checked on ubuntu, windows and macos, all have similar features.  Additionally, the report looks about the same across operating systems. I'll remove the pdf button. :smile:
