### ISSUE TITLE
support HTTPS

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#345]
**Describe what problem your feature request solves**
At present Threat Dragon uses HTTP, we can enable HTTPS via PROTOCOL env var but it does not seem to work correctly

**Describe the solution you'd like**
When running Threat Dragon web application, we have URL `http://localhost:8080/#/dashboard` but URL `https://localhost:8080/#/dashboard` gives "This site can’t provide a secure connection" response when the PROTOCOL env var is set to `https`.

Can we support both HTTP and HTTPS at the same time?

**Additional context**
Web application only, this will not be a problem for the electron desktop app

**Comment by lreading** [comment]
The `PROTOCOL` env var is only applied on the server, and doesn't have any configurable certificates.  It's currently set up more for the docker image running behind a reverse proxy with SSL termination.

This can/should be improved for sure, as not everyone installing the web version will opt for a docker installation. :smile:

With that said, when running locally, you're using the vue cli to run the site, separate from the server code.  If we wanted the same effect locally, we'd want to look at something like this: https://forum.vuejs.org/t/vue-cli-serve-with-https/39359

**Comment by jgadsden** [comment]
Ah, I may have mangled docs/development/env.md - apologies

**Comment by lreading** [comment]
It probably isn't super clear in the docs. :) That was more of a deployment detail when I was setting up the Heroku deployment... I 100% agree with the issue, to be clear! I have it set up to suit my specific deployment needs, as opposed to a more generic/robust configuration (which is what we'll likely want).

**Comment by jgadsden** [comment]
Thanks for looking at this - we can close as a non-issue
