### ISSUE TITLE
add Zone of Trust property

### ISSUE THREAD

**Issue by kostasadriano** [OWASP/threat-dragon#353]
**Describe what problem your feature request solves**
In Rapid Threat Model Prototyping, you have to define a zone of trust level for each element/node. This property can then be used by the threat engine to suggest STRIDE threats, or be used manually by the user. (eg DoS from zone 0 to any other zone, Information Disclosure form higher trust zones to lower trust zones, etc).

**Describe the solution you'd like**
Add a "zone of trust" property in each element we place on the diagram. It should allow for numerical values between 0 and 9.

**Additional context**
See also:
https://resources.infosecinstitute.com/topic/rapid-threat-model-prototyping-introduction-and-overview/
https://github.com/geoffrey-hill-tutamantic/rapid-threat-model-prototyping-docs

**Comment by jgadsden** [comment]
Labelling this as version 2.0 because version 1.6 is the last version for functional development on versions 1.x

**Comment by jgadsden** [comment]
Closing this because we use trust boundaries rather than a numerical zone of trust, and do not want to complicate the lightweight Threat Dragon tool (otherwise we start trying to compete with Microsoft TMT)
