### ISSUE TITLE
Formatting Guidelines for Contributors

### ISSUE THREAD

**Issue by ShubhamPalriwala** [OWASP/threat-dragon#368]
**Describe what problem your feature request solves**
Every developer has their own set of configs for tab sizes, indentations, linters, etc. This makes reviewing a PR difficult as well as makes the code formatting non-uniform across the project.

**Describe the solution you'd like**
Threat Dragon should have generalised standards that our project throughout its file follows. This reduces the time to address formatting changes and improves code readability also! 

Open to discussion for the above-discussed standards.
Once we agree on something, one can open a PR that implements the configs and sets up the entire project with those linting changes and uniformity.

**Comment by lreading** [comment]
Just leaving some notes:

Off the top of my head (I will try to remember to check later today) - We have eslint configured for both td.vue and td.server, with different linting rules.  Ideally, it'd be great to have a single source of truth.  Both linters are configured to run with the `--fix` argument which should be able to handle simple formatting issues.

Another tool at our disposal is using a [.gitattributes](https://stackoverflow.com/a/40821931/3033053) file to specify line endings, and I think can manage tabs v spaces as well.

**Comment by jgadsden** [comment]
Adopting [JavaScript Standard Style](https://github.com/standard/standard)
