### ISSUE TITLE
Apply OWASP ZAProxy to webapp

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#37]
**Apply OWASP ZAProxy on merge**
It would be good to run OWASP ZAProxy on Threat Dragon

**Solution**
ZAP can be run from github:
https://www.zaproxy.org/blog/2020-04-09-automate-security-testing-with-zap-and-github-actions/

**Comment by prakhar-ai** [comment]
Hi, can I work on this issue?

**Comment by jgadsden** [comment]
Hello @prakhar-ai
Yes, that  would be great if you could work on this issue. I have gone ahead and assigned it to you.

Many thanks!

**Comment by jgadsden** [comment]
The idea (at the time) was that we should at first apply ZAP manually to Threat Dragon. We have already received one notification of a vulnerability and it would be good to know if there are more.

If at  some point we can apply ZAP within the pull-request pipeline then that would be superb

**Comment by prakhar-ai** [comment]
Thanks @jgadsden , should I make the ZAP scan run every time on a push/pull request ?

**Comment by jgadsden** [comment]
Yes, that would be good to have - thanks again @prakhar-ai

**Comment by script-beast** [comment]
Can I work on this issue ?

**Comment by jgadsden** [comment]
Hello @script-beast , thanks for the offer -  @prakhar-ai is already working on this so if you would like to add to the PR could you coordinate him ?
Many thanks, Jon
