### ISSUE TITLE
v2 - determine if PROXY_PRESENT is still needed

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#370]
**Describe what problem your feature request solves**
We have an env var in version 1.6.0 for proxies: PROXY_PRESENT

**Describe the solution you'd like**
Determine if PROXY_PRESENT is needed for version 2.0 onwards

**Additional context**

**Comment by lreading** [comment]
I misunderstood what this config was used for.  In previous iterations, that was set for the passport/cookie auth configuration.  v2 no longer uses cookie auth, but instead relies on bearer token auth.  I don't know if we would need this setting, or how we would configure it.  I don't have any environments suitable for testing.

**Comment by jgadsden** [comment]
Thanks for looking at this - we can close this as it is  not needed
