### ISSUE TITLE
v2 - desktop includes github login

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#373]
**Description**
When using the desktop application, if the main page button is pressed 'Login with GitHub' then the main window becomes the github login screen and there does not seem to be a way to escape

**Expected behaviour**
It would be good to be able to get back to the main screen without having to close / reopen the application

**Environment**
 - Version: 2.0
 - Platform: Desktop App
 - OS: all , but tested on MacOS
 - Browser: NA

**To Reproduce**
1. from command line `npm run start:desktop`
2. click on 'Login with github' button
3. there seems to be no escape from the github login window

Note that if using the installed desktop app (rather than one run via vue cli) then there is different bahaviour

**Any additional context, screenshots, etc**
attached screenshot shows the github login screen 
<img width="576" alt="threat-dragon-github-login" src="https://user-images.githubusercontent.com/29352392/153431815-23993e9c-dffc-491a-8fb7-ba3d876b598a.png">

**Comment by lreading** [comment]
I think the "bug" is that the github login isn't intended to be present on the desktop app.  The logic hasn't been implemented yet because the wrapper was just added.  The github login flow requires the server, which isn't wrapped in the electron application.  Should be an easy fix and is already planned. :smile:

**Comment by storkinsj** [comment]
Has anyone tried PAT or read through how to avoid by using ssh?

Perhaps do this for your user on your computer and see what happens? 
https://docs.github.com/en/get-started/getting-started-with-git/why-is-git-always-asking-for-my-password
