### ISSUE TITLE
New Threat Model Gets Stuck at v2 Welcome

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#378]
**Describe the bug**
When creating a new threat model using GitHub auth, the guard that checks for v1 vs v2 models triggers, and you cannot navigate past it.  This happens when clicking the "create a new threat model" link from the _repository_ selection page.

**To Reproduce**
- Log in using Github Auth
- Click "open an existing threat model"
- Select a repository
- Select a branch
- Click the "Create a New Threat Model" link at the top of the page

**Any additional context, screenshots, etc**
![Screenshot from 2022-02-12 23-56-47](https://user-images.githubusercontent.com/5851985/153739320-36780c97-e5a0-4f32-8462-6f53b3bf89f2.png)

This was set up prior to much of the other routing and configuration.  Creating a new threat model using github auth isn't fully implemented yet either, as there is no option for repo/branch selection.  This issue _could_ cover all of the above, or just be picked up after the implementation of new threat models is fleshed out.

**Comment by jgadsden** [comment]
Confirmed that this still happens as described

**Comment by lreading** [comment]
Assigning to myself - I've wanted to re-work the git flow for a bit now.  I think it could be done a bit more cleanly anyways.  As it currently works, there's multiple pages/routes to get to a threat model, when it could be a single view with multiple components to accomplish the same goal.
