### ISSUE TITLE
Open/Save/Rename for Electron

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#383]
**Describe what problem your feature request solves**
The electron build requires different logic for saving directly the file system.  Users should only be prompted with the save file dialogue when they are creating a new threat model (not fully implemented yet)

**Describe the solution you'd like**
Create electron specific logic that saves the threat model whenever the user clicks a "Save" button.  

**Additional context**
Currently, this logic is triggered from the threatmodel store.  Additionally, there's `service/save.js` which is probably a good place to split the browser vs electron logic

**Comment by jgadsden** [comment]
This is a high priority for the electron desktop app - I will take this on next of that is OK?

**Comment by lreading** [comment]
I believe I had it working just using the browser save (ergo download) feature.  In electron, it would probably be best if we used the system save dialogue.  I think the main difference is that using the browser download function, it will prompt the user for the save location each time they save, and by default append a number to the end if the file already exists.  In the electron app, I think it would make more sense to overwrite an opened threat model by default. :smile:

**Comment by jgadsden** [comment]
Cool, thanks @lreading , I will go ahead  and use the filesystem dialog open/save/silent-save
