### ISSUE TITLE
desktop version won't let me edit processes, stores etc.

### ISSUE THREAD

**Issue by vtgav** [OWASP/threat-dragon#387]
**Describe the bug**
all appeared to be working OK, I created a new project, new diagram, started to build the model but at some point it became partially 'read only' - I can drag processes, stores and actors around but cannot change them ( eg: change the name or description etc. ). However I can change data flows and trust boundaries.
I cannot add items of any sort.

**Expected behaviour**
I should be able to change the configuration of any item on the drawing and add new ones

**Environment**
 - Version: 1.6.1
 - Platform: Desktop
 - OS: Windows
 - Browser: Chrome

**To Reproduce**
I don't know what caused the behavior to change, but I had created a fairly complex diagram before it did

**Any additional context, screenshots, etc**
If I create a new project and a new diagram I can't add anything to it

I passed my original model to a colleague and its fine for them, they can edit, add now processes etc.

I also deinstalled and reinstalled, same problem

**Comment by jgadsden** [comment]
Hello @vtgav - just to make sure, you have downloaded the Windows installer from the releases area:
https://github.com/OWASP/threat-dragon/releases
and you are using the desktop version not the web app version?
