### ISSUE TITLE
v2 - can not delete process diagram element

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#391]
**Describe the bug**
When attempting to delete a process diagram element from a diagram, the 'red cross' becomes unavailable and no deletion can be done

**Expected behaviour**
Deletion of processes; same as Actors, Data Flows and Trust Boundaries

**Environment**
 - Version: unreleased version 2.0
 - Platform: both Web App and Desktop App
 - OS: MacOS - possibly Windows + Linux as well
 - Browser: Chrome, Safari, probably others

**To Reproduce**

1. In  a Chrome browser navigate to https://www.threatdragon.com/#/
2. Login with local session
3. Explore a sample threat model: Version 2 Demo Model
4. Edit diagram: Main Request Data Flow
5. Attempt to delete process: Web Application or 

**Any additional context, screenshots, etc**
Tested with desktop app, get the same issue

**Comment by jgadsden** [comment]
Taking  this one on because I think the solution is fairly straight forward

**Comment by jgadsden** [comment]
I could not see how to correct this, so releasing it. The process diagram element can be deleted once it is selected, using the delete key or by using the trash can icon.
We have workarounds so demoting the priority

**Comment by lreading** [comment]
I'll take a look at this one.  I know it's not a show-stopper, but that's a pretty bad UX type of thing. :) I'm suspecting it has to do with the custom shapes.

**Comment by jgadsden** [comment]
Thanks @lreading - agreed we have the delete key and also rubber banding to delete the process shape ... but it is disconcerting that the red cross keeps disappearing every time you move to it (but only on the process circle-shape)

**Comment by lreading** [comment]
A quick observation: The process is the only shape where the SVG lines do not extend to the corners of the boundary body.  It seems as though the "x" icon disappears as soon as you are no longer inside the initial shape. I think a somewhat simple workaround would be to extend the shape to be a square with a circle inside of it.  We can set the opacity to 0 for the square, but X6 should still identify the cursor as being within the bounds of the shape. 

I'm going to give this a shot, but need to pay special attention to how it renders for print/pdf when testing it. :)

**Comment by jgadsden** [comment]
Wow, yes, I bow to you. Sounds like an elegant solution - I could not find a solution myself and this sounds good to me.
