### ISSUE TITLE
v2 - go straight to welcome screen for desktop app

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#396]
**Describe what problem your feature request solves**
At the moment the desktop goes first to the login page, but with only one option 

**Describe the solution you'd like**
The desktop app should miss out the login page (/#) and go straight to the welcome page (/#/dashboard)

**Additional context**
This would make the desktop application behave the same as version 1.x, and also it is an unnecessary step to go to the login page - there is no login necessary
Having said that, it would be great if the desktop app _could_ login to github and other remote file systems

**Comment by lreading** [comment]
Would it be worthwhile to make the decision of including authentication flows in desktop or not before doing this?

I don't have a definitive plan, but I do wonder if we may need to bundle the server code into the desktop app to accomplish this, or if we could use another auth flow to authenticate?  I think it'd be best to decide _how_ we want it to function, then work on the implementation. :) 

Open to anything here!

**Comment by jgadsden** [comment]
Yes, good point. If we have authentication in the desktop (whatever form that takes) then we still need the #/ page and not go straight to #/dashboard

I think this issue should be closed with "Won't Do" (re-open it @lreading if you disagree)
