### ISSUE TITLE
[CSS Rendering] Bug when opening the "edit diagram" interface in a small window

### ISSUE THREAD

**Issue by jeronomy** [OWASP/threat-dragon#399]
**Describe the bug**
Opening "Edit Diagram" feature with a small window, then resizing the window (enlarging) will cause the interface to not appear "properly" : 5 elements of the diagrams (process, store, actor etc) seems to have 'absolute' size fixed (when first shown in small window) and won't re-ajust their size properly (to fit new window size dynamically).

**Expected behaviour**
Edit diagram menu should adjust to size of window.

**Environment**
 - Version: 1.6.1
 - Platform: Windows Desktop App
 - OS: W10

**Any additional context, screenshots, etc**
Related to issue 386, I belive : https://github.com/OWASP/threat-dragon/issues/386#issue-1154116651
I understand that V2 will be more "feature rich" and utilize component to do the rendering in a different way, but I wanted to tell about this, in case it could be fixed in v1.

**Comment by jgadsden** [comment]
Thanks for the bug report @jeronomy  - how severe is this problem? Is it a blocker that needs a fix and a new patch release?

**Comment by jeronomy** [comment]
This is not a 'critical bug' imo, but I would like to have a 'more responsive' drawing interface if possible (without too much efforts).

I am doing some tests to see the possibility of use of this tool, for client's org.
Clean process for building & documenting threat models would be a huge benefits (helping me help them, to be more secure).
But those kind of bug (responsivness, non-adjusting sizing of widget, etc) could potentially contribute to put off some users among my client's org.

So I understand the V2 will be better, but IMO : would be nice to have a 'cleaner behavior' on sizing window (for the v1), if it does not represent too large amount of time & commit (and also does not get in the way of the V2 first stable release).
Question for me is kindof: do the demo with v1 (there is always pro & con for any software/version/tool), or wait for stable v2.

Btw : is there any ETA / idea about this v2 release date, or for the possibility to spin up easily a docker container for v2 ?

**Comment by jgadsden** [comment]
Hello @jeronomy - thanks for the really good information on how you are using Threat Dragon. As a project we rarely get such detail ... I use it in my company so it tends to follow the ForgeRock use cases, I guess a bit of an echo chamber :)

The drawing package for version 1.x proved a real headache for us, going up a version on JointJS introduced breaking changes that would need a lot of effort, and was the driver for moving to a revamped version 2.0. So it would be a lot of effort to clean up the drawing window / interface ... we would have to move JointJS from version 2.2.1 to version 3.5.4 with all that means

Stable version 2.0 is some way away - my guess is June this year: https://github.com/OWASP/threat-dragon/projects/5

Not sure if that answered any of your questions properly ...

**Comment by jeronomy** [comment]
Thanks for your message: I got my answers loud &  clear :)
So this is a minor issue, and I would like to avoid more headache on this specific matter!

I am testing the v2 and it seems like a really good shift ! 

I know this is not the place or the time to do suggestion properly, but... here it comes :)

- It seems harder to select items ! I did took 5min to understand that arrow must be clicked on their 'head', and still can't manage to select other item/entitie withtout creating junk arrows all around : maybe a mouse selector options to create or select item would ease the creation/ edition of diagram ?

- Rendering while playing with the window size is much more smoother than on v1 ! But it could be (imo) even more smooth with a dynamic sizing of the 'edition diagram' panel, to really enjoy your new super-ultra-mega-wide shiny monitors ? 

- The save feature from 'edition diagram' interface is kind of confusing, imo (desktop version) : there is a green popup (bottom left hand corner) which notice us that 'Threat model successfully saved!' , but at same time, Windows popup to register .json file (so, did the original json file were already overwritten, or not before confirming new name of json file via explorer.exe ?)

I know I'm pushing with next 2 on top of it (and I know it's WIP) but :
- I can't seems to find any place for 'info' on the main menu (place to find version number and stuff)
- A dark mode would be like, the cake on the cherry :)

Thank you for the time & effort invested in this nice tool : I belive it will quickly become the 'de facto standard' for this task, in few next months, if not already !

I will keep testing both version for preaching threat modeling, as we should :)

Have a nice one !

**Comment by jgadsden** [comment]
Hello @jeronomy , I agree with your points - did you want to raise an issue for:
1. Dark mode
2. Dynamic resizing of the side panel

Select items is in a pull request at the moment: "disable magnet to allow grab of entire element" #394
I will go ahead and merge this pull-request and so you can see if it has improved (@lreading I hope you do not mind megoing ahead)

**Comment by lreading** [comment]
> I know this is not the place or the time to do suggestion properly, but... here it comes :)

Feedback is very much welcome, however it comes in! Thanks for poking at it!

**Comment by jgadsden** [comment]
I am looking at  the versioning - Heroku does not seem to be updated with the latest version, so this would be a good to have. Will raise a feature request

**Comment by jeronomy** [comment]
Hello ! 
Thank you for you answers !
I had close the ticket in my mind so didn't expected some returns, nice to see commitment on product improvment like this :)

I will open issues for the 4 mentioned topics ! This is the least I can do :)

If I were able to read through the matrix, I would be tempted to wonder help dev some feature (but yeah, the matrice has me, for now...)
