### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by jeronomy** [OWASP/threat-dragon#406]
**Describe what problem your feature request solves**
The software looks good, in v1.6 & in v2 : it could look even better with a dark mode !

IMHO : The better the interface looks, the more people we will be able to convert to use this tool, by preaching the holy words of OWASP spirit. Amen.

**Describe the solution you'd like**
Invert color interface ? 
The 'mitigation' for this is easy on the web interface (DarkReader is good enough imo), but for the desktop version, IDK the simplest way to do it really.

This issue is linked to this thread : https://github.com/OWASP/threat-dragon/issues/399#issuecomment-1091775573

Have a good day :)

**Comment by jeronomy** [comment]
Sorry, duplicate of issue #404 (I did 'Not Found' it in time)

https://github.com/OWASP/threat-dragon/issues/404

**Comment by njmulsqb** [comment]
Do we have stylesheets for dark mode?
