### ISSUE TITLE
provide dynamic resizing of the drawing panel

### ISSUE THREAD

**Issue by jeronomy** [OWASP/threat-dragon#407]
**Describe the bug**
Dynamic resizing during window resizing to get a "proper responsive user experience" would be very nice !
In versions v1.6.0 and also in the next upcoming v2.0, the drawing panel is not able to enlarge itself, when more space is availble.

**Expected behaviour**
Would be nice to have the larger drawing panel possible, especially in futur v2, to increase usability & user experience 

**Environment**
Tested w/ Windows 10 desktop version.

This 'issue' is linked to this : https://github.com/OWASP/threat-dragon/issues/399#issuecomment-1091775573

**Comment by lreading** [comment]
I made a pass at this during initial implementation and decided to revisit it later, as I couldn't get it to work reliably.  There's a responsive attribute for the X6 diagram, but the machine-translated documentation isn't super clear on how it works.  I do know that you need to be using flex.  The issue could even be with how Bootstrap is using flexbox, or it could have simply been a lack of understanding on my part. :)

**Comment by jeronomy** [comment]
Nice, thank you for getting time to poke around this issue again ! 

I do understand pretty well that I do understand very little about technical stuff outside "dependency version should match", but I will eventually take a closer look at the ThreadDragon's code for this feature this weekend (and also on the flexbox side of things, perhaps ?)
By all means: don't raise expectation (for real results from me) - I only wish I could bring some real help tho (improving the overall user experience), instead of helping bury the team under hundreds of issues.

I do appreciate time & efforts put on the project ! Not only those code modifications which made it through mainline / stable!

Have a great one :)

**Comment by jgadsden** [comment]
thanks for looking at this @jeronomy and @lreading - do you mind if I assign it to you both? 
You can always unassign it if you disagree :)

**Comment by jgadsden** [comment]
Issue #422 shows we have problems with dynamic resizing in version 1.x (probably a JointJS problem), this was noted by @sparticvs

We can check that dynamic resizing in version 2.x does not do the same thing

**Comment by jgadsden** [comment]
Version 2.x drawing library corrects this issue - closing it as Fixed
