### ISSUE TITLE
v2.x - Info needed: 'Version number'

### ISSUE THREAD

**Issue by jeronomy** [OWASP/threat-dragon#408]
**Describe what problem your feature request solves**
The new upcoming v2 version does not seems to have a place for the version number info, in the main menu of the app.

While this is not a deal breaker as final user will not spontaneously search for version number on a perfect app without any bug (yes, it will be), while 'waiting' perfection, it would be practical  to be able to find this info **somewhere** on the main welcome interface.

(FI : the welcome popup in red, appearing in the bottom left hand corner have the info 'version 2.0', but it is shown for a short period, and user may want to find later, after some usage /drawing time in the app).

**Additional context**
Windows 10 Desktop version 2.0

This ticket is related to : https://github.com/OWASP/threat-dragon/issues/399#issuecomment-1091775573

**Comment by jeronomy** [comment]
Hello ! 
Nice adding of the "About Threat Dragon" option in the "Help" main menu !

We now can see that Threat Dragon use "Electron 17.4.0" (but not yet the Threat Dragon version in itself)

I know this message is not usefull in any way (as we know that I know that you know what you are doing) :
I just wanted to say "Thank you for this feature!" and also stop by to say hello, have a great week-end :)

**Comment by jgadsden** [comment]
Hello @jeronomy - yes, I agree that the electron version is not super useful :)

This is part of the weirdness that electron does - if you run it in development mode then the 'about' role in the menu system shows electron ... but if you build it as an installer it shows the correct information in the about box
<img width="777" alt="Screenshot 2022-04-16 at 07 00 25" src="https://user-images.githubusercontent.com/29352392/163663777-9f20cb22-1071-4266-8bdf-daaf671d08a8.png">

**Comment by jgadsden** [comment]
Having said that  ... not sure why the version string is '2.0.0 (2.0.0)' which looks weird and wrong. It must be picking this up from `package.json`

If you have time to experiment?
Cheers,Jon
