### ISSUE TITLE
improvments for 'import' & 'save project' features 

### ISSUE THREAD

**Issue by jeronomy** [OWASP/threat-dragon#409]
**Describe what problem your feature request solves**
This issue concerns 2 potential correlated but independent improvements:

1 - Reduce confusion for saving feature : when we hit "save" on the drawing panel, we are prompted with a green popup in the bottom left hand corner "Threat model successfully saved!", while a Windows Explorer popup ask us for a path to save the new file. 
So users can be left wondering : "Is my original old project .json file updated already, if I see the green popup ?" 

Moreoever, if the 'save' button from drawing panel would only update the project internaly it would be 'much' simpler, imo !
And back on the main menu/ screen, user could download the file, or save it with a new name : maybe simpler (so the green popup would stay exactly the same & the message would be more easy to grasp ?)

2 - Add 'Open recent project' option in the menu : TDv2 does not allow users to 'easily' open back the last edited TD project.
This feature would be really nice to have ! 
(If fantasy is allowed: a widget with 3 or 5 Latest TD projects on the welcome screen would be awarded with a golden globe oscar of the best 'user experience for a free & open source threat modeling tool' !)

And / or : the feature 'import a threat model via json' would be better if user could select the file from Windows/macOS/Linux explorer ! 
And also if user could drag / drop the Json file into the welcome interface of ThreatDragon for automatic loading : very nice User Experience imo !

**Additional context**
V2 : Windows 10 desktop & also web version

This issue is linked to this thread : https://github.com/OWASP/threat-dragon/issues/399#issuecomment-1091775573

Have a good day :)

**Comment by jgadsden** [comment]
Thanks again for the good bug report @jeronomy 
I am working on this feature - save of models - so I can assign this to myself  and see how I get on

**Comment by jgadsden** [comment]
Partially completed by issue #543 / pull request #542

**Comment by jgadsden** [comment]
@jeronomy the local filesystem access has had major changes, particularly for the desktop version, and is the subject of a pull request #559 

This issue can now be closed, and if you can take another look at the revised save, open, etc and create a new issue for anything you would like changed
