### ISSUE TITLE
Windows Desktop App crashed multiple times when using export feature

### ISSUE THREAD

**Issue by jeronomy** [OWASP/threat-dragon#410]
**Describe the bug**
I was searching for a way to export report in pdf : this is one of the last feature that is missing for me to do some demo of the tools to some of my coworkers so I am eager to find it :)

While testing 'Report - export' feature, the app crashed.

But unfortunatly I did not found debug file to help me provide info for helping you help me on this issue.
If there is an option to enable a debug file, or verbose output or anything else, let me know, I could try to be usefull on this, if I could !

**Expected behaviour**
When exporting a report : users will probably love to get a good old nice looking pdf file (instead of a good old nice looking crash)

**Environment**
Windows 10 desktop app v2

Have a great one ! :)

**Comment by jgadsden** [comment]
Thanks @jeronomy - will keep an eye on this one, we are still developing version 2.0 so it may not be a problem in the future
If you see it happen again then it would be great to have the steps to reproduce 👍🏾

**Comment by codingchili** [comment]
similar issue with the report -> export pdf on desktop 1.6.1, the file browser doesn't trigger and the user gets stuck in the "document-preview view" on Windows 10, works on another box with Windows 11. No errors logged in the console.

**Comment by jgadsden** [comment]
Version 2.0 is much more stable and no longer see this issue
