### ISSUE TITLE
apply i18n to desktop drop down menus

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#413]
**Describe what problem your feature request solves**
The desktop version of threat Dragon has drop down menus that do not follow the i18n selection; always in English

**Describe the solution you'd like**
Drop down menus should follow i18n

**Additional context**
a tutorial on an i18n implementation: https://phrase.com/blog/posts/building-an-electron-app-with-internationalization-i18n/#Switching_Locale_from_the_Menu

**Comment by guptaharsh13** [comment]
Hi @jgadsden,
I would love to work on this issue. Could you please assign the same to me.

**Comment by jgadsden** [comment]
Hello @guptaharsh13 - all yours! Thank you for taking this on

**Comment by jgadsden** [comment]
I have applied some translations to the dropdown menu. These still need to be applied dynamically, probably using technique here: https://phrase.com/blog/posts/building-an-electron-app-with-internationalization-i18n/#Adding_The_Menu
