### ISSUE TITLE
revise version 2 workflow release process

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#418]
**Describe what problem your feature request solves**
We need to rewrite workflow .github/workflows/release.yaml for version 2.0

**Describe the solution you'd like**
this is the automation for when a new tag is created, which can then be used for the release candidate

**Additional context**

**Comment by ShubhamPalriwala** [comment]
@jgadsden What are we planning to rewrite [here](https://github.com/OWASP/threat-dragon/blob/main/.github/workflows/release.yaml.bak)?

Like are we supposed to enhance anything here?

**Comment by jgadsden** [comment]
at the moment `.github/workflows/release.yaml` from 1.x is disabled - see `.github/workflows/release.yaml.bak` - and it has a comment "# TODO - This will need to be re-written for v2"

**Comment by ShubhamPalriwala** [comment]
Okay! What is supposed to be done though xD? Why are we changing the release process? 
I'm assuming changing/TODO means something other than **uncommenting** the code xDD?

**Comment by lreading** [comment]
My ideal situation would be that it fully automates the steps required for a release. We should be able to trigger this action when we push a tag. The steps (from memory):
- build/push the docker image with with the git tag
- create the GitHub release draft (visible to maintainers)
- build the signed electron packages (win, Mac, nix)
- push to snapcraft


It's currently set up to look for the td.desktop directory, and I don't know how far along we are with the election build yet
