### ISSUE TITLE
Reactive CSS results in oversized DFD elements

### ISSUE THREAD

**Issue by sparticvs** [OWASP/threat-dragon#422]
**Describe the bug**
There is an issue where triggering reactive CSS, results in DFD elements (e.g. data-flow arrows, threat boundary, etc) displaying incorrectly - either missing or significantly larger than the expected size.

**Expected behaviour**
Resizing of the desktop app window would keep the elements at a fixed size relative to the resolution.

**Environment**
 - Version: 1.6.1
 - Platform: Desktop App
 - OS: Linux / RHEL 8 w/ GNOME v3.32.2
 - Browser: N/A
 - *Note: RPM used is built as part of [my Fedora COPR](https://copr.fedorainfracloud.org/coprs/sparticvs/owasp-threat-dragon/), but should also exist in the project official RPM*

**To Reproduce**

1. Open Desktop Application
2. Either open an existing model or create a new model
3. (If creating a new model, edit and add a diagram. don't open it yet)
4. Resize the window to have reactive css displaying kick-in (usually when the edit, report, delete buttons move to a new line)
5. Open diagram
6. Notice that data-flow and trust boundary lines are very large
7. Resize screen to deactivate reactive css
8. Notice that elements move behind the drawing canvas or are still very large

**Any additional context, screenshots, etc**

![image](https://user-images.githubusercontent.com/847020/164325106-506caaea-7677-4753-90f3-e0158b03ebab.png)

**Comment by jgadsden** [comment]
Thanks @sparticvs - we can check that this does not happen on version 2.0, we hope it is restricted to version 1.x and JointJS

**Comment by jgadsden** [comment]
Checked that this does not happen for version 2.0 (see https://www.threatdragon.com), and so it is only for 1.x versions and to do with the version of JointJS used.
We are not planning any updates for version 1.x, unless it is a security update, so closing this issue ... I hope that is OK with you @sparticvs
