### ISSUE TITLE
v2 - Add date to report export

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#424]
**Describe what problem your feature request solves**
It would be good to date timestamp the generation of the PDF / hardcopy report.
**Describe the solution you'd like**
Put a date timestamp on the footer of the report when it is exported to PDF or printed out

**Additional context**
 This is useful for audit purposes, so that the state of the threatmodel is shown at a particular time - often we have to prove that we have implemented a secure software development lifecycle, and part of this involves evidence that we have been creating threat models during the SSDLC

**Comment by lreading** [comment]
Is this an OS-specific type of thing? 
On Ubuntu 22.04, the footers in the PDF/Printed report contain the URL and date/time.  I can check other systems at some point. :)
![image](https://user-images.githubusercontent.com/5851985/166863215-8726939e-15e6-433a-a30a-61359b3e4231.png)

The printed report also has a date (no time) on the cover-page:
![image](https://user-images.githubusercontent.com/5851985/166863275-962892c0-d81d-4704-9a28-425ad347eddf.png)


The "online" report does not include any timestamp, however.

**Comment by jgadsden** [comment]
oops, I was looking at the report using the wrong version (1.x) ... it happens :)

I agree, this is already done and nothing further to do
