### ISSUE TITLE
Quick arrow connection between elements

### ISSUE THREAD

**Issue by github-itsec-oculavis** [OWASP/threat-dragon#429]
**Describe what problem your feature request solves**
It allows you to directly connect an element with another by a data flow arrow just by clicking on it.

**Describe the solution you'd like**
It would be nice to have the same feature as in v.1.x, where if you click an element, the selected element shows an (X) and a (>) symbol (upper left part), the last of which (>) lets you connect the selected element with another element just by clicking on it.

**Additional context**
As already mentioned, it would be nice to have, because the task of connecting elements is a bit more tedious now. But definitely not a must or urgent, as it already works fine and does what it should.

**Comment by jgadsden** [comment]
Many thanks @github-itsec-oculavis - it would be good to have this back in version 2.0
We had a bit of problem with grabbing some types diagram elements, but @lreading has sorted this out and we may be able to reinstate this feature

**Comment by jgadsden** [comment]
In pull request https://github.com/OWASP/threat-dragon/pull/394 the magnet attribute was disabled to allow grab of the whole shape
We need to reinstate ability to create data flows by selecting diagram element, possibly using ports, while keeping the ability to grab of the whole shape
X6 has some tutorials on ports, this may give us what we need

**Comment by jgadsden** [comment]
it is unlikely that we can get this into version 2.0, so targeting version 2.1

**Comment by jgadsden** [comment]
marking this as a bug because of the missing functionality
