### ISSUE TITLE
Pipeline action: deploy has stopped working

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#431]
**Describe the bug**
The deploy action has stopped working, first noticed on 14th May :
https://github.com/OWASP/threat-dragon/actions/workflows/deploy.yaml

**Expected behaviour**
Deploy action used to work OK, and we need it for our demo on Heroku

**Environment**
 - Version: latest
 - Platform: Desktop App
 - OS: any
 - Browser: any

**To Reproduce**
Merge a commit to the main branch, and observe deploy action failing

**Any additional context, screenshots, etc**
Error response from daemon: login attempt to https://registry.heroku.com/v2/ failed with status: 401 Unauthorized

**Comment by jgadsden** [comment]
This is expected, Heroku suffered a breach and have been resetting passwords from 4th May:

"Heroku will start resetting user account passwords today, May 4, 2022, as mentioned in our previous notification. We recommend that you reset your user account password in advance [here](https://id.heroku.com/account/password/reset) and follow the best practices below: 

Minimum of 16 characters 
Minimum complexity of 3 out of 4: Uppercase, Lowercase, Numeric, Symbol

If you do not reset your password and your user account password is reset by Heroku today, your existing password will no longer work. To log in to Heroku, you must reset your password by accessing the Heroku login page and clicking the "Forgot your password?" [link](https://id.heroku.com/account/password/reset) . Due to the nature of this issue, you may be required to reset your passwords again in the future. 

NOTE: A password reset will also invalidate your API access tokens. As a result, any automations you’ve built to integrate with the Heroku Platform API that use these tokens may result in [403 forbidden errors](https://help.heroku.com/PBGP6IDE/how-should-i-generate-an-api-key-that-allows-me-to-use-the-heroku-platform-api) . To avoid downtime you will need to re-enable direct authorizations by following the instructions [here](https://devcenter.heroku.com/articles/oauth#direct-authorization) and update your integrations to use your newly generated token."

**Comment by jgadsden** [comment]
The breach notification was on 4th April:

"At Salesforce, we understand that the confidentiality, integrity, and availability of your data are vital to your business, and we take the protection of your data very seriously. We value transparency and wanted to notify you of an incident we're actively investigating that may lead to unauthorized access to your GitHub repositories connected to Heroku.

Please visit [status.heroku.com](http://click.msg.salesforce.com/?qs=2d587289801a58af178d6e6e4563e1e491cc23542420ccc59ffb3389653fdd9ba22386fc4c1ac301a9536582cc7c310e87c6b32900f3be9443d48f17197203ef) for additional information. If Salesforce becomes aware of unauthorized access to customer GitHub repositories connected to Heroku, we will notify affected customers by email without undue delay."

**Comment by lreading** [comment]
Whoops! I had reset my password but overlooked the API key part.  I'll fix this today. :smile: Thanks for bringing it up!  I'm only getting notified on GH action failures when it's related to a specific commit/push I've done, I'm not getting notified on the scheduled ones.  I'll have to look into that as well.

**Comment by jgadsden** [comment]
Thanks @lreading - it has only recently become an issue, and the demo + docs is still good

**Comment by lreading** [comment]
I regenerated the API key and updated the repo secret, working again. :smile: 

https://github.com/OWASP/threat-dragon/runs/6557902601?check_suite_focus=true
