### ISSUE TITLE
Can't print reports

### ISSUE THREAD

**Issue by dzablo** [OWASP/threat-dragon#436]
**Describe the bug**
When I try to "print" the report, the app crash.
here is the test JSON file
[test.json.log](https://github.com/OWASP/threat-dragon/files/8853741/test.json.log)

**Expected behaviour**
I should be able to "print" the report.

**Environment**
 - Version: 2.0
 - Platform: Desktop App
 - OS: Linux
 - Browser: chrome

**To Reproduce**
1. Create a new report
2. Click the report
3. Click the print

**Any additional context, screenshots, etc**
here is the error I get in the terminal

``` INFO  Launching Electron...
(node:234607) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/adamjablonski/git/tools/threat-dragon/td.vue/dist_electron/package.json' of 'background.js'. Please either fix that or report it to the module author
(Use `electron --trace-deprecation ...` to show where the warning was created)
(node:234607) ExtensionLoadWarning: Warnings loading extension at /home/adamjablonski/.config/Threat Dragon/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
Crashing due to FD ownership violation:
#0 0x56107bf647a3 <unknown>
#1 0x56107c0107dc <unknown>
#2 0x56107c0107a1 <unknown>
#3 0x7f8341de8cdb <unknown>```

I think my system lacks some lib, so if you have any idea, please give me advice :)

**Comment by jgadsden** [comment]
Hello @dzablo 

These are the steps I took to try and reproduce this:

1. clone the repo, install and then run `pnpm run start:desktop`
2. 'Login with local session'
3. 'Import a threat model via JSON'
4. paste the contents of [test.json.log](https://github.com/OWASP/threat-dragon/files/8853741/test.json.log)
5. 'Import'
6. 'Report'
7. 'Print'
8. 'Save as PDF' from 'PDF' pull-down
9. 'Save'

this gave me file [OWASP Threat Dragon.pdf](https://github.com/OWASP/threat-dragon/files/9554991/OWASP.Threat.Dragon.pdf)

Can you try this again? I will create a Cypress e2e test for this so we can continually check that it is working

**Comment by jgadsden** [comment]
Thanks @dzablo 
The difference I see in my console output is that you have:
```
Error: Could not find a package.json for module ajv
    at $HOME/git/tools/threat-dragon/td.vue/node_modules/.pnpm/vue-cli-plugin-electron-builder@2.1.1/node_modules/vue-cli-plugin-electron-builder/lib/webpackConfig.js:149:17
    at Array.reduce (<anonymous>)
...
```

This looks like `pnpm install` is either out of date or needs to be run again. Could you install again and make sure you are not getting `Could not find a package.json` errors?

**Comment by dzablo** [comment]
@jgadsden I still get the error :/ 

```
pnpm run start:desktop

> threat-dragon@2.0.0 start:desktop $HOME/git/tools/threat-dragon
> cd td.vue && npm run electron:serve


> threat-dragon-frontend@2.0.0 electron:serve
> vue-cli-service electron:serve

Server API protocol: http and port: 3000
 INFO  Starting development server...


 WARNING  Compiled with 2 warnings                                                                                                                                                                                                                                     10:22:42 AM

 warning  in ./src/App.vue?vue&type=style&index=0&id=7ba5bd90&lang=scss&

Module Warning (from ./node_modules/.pnpm/postcss-loader@6.2.1_mepnsno3xmng6eyses4tepu7bu/node_modules/postcss-loader/dist/cjs.js):
Warning

(3294:3) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.

 warning  in ./src/components/DashboardAction.vue?vue&type=style&index=0&id=4ed74a2c&lang=scss&scoped=true&

Module Warning (from ./node_modules/.pnpm/postcss-loader@6.2.1_mepnsno3xmng6eyses4tepu7bu/node_modules/postcss-loader/dist/cjs.js):
Warning

(3293:3) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.


  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.15.150:8080/

  Note that the development build is not optimized.
  To create a production build, run pnpm run build.

⠹  Bundling main process...

 DONE  Compiled successfully in 1195ms                                                                                                                                                                                                                                 10:22:44 AM

  File                     Size                                                                                                                      Gzipped

  dist-desktop/index.js    1335.24 KiB                                                                                                               293.32 KiB

  Images and other types of assets omitted.
  Build at: 2022-09-15T08:22:44.114Z - Hash: 856df6e0e669dc869b92 - Time: 1195ms

 INFO  Launching Electron...
10:22:44.670 › update-electron-app config looks good; aborting updates since app is in development mode
(node:438132) [DEP0128] DeprecationWarning: Invalid 'main' field in '$HOME/git/tools/threat-dragon/td.vue/dist-desktop/package.json' of 'background.js'. Please either fix that or report it to the module author
(Use `electron --trace-deprecation ...` to show where the warning was created)
(node:438132) ExtensionLoadWarning: Warnings loading extension at $HOME/.config/Threat Dragon/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
10:22:44.908 › Log level is set to: info
10:22:44.910 › Running in development mode with WEBPACK_DEV_SERVER_URL: http://localhost:8080/
Crashing due to FD ownership violation:
#0 0x5591dfce8c53 <unknown>
#1 0x5591dfd94c8c <unknown>
#2 0x5591dfd94c51 <unknown>
#3 0x7f44b6d70ef3 <unknown>
```

**Comment by dzablo** [comment]
I'm pretty sure it is the same issue https://github.com/electron/electron/issues/31151 because when I call `window.print()` in the dev console the issue occurs.

**Comment by jgadsden** [comment]
Many thanks for investigating @dzablo 
What do we want to do here? I do not want to hold up Threat Dragon Version 2.0, as there does not seem to be a fix from electron.
I can tag it Version2.x and wait for a fix from Electron?

**Comment by dzablo** [comment]
> What do we want to do here? I do not want to hold up Threat Dragon Version 2.0, as there does not seem to be a fix from electron.
I can tag it Version2.x and wait for a fix from Electron? 

I think we can leave it with the tag and wait for the fix, and for the others who have the same problem, I would like to recommend as a workaround to run the `pnpm run start:server` and use your favorite browser :)

**Comment by jgadsden** [comment]
Keeping this issue **Open** until we get a fix from Electron, although it may not get resolved for the upcoming version 2.0 release.  Created [a wiki FAQ](https://github.com/OWASP/threat-dragon/wiki/FAQs#failure-when-printing-a-report) to help

**Comment by jgadsden** [comment]
Hello @dzablo - can you try with the latest version v2.0.0 of Threat Dragon desktop? Available from the release area

Also are you using a network printer - that may be the problem : https://github.com/electron/electron/issues/31151#issuecomment-1313218193

**Comment by dzablo** [comment]
@jgadsden sorry, I change the laptop and now works fine, so we can close this issue.

**Comment by jgadsden** [comment]
cool, thanks @dzablo
