### ISSUE TITLE
Error occurs when converting between TMT thread model to OWASP model

### ISSUE THREAD

**Issue by AlamosJ** [OWASP/threat-dragon#438]
When running the ConvertTMT2TD.py script a list index out of range error occurs and the TMT file cannot be converted.

**Expected behaviour**
The TMT file should be converted to OWASP's json format.

**Environment**
 - Version: 1.6
 - Platform: Desktop app
 - OS: Windows
 - Browser: Chrome

**To Reproduce**
   1. Run the ConvertTMT2TD script
   2. Select a TMT file to convert

**Any additional context, screenshots, etc**

Error code thrown
<img width="509" alt="Annotation 2022-06-16 121850" src="https://user-images.githubusercontent.com/65973160/174148291-b2a70796-9018-4b10-a9dd-233966c0cb5f.png">

If anyone else encounters this error, I have found a solution to this issue. Just figured I should put this on the board anyways.

Solution
<img width="842" alt="Annotation 2022-06-16 121745" src="https://user-images.githubusercontent.com/65973160/174148132-da16fa27-9e17-476a-b25a-0e63389550f9.png">

Adding "diagramnum = 0"  after line 430 clears up this error.

**Comment by jgadsden** [comment]
Hello @AlamosJ 

Many thanks for reporting this and even better providing a fix.

I have applied your change in commits:
* V2.x: https://github.com/OWASP/threat-dragon/commit/33f2cfa681629c5198693e483ff0f25eeab49048
* V1.x: https://github.com/OWASP/threat-dragon/commit/6541f89620b485dfaae5d90858aaa57e28bb9d65

Thanks again!
