### ISSUE TITLE
Permissions failure opening Mac desktop app

### ISSUE THREAD

**Issue by lucasgonze** [OWASP/threat-dragon#439]
1. Download OWASP-Threat-Dragon-1.6.1-mac
2. Unpack
3. Right click and select "open"

Expect: app starts
Actual: "You do not have permission to open the application"

<img width="248" alt="image" src="https://user-images.githubusercontent.com/111581/174339276-40243a6c-3127-4379-936d-718c5ca4a640.png">

4.  Open Terminal. Use command "open <path to .app directory>"
5. Get error with diagnostic information

> The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2436, NSUnderlyingError=0x7fdfe95182f0 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x7fdfe9518ab0 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 111}}}}}

6. sudo open <path to .app>
7. Get error with different diagnostic information

> The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2436, NSUnderlyingError=0x7f81fce0e660 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x7f81fce081c0 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 111}}}}}

**Comment by jgadsden** [comment]
Hello @lucasgonze

Apologies for not responding sooner, I was on vacation in a place without internet (hard to find, but they still exist :)

It looks like your MacOS has a security policy that  does not allow the zip archive to run directly, which is the case for the majority (but not all) MacOS these days. Can you try the installer [OWASP-Threat-Dragon-1.6.1.dmg](https://github.com/OWASP/threat-dragon/releases/download/v1.6.1/OWASP-Threat-Dragon-1.6.1.dmg) ?

This should install directly without need for any security exception.

There are some instructions at https://threatdragon.github.io/install-desktop/#macos-installer , but it should be made clearer in the instructions that the `.dmg` file should be used in most cases. I will raise a Docs issue for this

**Comment by jgadsden** [comment]
Raised Docs issue : https://github.com/threatdragon/threatdragon.github.io/issues/35

**Comment by lucasgonze** [comment]
Jon, thanks for this guidance. I will try again, using the DMG.

**Comment by jgadsden** [comment]
I have updated the [wiki to include this]( https://github.com/OWASP/threat-dragon/wiki/FAQs#why-do-i-get-permissions-failure-opening-mac-desktop-app-when-installing-from-the-zip-file) and have also have [updated the documentation](https://github.com/threatdragon/threatdragon.github.io/edit/main/public/pages/install/install-desktop.markdown)
