### ISSUE TITLE
multiple-line description support 

### ISSUE THREAD

**Issue by gassara-kys** [OWASP/threat-dragon#468]
**Describe the bug**

If we have written a multi-line `High level system description`, it will be rendered on a single line in the model and report screens.

**Expected behaviour**

To be rendered in multiple lines in the above screens

**Environment**
 - Version: 2.0.0 (e.g. 1.3.1)
 - Platform: Web App (Web App / Desktop App)
 - OS: MacOS (MacOS / Windows / Linux)
 - Browser: chrome (e.g. chrome, firefox, safari)

**To Reproduce**

- create new model
- write description
- display dashboard & 

**Any additional context, screenshots, etc**

- submit mutiple-line description
  - ![image](https://user-images.githubusercontent.com/25426601/182982979-d1133484-eacc-49f7-a8ed-26793b047411.png)
- rendering single-line
  - ![image](https://user-images.githubusercontent.com/25426601/182983712-762588f1-3408-43ee-b422-0d3c6147e94f.png)

**Comment by jgadsden** [comment]
Thanks @gassara-kys for finding this. We have multi-line descriptions in 1.x, so it should be relatively straight forward to reinstate this for version 2.0
I have marked it as a priority for version 2.0

**Comment by Rets66** [comment]
There are some related issues.

I inputed the text to `Discription` and `Mitigations` like as follows:
- Discription
  <img width="1959" alt="スクリーンショット 2022-08-09 21 23 59" src="https://user-images.githubusercontent.com/17017861/183646762-0d512008-10fd-4bf0-b366-a23f89008c74.png">
- Mitigation
  <img width="787" alt="スクリーンショット 2022-08-09 21 24 22" src="https://user-images.githubusercontent.com/17017861/183646795-c055491f-19fa-4d66-9ce1-48481af2bee3.png">

But the out put were like this:
<img width="1959" alt="スクリーンショット 2022-08-09 21 22 37" src="https://user-images.githubusercontent.com/17017861/183647358-eb4cdfca-deb5-4153-8b07-593ef1e89c95.png">
