### ISSUE TITLE
Sometimes fail to install geckodriver on windows platform

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#471]
**Describe the bug**
On windows platform there is a report of unable to `pnpm install` on the main branch. 

**Expected behaviour**
pnpm installation should succeed  under the main branch

**Environment**
 - Version: main branch
 - Platform: both Web App / Desktop App
 - OS:  Windows
 - Browser: any

**To Reproduce**
This does not seem to be for all installations, and is not reproduced for MacOS and Linux.

**Any additional context, screenshots, etc**
![geckodriver-install](https://user-images.githubusercontent.com/29352392/183052642-36e8977e-d2b9-4c73-a802-b9c99ad75f39.png)

**Comment by jgadsden** [comment]
Successful on MacOS and Linux, eg:

```
threat-dragon % pnpm install geckodriver
Packages: +44
++++++++++++++++++++++++++++++++++++++++++++
node_modules/.pnpm/geckodriver@3.0.2/node_modules/geckodriver: Running postinstanode_modules/.pnpm/geckodriver@3.0.2/node_modules/geckodriver: Running postinstall script, done in 640msreused 125, downloaded 2, added 44, done

dependencies:
+ geckodriver 3.0.2
```

**Comment by taoyiyang1** [comment]
I removed it from package.json, will this work? @jgadsden

**Comment by jgadsden** [comment]
Hello @taoyiyang1 , we would prefer to keep geckodriver in the packages used for TD front-end. I have updated the main branch to use geckodriver version 3.0.2, could you pull this change and try installing again?

With a bit of luck this may cure the problem

**Comment by taoyiyang1** [comment]
All problems are solved, many package installations have to use a VPN, China has too many restrictions @jgadsden

**Comment by jgadsden** [comment]
Thanks for finding out what the problem is @taoyiyang1 
I will update the documentation to suggest using a VPN if there are problems installing

**Comment by jgadsden** [comment]
I have added a FAQ in the Threat Dragon wiki : https://github.com/OWASP/threat-dragon/wiki/FAQs#failures-when-installing-from-source-code
