### ISSUE TITLE
Convert json file to graphic, e.g. svg

### ISSUE THREAD

**Issue by AG4GitHub** [OWASP/threat-dragon#497]
**Describe what problem your feature request solves**

for external reprorts, discussion and presentation, it would be great to export or edit the model as a graphic. 
**Describe the solution you'd like**
Hi, 
Is the a way to convert the json file in a graphic, best scalable format?
**Additional context**

Is there a plan to add export format, so that the models can be edited externally?

thanks for the attention

**Comment by jgadsden** [comment]
Hello Andreas, could you describe what you want in more detail? Do you want just the diagram as a graphic?

We have the pdf output for the report, but this has all the wording attached.

**Comment by jgadsden** [comment]
The best way to do this is to create a report, which displays the diagram ready for printing,  and then either capture from the screen to create the graphic or print to PDF and then edit the diagrams from the PDF file
