### ISSUE TITLE
provide OATs (OWASP Automated Threats) by property

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#501]
**Describe what problem your feature request solves**
It would be good to reinstate this feature provided by version 1.x

**Describe the solution you'd like**
Apply OATs according to the property of the diagram element

**Additional context**

**Comment by raghav1030** [comment]
Hey @jgadsden, Could you please assign it to me?

**Comment by jgadsden** [comment]
Certainly! Thanks for taking this on @raghav1030 as part of the Google Summer of Code

**Comment by jgadsden** [comment]
@raghav1030 this will reimplement a feature that was present in versions 1.x, but has yet to be implemented in version 2.x of Threat Dragon
If you install version 1.6.1 and start adding threats to a diagram, you can see that there is a selection in the left hand pane for 'Threat within context'. This feature should be added to version 2.x, with a similar flow / functionality as version 1.x

**Comment by raghav1030** [comment]
Thank you, @jgadsden for your guidance. I'll look into it and get back to you.

**Comment by professorabhay** [comment]
Hey @jgadsden, I hope you are doing well. I found that this issue falls under GSoC 2024. I'm just wondering if it is still open for all or not.

**Comment by jgadsden** [comment]
Hello @professorabhay , this has been assigned to @raghav1030 for GSoC 2024

**Comment by jgadsden** [comment]
@mohamedselbohy from our discussions you would like to look at this issue, so I have assigned it to you if that is OK
it is targeted for version 2.4 in Q4 2024, but if that is too soon then get back to me

**Comment by mohamedselbohy** [comment]
Of course! I would be happy to work on this feature, and I expect to finish it before the deadline, having enough time to discuss my implementation if needed.
