### ISSUE TITLE
Docs: threat documentation page out of date

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#503]
**Describe the bug**
Version 2.0 documentation page at `docs/usage/modeling/threats.md` is out of date

**Expected behaviour**
Needs updating before release

**Environment**
 - Version: 2.0, 2.x
 - Platform: both Web App / Desktop App
 - OS: all MacOS / Windows / Linux
 - Browser: any chrome, firefox, safari

**To Reproduce**
visit : https://www.threatdragon.com/docs/usage/modeling/threats.html

**Any additional context, screenshots, etc**

**Comment by professorabhay** [comment]
Hey @jgadsden, If I am not wrong then we just need to update the file as per the new version. 
Have to include all new features??

Please help out, I am interested to solve this..

**Comment by jgadsden** [comment]
This has been done with commit 8b7d75ffdbf31b0af018eef4fa1aff973044a8c5
