### ISSUE TITLE
Cannot import a model in the new version

### ISSUE THREAD

**Issue by gmaran23** [OWASP/threat-dragon#505]
**Describe the bug**
An existing model that was created in [https://www.threatdragon.com](https://www.threatdragon.com) does not load anymore using the "Import via JSON" function

**Expected behaviour**
The model should get imported, a diagram should be available, a list of threat should also me made available

**Environment**
 - Version: (unsure - but this model used to load in threatdragom.com a few weeks after June 20)
 - Platform: (Web App)
 - OS: (Linux)
 - Browser: (chrome, firefox)

**To Reproduce**
Here is the JSON of the model with diagram information, and threats. - https://gist.github.com/gmaran23/1b87069cc69d1532cfa2a300416ecb11

Try importing the model as JSON. When you get past the v2 message, the diagram along with a list of threats should be shown.

**Any additional context, screenshots, etc**

Questions:
1. Is there a recommended way to use this threat model with the newer version?
2. Could you point me to a list of changed JSON elements perhaps? so that I can edit the JSON to be usable in v2
3. What other advise do you have to save some time from redrawing and adding information to create a new model?

Thank you very much.

**Comment by jgadsden** [comment]
Hello @gmaran23 - thanks for the bug report. We are working in this general area with #409 and #383 , so this is a useful test to see if we get it right
At the moment we flag a warning that version 2.0 may be compatible with version 1.x files ... but we hope that when it is released as version 2.0 we will have the compatibility in place

**Comment by gmaran23** [comment]
Thank you for responding soon. 

For the moment, would you advise that I redraw the diagram and annotate with threats using the current version live at https://www.threatdragon.com/?

I am asking because if there is a future change that 'may' break the new diagrams that I am planing to draw in a couple of days, then I would hold, and try with a newer version when it is out.

**Comment by jgadsden** [comment]
Personally I would _not yet use_ version 2.0 for any existing threat models. I would wait for version 2.0 to be released and stable, at that point we would hope that it is fully compatible with version 1.x
At the moment I am still using version 1.6.1 for all my threat models, because version 2.0 models are subject to change

**Comment by gmaran23** [comment]
Thank @jgadsden for your response. I will try with the 1.6.1, and keep you posted.

**Comment by jgadsden** [comment]
Hello @gmaran23 
I did some more tests, and the JOSN Import feature works if the model is an existing version 2.0, but if it is a version 1.x then it gets stuck as you describe
I think it has been like this for some time - it is throwing a navigation guard error on a version 1.x import:

```
vue-router.esm.js:2065 Uncaught (in promise) Error: Redirected when going from "/local/threatmodel/import" to "/local/New%20threat%20model" via a navigation guard.
    at createRouterError (vue-router.esm.js:2065:1)
    at createNavigationRedirectedError (vue-router.esm.js:2024:1)
    at vue-router.esm.js:2376:1
    at upgradeGuard (index.js:49:16)
    at iterator (vue-router.esm.js:2362:1)
    at step (vue-router.esm.js:2004:1)
    at step (vue-router.esm.js:2008:1)
    at runQueue (vue-router.esm.js:2012:1)
    at HashHistory.confirmTransition (vue-router.esm.js:2392:1)
    at HashHistory.transitionTo (vue-router.esm.js:2260:1)
```

**Comment by jgadsden** [comment]
And then having said all that, I can see from https://gist.github.com/gmaran23/1b87069cc69d1532cfa2a300416ecb11
that you already have a version 2.0 model ... but the schema has changed from using 'version' to use 'tdVersion'

This was probably a bad change - it adds nothing and breaks a lot of stuff ... so it will be reverted
and this means that your version 2.0 files will start working again @gmaran23 , just give me a couple of hours to promote this change to the threatdragon.com site

**Comment by gmaran23** [comment]
@jgadsden Thank you very much for the efforts. Appreciate it very much. 
I can confirm that the model - https://gist.github.com/gmaran23/1b87069cc69d1532cfa2a300416ecb11 loads well at threatdragon.com.

I will test this out locally and close this issue soon.

**Comment by jgadsden** [comment]
All seems good now, so closing
