### ISSUE TITLE
Signed Bundles

### ISSUE THREAD

**Issue by storkinsj** [OWASP/threat-dragon#52]
**Describe what problem your feature request solves**
Threat Dragon is currently not signed. This is not only dangerous as it trains people to install unsigned code (if you'd like a dragon threat model to showcase the threats- I'll hand you one!), but it is actually disallowed in good organizations like mine where managed machines are disallowed from running most unsigned code.

**Describe the solution you'd like**
Signed package builds or App Store builds

**Additional context**
If you would like a donation to cover the cost of the ADC license, hit me up.

Another suggestion: remove the comments from your template. I am guessing it often results in commented out suggestions!

**Comment by jgadsden** [comment]
Hello @storkinsj - this is a very good point, and it has been a long running problem because the Apple developer licence costs ... and we are only volunteers :-)

If it makes it any better (and it does not really) OWASP project ZAP and Amass have the same problem.

The good news is that the company I work for has this week given me an Apple developer licence ... so I was planning on releasing version 1.3.2 later this month with some bug fixes and properly signed downloads.

Thanks for the really good suggestions - much appreciated.

(this is very similar to desktop issue https://github.com/OWASP/threat-dragon-desktop/issues/43)

**Comment by storkinsj** [comment]
Wow that is really cool. For attribution's sake, I trust the license is not tied to the company?

Again, I'm really happy to donate if you want one for the group. You should arrange who will manage it.

**Comment by jgadsden** [comment]
Hello @storkinsj - yes, thanks, it is good of my employer. It is not tied to them ... I have yet to go into it fully but it will be for me at my owasp.org address (jon.gadsden@owasp.org)

Will keep you informed as to how I get on, maybe tracking this in OWASP/threat-dragon-desktop#43

**Comment by storkinsj** [comment]
@jgadsden Hi Jon- I am checking in as I have found out there is a "threat dragon core" repo as well.
If my other issues belong there instead of here, please let me know and I can move them.

**Comment by jgadsden** [comment]
Hello @storkinsj - sure, I will go through them now and make suggestions. I meant to have a look before now but it was a busy weekend (happy family stuff), but I am back now :-)

**Comment by jgadsden** [comment]
@storkinsj , there are 3 repos, one for the web app, one for the desktop app and one for the common code between them, which includes the JointJS which is giving us all the problems.

Version 2.0 will not be structured like this, just one repo for the web app and another electron-based repo to provide the desktop app. But until thenn we have the three repos

**Comment by jgadsden** [comment]
Use github [commit signature verification](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification)

**Comment by lreading** [comment]
@storkinsj - [Version 1.5.3](https://github.com/OWASP/threat-dragon/releases/tag/v1.5.3) has been released which has signed/notarized MacOS installers.  As Jon mentioned, the signing key is issued to him personally.  Hopefully this will help meet the requirements of more organizations with those security controls in place. :smile:
