### ISSUE TITLE
I18N: add German translation

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#524]
**Describe what problem your feature request solves**
It would be good to have the German translation for Threat Dragon

**Describe the solution you'd like**
Modify [translation file](https://github.com/OWASP/threat-dragon/blob/main/td.vue/src/i18n/de.js)

**Additional context**

**Comment by sparticvs** [comment]
@jgadsden I'm looking into this further, I think there is an assumption of English grammar in the structuring here - I'm looking into this further, but we may need to make some other adjustments to get a coherent German translation. I'll likely leave parts of this in English to purely support not needing any UI changes at the moment. I'm not 100% certain at the moment, so I'm still investigating this.

**Comment by professorabhay** [comment]
Hey @jgadsden, Can I resolve this issue and merge PR after creating and close this also??👨🏻‍💻 
Please explain it little more to me!!

**Comment by jgadsden** [comment]
Hello @professorabhay , how good is your German language?

**Comment by professorabhay** [comment]
🥲 Not so good 
Just basic but I can do it correctly 🤠

**Comment by sparticvs** [comment]
@professorabhay - Mochtest du die Veränderungen überprüfen?

@jgadsden - I've been working on this in my spare time, which has me slowed down with a new puppy and toddler in the mix. I've been also making sure that the wording is aligned with the threat modeling papers that have been published by students from German universities.

**Comment by professorabhay** [comment]
@sparticvs 
Ya sicher !!

**Comment by jgadsden** [comment]
@Zmiler you may want to work with @sparticvs on this tranlsation?

**Comment by Zmiler** [comment]
I would gladly help with translation. I am a native german speaker

**Comment by sparticvs** [comment]
I'll push up what I have completed ASAP if you want it.

@jgadsden how do you want the tracking done where the grammar doesn't work with the templating?

**Comment by jgadsden** [comment]
ah, can you give an example @sparticvs ? I am not sure what you mean

**Comment by Zmiler** [comment]
@jgadsden I translated most of it. I did not see any weird text wrapping yet. I will translate the remaining bits tomorrow and check all areas of the application

**Comment by sparticvs** [comment]
@jgadsden my concern was with the break up of "select", "from", etc. Looking at @Zmiler's translation, there probably isn't an issue after all.
