### ISSUE TITLE
I18N: add Russian translation

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#526]
**Describe what problem your feature request solves**
It would be good to have the Russian translation for Threat Dragon

**Describe the solution you'd like**
Modify [translation file](https://github.com/OWASP/threat-dragon/blob/main/td.vue/src/i18n/ru.js)

**Additional context**

**Comment by professorabhay** [comment]
Hey @jgadsden, Can I resolve this issue and merge PR after creating and close this also??👨🏻‍💻

**Comment by jgadsden** [comment]
Hello @professorabhay , how good is your Russian language?

**Comment by professorabhay** [comment]
привет @jgadsden , something like that 😅
But surely I can do it with zero mistakes !!

**Comment by jgadsden** [comment]
Hello @professorabhay , really we need a fluent Russian speaker to do this translation as translation of technical terms is not straight forward. I hope you do not mind but it would be better to get a fluent Russian speaker to do this translation

**Comment by professorabhay** [comment]
Okk sure !! 
I will help out in other issues.

**Comment by jgadsden** [comment]
@professorabhay if you are fluent in other languages beside English then you are very welcome to provide the translation file for that language.
I can create the framework file if you need it

**Comment by professorabhay** [comment]
Except English and Portuguese, I am fluent in my native language HINDI. 
Is there any need of file in Hindi language than I can make it. 

I am also interested to contribute in other tech issues. I commented on some of them. Please check it out

**Comment by jgadsden** [comment]
Hello @professorabhay , if you would like to create the Hindi translation file then that is great. Tell me if you need me to create the file for you.

**Comment by professorabhay** [comment]
Hai @jgadsden, Please create a file for me. I'll modify that!! 📝

**Comment by jgadsden** [comment]
No interest from the threat dragon community so closing this issue
