### ISSUE TITLE
I18N: update ES translation file

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#529]
**Describe what problem your feature request solves**
As Threat Dragon begins to approach the [release of version 2.0](https://github.com/OWASP/threat-dragon/projects/4), it would be good to update the Spanish translation

**Describe the solution you'd like**
Modify [translation file](https://github.com/OWASP/threat-dragon/blob/main/td.vue/src/i18n/es.js)

**Additional context**

**Comment by jgadsden** [comment]
I added some translations strings into the i18n file, but my Spanish is not as good as I thought it was, so it is incomplete

**Comment by professorabhay** [comment]
Hey @jgadsden, Can I resolve this issue and merge PR after creating and close this also??👨🏻‍💻

**Comment by jgadsden** [comment]
Hello @professorabhay , yes please go ahead and resolve / close this issue as done. Thanks again!

**Comment by professorabhay** [comment]
I'll do this asap!!🙂

**Comment by jgadsden** [comment]
Hello @professorabhay , how good is your Spanish language?

**Comment by professorabhay** [comment]
Hola 👋 @jgadsden, I can't speak fluently but I can survive in Spanish country. 
Or, In other way I can translate this 99% correctly.

**Comment by jgadsden** [comment]
Hello @professorabhay , really we need a fluent Spanish speaker to do this translation. I myself can speak Spanish fairly well, but I would not attempt translation of technical terms - it is not straight forward at all.

I hope you do not mind but it would be better to get a fluent Spanish speaker to do this translation

**Comment by professorabhay** [comment]
@jgadsden But I think that, we don't need a speaker for this. We can use another method to resolve this. No need of a Spanish speaker, we can do this by google translator for this work also. We can update values line by line after translating to Spanish. 
And I think that there is no need to tell, How good and efficient google translator is!!

something like shown in this reference image ==>>
![oswap new](https://user-images.githubusercontent.com/76243309/205046112-4b209141-5ec2-4b06-9cd2-8df212f2a549.png)

**Comment by jgadsden** [comment]
The problem with Google translate is that the translation can miss the subtleties of the language. 
The Spanish example given above was provided by a native Spanish speaker, but the Google version would be:
"Esta es la versión 2.0 de OWASP Threat Dragon y aún está en desarrollo. ¡No use esto para editar modelos existentes, ya que esta versión podría romperlos!"
which loses some of the technical meaning. If we translate the original Spanish version, or the Google version, into English using Google translate we get the same wording, and so missing some of the subtleties of Spanish.

Having said that, there is a typo and the 'do' should be 'de'

**Comment by professorabhay** [comment]
Ok !! 
No problem

**Comment by jgadsden** [comment]
@yaso and @GigliolaCordova is it OK to assign this to you? You provided the original translation file
