### ISSUE TITLE
I18N: update FR translation file

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#530]
**Describe what problem your feature request solves**
As Threat Dragon begins to approach the [release of version 2.0](https://github.com/OWASP/threat-dragon/projects/4), it would be good to update the French translation

**Describe the solution you'd like**
Modify [translation file](https://github.com/OWASP/threat-dragon/blob/main/td.vue/src/i18n/fr.js)

**Additional context**
@andk123  as you provided the original translation I hope you do not mind me assigning this to you?

**Comment by andk123** [comment]
Not at all, it will be my pleasure to do so! I will keep you updated once it's completed.

**Comment by jgadsden** [comment]
Thanks @andk123 , I have just added `threats.properties.number`, for labelling the threat number and `threats.properties.score` for labelling the custom score into the i18n file

**Comment by andk123** [comment]
Quite a busy week here, it will be done this weekend :)

**Comment by jgadsden** [comment]
No hurry at all, thanks @andk123 
There is one last major feature that we need for Version 2.0 which I am working on, so it may be early November (at the earliest) that it would be good to have the translations
