### ISSUE TITLE
I18N: update PT translation file

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#531]
**Describe what problem your feature request solves**
As Threat Dragon begins to approach the [release of version 2.0](https://github.com/OWASP/threat-dragon/projects/4), it would be good to update the Portuguese translation

**Describe the solution you'd like**
Modify [translation file](https://github.com/OWASP/threat-dragon/blob/main/td.vue/src/i18n/pt.js)

**Additional context**

**Comment by professorabhay** [comment]
Hey, I am interested to work on this. 
Can you plz explain it more?
I am new here but ready to learn.

**Comment by jgadsden** [comment]
Hello @professorabhay - this is the Portuguese translation file for Threat Dragon version 2.x. Certainly update it if you like:
https://github.com/OWASP/threat-dragon/blob/main/td.vue/src/i18n/pt.js

**Comment by professorabhay** [comment]
Hey @jgadsden - I want to update all lines of this file which is in English to Portuguese. Or anything else.

**Comment by jgadsden** [comment]
Hello @professorabhay , please go ahead and translate the English in `pt.js` to Portuguese - many thanks for doig this

**Comment by professorabhay** [comment]
Hey @jgadsden, I just updated the file and created a pull request. 
please review it and let me know if there is any problem in it.
![gitoswap](https://user-images.githubusercontent.com/76243309/204839157-98dcf901-25a9-4dc9-a30e-81bf133e1d51.png)

**Comment by jgadsden** [comment]
Hello @professorabhay , thanks for the translations. The JSON attributes should not be translated though, just the values, do you want to reinstate them?

**Comment by professorabhay** [comment]
Yes, I can do !!
I am attaching some images for referral of JSON attributes. I don't have enough knowledge about this 😐
If I am not wrong than are you talking about these.


![again1](https://user-images.githubusercontent.com/76243309/204866484-5fcd4031-b178-48ea-bcfd-0695d80afccc.png)
![again2](https://user-images.githubusercontent.com/76243309/204866491-08f3efbc-25d4-42ef-8640-cacb4af559ef.png)

**Comment by professorabhay** [comment]
Hello @jgadsden, I just updated again as you want. Please review it!!
