### ISSUE TITLE
Add Machine "box style" boundary

### ISSUE THREAD

**Issue by storkinsj** [OWASP/threat-dragon#54]
**Describe what problem your feature request solves**
It is often useful to draw machine boundaries which simplify drawing tons of trust boundaries when the machine boundary is appropriate.
**Describe the solution you'd like**
A simple box tool that drags to draw 4 lines which act as trust boundaries is Very useful. I find myself drawing those all the time.

**Additional context**
With the lack of copy and paste of screen elements, Drawing a simple box takes time and effort and the four lines need to be drawn again and again.  A box around multiple processes is extremely common and useful for threat modeling.

**Comment by jgadsden** [comment]
Hello @storkinsj - agreed, this would be very good to have. I think it is possible to implement this within our version of JointJS (the free to use version). Did you want to transfer this issue to the Threat Dragon core repo? This is where the work would be carried out, which could be done for version 1.4 :

https://github.com/OWASP/threat-dragon-core/issues

thanks again for the good suggestion

**Comment by lreading** [comment]
Here is the implementation we have for 2.0.  Please leave any feedback here. :) 

![Screenshot from 2021-06-21 10-35-50](https://user-images.githubusercontent.com/5851985/122780101-82f7fd00-d27c-11eb-92ae-694590d2a3ab.png)

**Comment by jgadsden** [comment]
This looks very good to me - nice to have a choice.
Boundaries are the 'strange' component in that often we want to have no title; sometimes it is good to have a title, but usually they have an empty one. I guess the grey title bar for the square boundary will not be present if the title is empty?

**Comment by lreading** [comment]
Great point about the title. I'm inclined to remove the background for the title entirely.  The only question is if that is the right spot for the text field?  Though, we will have arbitrary text fields / labels in 2.0, so if a user wanted it somewhere else, they could just add one manually.

**Comment by jgadsden** [comment]
Sounds like a good solution, having a transparent background to the text. To me that is the right place for the text field, so I would keep that as it stands ... until we get complaints of course ;-)

**Comment by storkinsj** [comment]
-I love the location for the box label
-Location for single line boundary is also excellent.

Sorry- no negative feedback for you on this one- thank you!!

**Comment by lreading** [comment]
Closing as this is complete in v2
