### ISSUE TITLE
Github responses only include 30 repos/branches

### ISSUE THREAD

**Issue by danielpops** [OWASP/threat-dragon#547]
**Describe the bug**
The github api by default only returns 30 items for repos, branches, etc. the threatdragon UI to choose a repo or branch is limited to the first 30 and there is no paging or option to pull the remaining items. 

**Expected behaviour**
All items should be returned, or the UI should expose some "next/prev" links to navigate through the pages of results. 

**To Reproduce**
Connect to a user/org with more than 30 repos or a repo with more than 30 branches.

**Comment by jgadsden** [comment]
assigning to @SilverC
