### ISSUE TITLE
Add open framework base on Threat Modeling Manifesto

### ISSUE THREAD

**Issue by iman4000** [OWASP/threat-dragon#549]
**Describe what problem your feature request solves**
All frameworks have limitations and we have problem with it and this makes us to use multiple frameworks for having all sides and threats. so we decide to follow `Threat Modeling Manifesto` and combine some frameworks.

**Describe the solution you'd like**
Add one more framework beside STRIDE/CIA/LINDDUN like `Manifasto` with principle of [Threat Modeling Manifesto](https://www.threatmodelingmanifesto.org/) to make user free for choosing how and what parameter from which framework he/she wants to add

**Comment by iman4000** [comment]
Hello @jgadsden choosing any of these three frameworks is possible right now as I understand correctly!
I want the forth framework which is flexible to put anything I want. let me provide a small example:
one frame work that I can add PASTA and STRIDE perspective for one element together and for another element in my diagram I need to combine OCTAVE and DREAD together....

something like this feature I meant for

**Comment by jgadsden** [comment]
Cool, thanks @iman4000 , I now understand 
So if you could add an entirely free-form threat then that would do what you want? You could edit the type etc to whatever text you like?

**Comment by iman4000** [comment]
yeah! something like what you said :D
and it has some free-form text fields that we can add our perspectives! maybe we should think about these fields but it is really cool as far as I know 💯

**Comment by iman4000** [comment]
Is there anything that I can do about this issue @jgadsden ?

**Comment by jgadsden** [comment]
Can you provide the code changes for this @iman4000 ? 
Note that if the diagram is 'Generic' then you can choose any of STRIDE, LINDDUN and CIA categories. Do you need extra categories on top of these?

**Comment by jgadsden** [comment]
this can be achieved using the 'Generic' diagram type, so we an close this issue now
