### ISSUE TITLE
Provide diagram description

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#553]
**Describe what problem your feature request solves**
When using multi-diagram threat models, it is not obvious which diagram is which. They have titles but this is the briefest of information

**Describe the solution you'd like**
It would be good to have a short description for each diagram, so that on the main threat model page it is obvious which diagram is associated with which activity.

**Additional context**
The thumbnails are not informative - they do not correspond to the data flow diagrams, and can be misleading. Consider replacing the thumbnails with descriptive text

**Comment by jgadsden** [comment]
Thanks for taking this on @mariuslihet - I will add you as a contributor

**Comment by mariuslihet** [comment]
> Thanks for taking this on @mariuslihet - I will add you as a contributor

It was my pleasure. If you could add me as a contributor I would really appreciate it.
If you need anything else, just let me know!
