### ISSUE TITLE
I18N: add Hindi translation file

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#558]
**Describe what problem your feature request solves**
It would be good to have the Hindi translation for Threat Dragon

**Describe the solution you'd like**
Modify [translation file](https://github.com/OWASP/threat-dragon/blob/main/td.vue/src/i18n/hin.js)

**Additional context**

**Comment by jgadsden** [comment]
Hello @professorabhay , the translation file is in place so this is now all yours. Thank you for offering to do this translation

**Comment by professorabhay** [comment]
Hello @jgadsden, Thanks for the help. I'll raise PR soon !!
