### ISSUE TITLE
Warning during Windows installation

### ISSUE THREAD

**Issue by maarre** [OWASP/threat-dragon#564]
**Describe the bug**

Windows warns when installing. You have to choose "install anyways" or something like it. I cannot reproduce by uninstalling and reinstalling.
**Expected behaviour**

Install without any warnings.
**Environment**
 - Version: (e.g. 1.3.1) 1.6.1
 - Platform: (Web App / Desktop App) Desktop
 - OS: (MacOS / Windows / Linux) Windows 10
 - Browser: (e.g. chrome, firefox, safari)

**To Reproduce**

**Any additional context, screenshots, etc**

**Comment by maclovin** [comment]
I think this kind of warning is pretty common in any electron application.

**Comment by jgadsden** [comment]
Hello @maarre , I have added a [wiki entry](https://github.com/OWASP/threat-dragon/wiki/FAQs#why-do-i-get-owasp-threat-dragon-setup-isnt-commonly-downloaded-warnings-after-downloading-on-windows) and also an entry in the Threat Dragon documentation

**Comment by storkinsj** [comment]
it is not just an innocuous warning it’s an important security feature.

you may be blocking some security teams from using it in certain locked down environments.

A friend of mine presented a DEFCON a few years ago and showed the electron abs could be totally tampered with and they fixed electron to sign the JavaScript

>

**Comment by jgadsden** [comment]
Understood @storkinsj , it is the best we can do for now for Threat Dragon. We notarize the MacOS images but have not gone down the similar route for Windows images.

**Comment by jgadsden** [comment]
@maarre I have also updated the online documentation at : https://threatdragon.github.io/install-desktop/

If this looks OK to you then feel free to close this issue, thanks for raising it

**Comment by maarre** [comment]
@storkinsj can you formulate a feature request? I am closing this issue
