### ISSUE TITLE
Copy and Paste Objects

### ISSUE THREAD

**Issue by storkinsj** [OWASP/threat-dragon#57]
**Describe what problem your feature request solves**
It is quite common when threat modeling (using other tools) to copy a set of objects to another "occurrance" to show a repeating pattern.  There is no way today to select one or more objects and copy it. This is extremely useful when you have taken pains to draw something like the missing "machine boundary" feature using 4 trust boundaries. Instead you must draw another 4 lines in order to do that, repeating the labels, etc.

**Describe the solution you'd like**
The tool should work the way standard objecte editors such as MS SDL threat modeling tool, Visio, draw.io, Adobe Illustrator works: 
1) Mouse Down begins Dragging a rectangle once the cursor is moving; rectangle uses origin and current mouse pointer as opposite points of rectangle
2) Objects under rectangle bold or change color to show them being selected in real time so that user can properly adjust the size of the rectangle to exactly copy all the objects 
3) Platform specific copy command (Command or control-C) puts all objects and relative distance into the clipboard for pasting
4) Paste command ignores mouse, but pastes an exact copy which is offset in X and Y to allow the user to find the objects relative to the originals.
5) All objects remain selected for mouse grab and move as one; optionally using arrow keys could move the group as well
6) Clicking the mouse away from any of the objects deselects all objects.

You have now copied and pasted a selection of graphic objects.
More powerful editors such as Illustrator have grouping features too; however, simple copy and paste is extremely useful. Even if we only do one object.

**Additional context**
Some recent objects with multiple entities I have had to redraw painfully one element at a time:
-Hypervisors
-Network Switches
-Kubernetes Pods
etc.

**Comment by jgadsden** [comment]
Hello @storkinsj - another very good suggestion, it would be great to be able to select multiple elements and then copy / drag / delete etc, all the usual stuff we should expect.
We have a lot of difficulty with doing this, we use the free-to-use version of JointJS which is very restricted in this area. @andk123 did some good work with the 'duplicate' button, but we are hampered by what JointJS provides us.

We are migrating the drawing package to mxgraph, and this will give us these features out of the box, and this is planned for Threat Dragon version 2.0 late this year.

This is an excellent suggestion, and may be worth adding this suggestion to the Threat Dragon core repo where this sort of suggestion is being collected: https://github.com/OWASP/threat-dragon-core/issues

It is linked to but does not duplicate: https://github.com/OWASP/threat-dragon-core/issues/59

**Comment by lreading** [comment]
Closing as this is complete in v2
