### ISSUE TITLE
First diagram overwritten when creating multiple diagrams

### ISSUE THREAD

**Issue by IchGehSteil** [OWASP/threat-dragon#582]
**Describe the bug**
When creating and editing multiple diagrams in one threat model after saving, the diagram on the first index is always overwritten.

**Expected behaviour**
When editing the second, third, forth, etc.. diagram and saving, the diagram on the first index should not be overwritten.

**Environment**
 - Version: 2.0.0
 - Platform: https://www.threatdragon.com/ and web app built with pnpm
 - OS: Linux
 - Browser: chrome and edge

**To Reproduce**
1. Create a threat model with three diagrams (first, second, third)
2. Edit first diagram (add a process)
3. Save and return to overview with "close"
4. Edit second diagram (add process and actor)
5. Save and return to overview with "close"
6. Observe, the first diagram was overwritten with second. Second exists twice
7. Edit third diagram (add two processes and actor)
8. Save and close
9. Observe, second diagram was overwritten with third. Two third and one second exist

**Comment by jgadsden** [comment]
Ah, thanks for this @IchGehSteil - this is a very serious bug, I have just reproduced it.
We were going to beta release this week, so I can try and fix it before then. Otherwise we will delay beta release to make sure this is fixed

**Comment by IchGehSteil** [comment]
@jgadsden I was struggling to replicate the bug, but managed. 
Do this: 
1. Create a new project
2. Add a diagram called "first"
3. Use the "duplicate" function
4. Try to rename the copy -> Observe the name of both diagram change
5. Save and close
6. Edit Project again and rename the copy again -> Only one diagram will rename
7. Save and close
8. Edit the copied diagram
9. Save and close the diagram
10. Observe the copy has overwritten the original

Tested in Google Chrome

**Comment by jgadsden** [comment]
Hello @IchGehSteil , many thanks for finding this, it is a new bug introduced when the duplicate diagram feature was implemented
do you want to raise a new bug report for this? If not then I am happy to raise the bug report
