### ISSUE TITLE
Documentation for running the built docker image

### ISSUE THREAD

**Issue by vineetpandey** [OWASP/threat-dragon#586]
**Describe the bug**

Downloaded the beta release source and build the docker image. While running the image, got the syntax error.

**Expected behaviour**

Expected to run the docker image smoothly 

**Environment**
 - Version: [Beta Version 2.0.0](https://github.com/OWASP/threat-dragon/releases/tag/v2.0.0-beta)
 - Platform: Web App
 - OS: Windows 
 - Browser: chrome

**To Reproduce**

- docker build -t owasp-threat-dragon:dev .
- docker run -it --rm -p 8000:3000 -v %CD%/.env:/app/.env owasp-threat-dragon:dev
- Got the error
- td.server/index.js: line 1: syntax error: unexpected "("

**Any additional context, screenshots, etc**

**Comment by jgadsden** [comment]
Thanks @vineetpandey , the bug is much appreciated. If you have a fix then that would be great

**Comment by jgadsden** [comment]
OK, thanks @vineetpandey 
It works OK on my MacOS - I can will it on my Linux and my Windows machines later this week

**Comment by vineetpandey** [comment]
Great @jgadsden .
If that works for windows. Please state away the steps as well please. Thanks!

**Comment by vineetpandey** [comment]
Was this beta published on docker hub as well?
I was checking it but couldn't find on docker hub. Though I'll give a try. Thanks for the information @jgadsden

**Comment by vineetpandey** [comment]
@jgadsden looks like this docker image is working fine. Though I'll check it thoroughly tomorrow. Thanks for this.

**Comment by vineetpandey** [comment]
@jgadsden : now able to run from docker image but another trouble came up while returning the oauth code.
Below are the environment variables passed in .env file:
GITHUB_CLIENT_ID=Iv.1854ce0c2e723a
GITHUB_CLIENT_SECRET=esdf3423432423463453rfwe
GITHUB_SCOPE=repo

NODE_ENV=development
SERVER_API_PROTOCOL=http

ENCRYPTION_KEYS='[{"isPrimary": true, "id": 0, "value": "sdfsdfs4erw45345345"}]'
ENCRYPTION_JWT_SIGNING_KEY=sdfsdfs4erw45345345
ENCRYPTION_JWT_REFRESH_SIGNING_KEY=sdfsf5434r4fd4erf34dre34
-------------------------------------------------------------------------------------
And, this is the error while clicking on "Login with Github"
![image](https://user-images.githubusercontent.com/3475982/213742993-978524f5-bff1-4635-bf59-e689c40c71f6.png)

**Comment by jgadsden** [comment]
Hello @vineetpandey 

If you are running these commands:

```
docker pull threatdragon/owasp-threat-dragon:v2.0.0-beta
docker run -it --rm -p 8080:3000 -v %CD%/.env:/app/.env threatdragon/owasp-threat-dragon:v2.0.0-beta
```
then you are mapping for port 8080 on your localhost, so you should try http://localhost:8080/#/

The backend Express server is listening on port 3000 for requests from the Vue application front end or from the browser - but these requests are mapped to port 8080

**Comment by vineetpandey** [comment]
Hi @jgadsden : yes, I ran this URL only: http://localhost:8080/#/
while clicking on "Login with Github", let me authorize and throwing the error as shown in the image attached in my last comment. Not sure what to do, since my Github app configuration is:
HomePage URL: http://localhost:8080
Callback URL: http://localhost:3000/api/oauth/return
Also, I gave my discord webhook as well.

**Comment by vineetpandey** [comment]
Hi @jgadsden : had a chance to look into the above error?? 
Thanks!

**Comment by jgadsden** [comment]
Hello @vineetpandey sorry for the delay - been busy times
can you check your dotenv value for SERVER_API_PROTOCOL? If it is https then this will fail because the certificates are (probably) not in place

**Comment by jgadsden** [comment]
Hello @vineetpandey , I think I need to create a step by step guide to running the docker image locally, and that should show any errors. I can put the step by step guide onto the documentation site

**Comment by jgadsden** [comment]
Hello @vineetpandey I have created instructions for github access, which include running the docker image locally, in the documentation [pull request](https://github.com/OWASP/www-project-threat-dragon/pull/71)

**Comment by vineetpandey** [comment]
@jgadsden thanks for this.

One more query, can we also run this in gitlab. If yes, then can you also include the step-by-step instructions for **gitlab** deployment since gitlab is popular alike GitHub and gives you the feasibility to host it on-premise which large organisations do prefer.
