### ISSUE TITLE
401 on doc access

### ISSUE THREAD

**Issue by sparticvs** [OWASP/threat-dragon#587]
**Describe the bug**
Navigating to https://www.threatdragon.com/docs/development/env.html results in a 401.

**Expected behaviour**
Docs page to load

**Environment**
 - Version: N/A
 - Platform: Website (not TD Web App)
 - OS: RHEL
 - Browser: Chrome

**To Reproduce**
Use incognito to navigate to https://www.threatdragon.com/docs/development/env.html

**Any additional context, screenshots, etc**
Response:
```
{"status":401,"message":"Unauthorized","details":"You must login to continue"}
```

**Comment by jgadsden** [comment]
Many thanks for this @sparticvs - and indeed this link is broken. It is due to a recent change of name for this page to :
https://www.threatdragon.com/docs/development/environment.html

I will apply a fix for this so that www.threatdragon.com/docs/ will work again
