### ISSUE TITLE
Scan docs for broken links

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#589]
**Describe what problem your feature request solves**
We recently had some broken links on the docs pages, and this was not picked up by the CI pipeline

**Describe the solution you'd like**
Scan for broken links on merge to main branch

**Additional context**

**Comment by jgadsden** [comment]
Probably uses Lychee as a github action:
https://github.com/marketplace/actions/lychee-broken-link-checker

A good example is here:
https://clementbm.github.io/coding/2020/05/31/automatically-validate-links-on-jekyll-website.html

**Comment by xsankalp13** [comment]
Hey there
It would be an honour to work on this issue
If it is still available, I'd be glad to work on it

**Comment by jgadsden** [comment]
added lychee with commit
fund some broken links and corrected them with commit ff9c1bbf61a1e5f4ce448d44d048c2e78c9d56f2
lychee scans daily so this should flag up any future broken links
