### ISSUE TITLE
Different browser widths cause misformating of the report

### ISSUE THREAD

**Issue by ChristopherHackett** [OWASP/threat-dragon#598]
**Describe the bug**
Different browser widths cause misformating of the report. As the width is reduced parts of the top of initial section of the report are obstructed. 

**Expected behaviour**
Elements should format correctly and not be obstructed 

**Environment**
 - Version: v2.0.0-beta
 - Platform: Web App
 - OS: MacOS
 - Browser: Firefox 109.0.1 (64-bit)

 **To Reproduce**
1. Visit https://www.threatdragon.com/#/dashboard
2. Click "Explore a sample threat model"
3. Click "Demo Threat Model"
4. Click "Report"
5. Adjust the width of the browser window 

**Any additional context, screenshots, etc**
![image](https://user-images.githubusercontent.com/1075126/218320280-f27ee0b1-88ac-4291-bc57-61d133c3fe21.png)
![image](https://user-images.githubusercontent.com/1075126/218320295-81a279e7-5836-44ed-9c2d-0268b775e81d.png)
![image](https://user-images.githubusercontent.com/1075126/218320303-b37b1c19-4db3-4497-a9ac-a09c9bd61122.png)
![image](https://user-images.githubusercontent.com/1075126/218320313-e8e5422b-da74-4d26-86f8-fa22aa807f46.png)

**Comment by jgadsden** [comment]
Thanks for this issue @ChristopherHackett , do you have a fix for this? Any contributions welcome
