### ISSUE TITLE
Error: Invalid key length at new Cipheriv (crypto.js:219:16)

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#6]
This issue has been migrated from : 
https://github.com/mike-goodwin/owasp-threat-dragon/issues/74
and was opened by @anirbanctts : 

Keep on getting this error after entering github credentials.
Error: Invalid key length     
at new Cipheriv (crypto.js:219:16)
at Object.createCipheriv (crypto.js:619:10)
at encryptData
....

var crypto = require('crypto');
var inputEncoding = 'ascii';
var outputEncoding = 'base64';
var keyEncoding = 'ascii';
var algorithm = 'aes256';

these properties were unchanged. Not sure why this issue keeps on repeating.
using NodeJS 8.11.3 LTS version

**Comment by omerlh** [comment]
Found the solution - generate the key using the following command:
```
openssl rand 16 -hex
```

**Comment by jgadsden** [comment]
Hello @omerlh - thanks for the suggestion, and the issue does seem to be the key has been copied into the environment variables incorrectly. 
@anirbanctts if you come across this problem again could you see if the environment variables are set up as in the readme:
https://github.com/OWASP/threat-dragon#environment-variables

This issue can be closed
