### ISSUE TITLE
Make GitHub OAuth integration optional

### ISSUE THREAD

**Issue by tomdottom** [OWASP/threat-dragon#629]
**Describe what problem your feature request solves**

I would like to deploy a local _production_ version without configuring Github OAuth.

**Describe the solution you'd like**
Maybe a simple flag or env var to turn the Github integration on/off,

**Comment by jgadsden** [comment]
A very good suggestion, thanks @tomdottom

**Comment by jgadsden** [comment]
moving to version 2.2 because no work on this issue yet

**Comment by steve-winter** [comment]
@jgadsden - Can I confirm the intent:

- Deploy the web app locally without requiring login.

1. Is the desire to utilise Github as a repo via application keys or utilise another storage mechanism? 

Suspect I can pick this one up once I understand the requirement.

**Comment by jgadsden** [comment]
Rereading this issue, I am not sure what the change in functionality is needed, @tomdottom could you provide more detail?

**Comment by steve-winter** [comment]
@tomdottom do you have any more info on what you are expecting?

**Comment by jgadsden** [comment]
Taking this issue on - I think the solution is to make sure that if no GitHub, GitLab or Bitbucket env vars are set then the web app works but with just local login as an option. I think it does, but this needs confirmation

**Comment by jgadsden** [comment]
provided in update to documentation commit [d11919a](https://github.com/OWASP/www-project-threat-dragon/commit/d11919adf1c96b58383dc754dfd24e3d6ffd07ff)
