### ISSUE TITLE
Docs: Add usage of dotenv to load environment variables

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#65]
**Describe what problem your feature request solves**
usage of dotenv to load environment variables needs to be added to the Docs branch , functionality added by #62 

**Describe the solution you'd like**
section in docs expanded for this use

**Additional context**

**Comment by lreading** [comment]
I'm happy to take this as well, though I don't see a docs branch.  I did find https://github.com/threatdragon/threatdragon.github.io

Is that the correct place to update and submit a PR?

**Comment by jgadsden** [comment]
Thanks @lreading , indeed the docs are in that repo.

The threat  dragon project structure is : 
Web application at : OWASP/threat-dragon
Desktop application at : OWASP/threat-dragon-desktop
Both desktop and web app rely on common files held in :  OWASP/threat-dragon-core
Docs at : threatdragon/threatdragon.github.io

This has become a bit confusing over the years, so the structure of version 2.0 will be simplified:
- Threat dragon project contains all necessary files so no longer a core repo
- Docs a sub project of threat dragon project
- Desktop application an electron shell around threat dragon project

**Comment by lreading** [comment]
Thanks for the helpful info! 
I believe this is closed by https://github.com/threatdragon/threatdragon.github.io/pull/19
