### ISSUE TITLE
Out of Scope Threats not in PDF Report (v2.0.2)

### ISSUE THREAD

**Issue by RQQDawg** [OWASP/threat-dragon#659]
**Describe the bug**
When trying to generate a pdf report and having show out-of scope threats checked, the pdf report that is created does not include the out of scope threats. This occurs in version 2.0.2 of the tool.

**Expected behaviour**
That the pdf report will list which threats are out of scope and provide the justification for why.

**Environment**
 - Version: 2.0.2
 - Platform: Desktop App
 - OS:  Windows/ Mac

**To Reproduce**
Save PDF with show out of scope threats checked

**Any additional context, screenshots, etc**

N/A

**Comment by jgadsden** [comment]
Thanks @RQQDawg , I will prioritise this for version 2.1

**Comment by jgadsden** [comment]
Looking at this further, I can add the threats for out of scope elements into the report OK:
[new-model.pdf](https://github.com/OWASP/threat-dragon/files/11523760/new-model.pdf)

@RQQDawg can you provide your JSON file (compressed)? Here is the file I used:
[new-model.json.zip](https://github.com/OWASP/threat-dragon/files/11523761/new-model.json.zip)

**Comment by jgadsden** [comment]
Closing this issue as I can not reproduce it - I can reopen it @RQQDawg if you can provide the `json` file that shows this?

**Comment by jgadsden** [comment]
This may be related to a new issue that asks for out of scope diagram elements to be shown, even if they have not threats associated with them ('mitigated' / 'unmitigated' or 'in scope' / 'out of scope')
