### ISSUE TITLE
Investigate dependabot security alerts

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#665]
**Describe the bug**
There are outstanding security alerts at https://github.com/OWASP/threat-dragon/security/dependabot

**Expected behaviour**
would be nice to clean these up

**Environment**
 - Version: 2.0.2
 - Platform: both Web App / Desktop App
 - OS: all MacOS / Windows / Linux
 - Browser: all chrome, firefox, safari

**To Reproduce**

**Any additional context, screenshots, etc**

**Comment by jgadsden** [comment]
updating `got` stopped tests running and was reverted in 2414d095a2fcb5389e2b8a78c1981e4c06a9333c

**Comment by professorabhay** [comment]
Hey @jgadsden, I just checked it out.
Do I just have to dismiss these alerts because as you said that all changes are reverted ?

**Comment by jgadsden** [comment]
Yes, good point @professorabhay  - ignore these alerts
It may be that the test packages have been updated and we can upversion `got`, but this needs investigation

**Comment by professorabhay** [comment]
Hey @jgadsden, I just take a look to `package-lock.json` file as per the [Dependabot alerts](https://github.com/OWASP/threat-dragon/security/dependabot) [#93](https://github.com/OWASP/threat-dragon/security/dependabot/93) of SSRF in Requests and found that is requesting that older version - 
![image](https://github.com/OWASP/threat-dragon/assets/76243309/922833fd-9c0a-4c00-a1f0-16662da08044)
We need to update it in the file. So, that the error resolve.

**Comment by jgadsden** [comment]
dismissed the dependabot alerts because there is nothing we can do about `request` and `got`
