### ISSUE TITLE
New Data Flow does not show property editor

### ISSUE THREAD

**Issue by deniskrizanovic** [OWASP/threat-dragon#666]
**Describe the bug**
When creating a new data flow between two other components, I am not provided the ability to edit the properties, like for example Name, or threats or whatever. I can edit the properties on the demo diagrams. But when I add a new flow to the demo diagram the property editor does not appear then either.

When modifying the name attribute in the underlying json, I still don't see it in the editor, or the generated pdf.

**Expected behaviour**
To be able to edit the flow propertiers

**Environment**
v2.02
mac

**To Reproduce**

**Any additional context, screenshots, etc**
![image](https://github.com/OWASP/threat-dragon/assets/899331/74b94ae4-8983-43b9-994e-b2801849a67e)

**Comment by deniskrizanovic** [comment]
I figured it out! If you click the arrow of the data flow, it will bring it up.. Very tricky.. And I didn't find that instruction in the doco either.

**Comment by jgadsden** [comment]
Leaving this open as a priority, because it is _really_ awkward to select a dataflow
