### ISSUE TITLE
Make it easier to select a data flow

### ISSUE THREAD

**Issue by ecobux** [OWASP/threat-dragon#687]
**Describe what problem your feature request solves**:

The problem is currently that clicking on the line creates a new point (black disk) to change the curve. In order to select a data flow, you have to click on the head of the arrow, which often requires several attempts with the Undo function.

**Describe the solution you'd like**:

Usually you select items by a single click. For creating a new point you could therefore assign the double-click event.

**Additional context**:

Experienced on the desktop app.

**Comment by jgadsden** [comment]
Thanks @ecobux , this makes a lot of sense
We can try and prioritize it for version 2.1

**Comment by jgadsden** [comment]
This is probably related to #666

**Comment by exoosh** [comment]
I'm still seeing this with 2.2.0
