### ISSUE TITLE
Save dialog of desktop app suggests extension with two dots for PDFs

### ISSUE THREAD

**Issue by ecobux** [OWASP/threat-dragon#689]
**Describe the bug**:

When saving a PDF report, the file dialog suggests files with the extension `*..pdf`, resulting in an empty list of existing PDFs.

![image](https://github.com/OWASP/threat-dragon/assets/1910838/00f06bd2-c98a-4a62-b8f3-4e174a847c21)

**Expected behaviour**:

It should be `*.pdf`.

**Environment**:

- Version: (2.0.2)
- Platform: (Desktop App)
- OS: (Windows)

**To Reproduce**:

1. open or create a threat model
2. menu: File > Save PDF
3. button: Save PDF

**Comment by jgadsden** [comment]
Thanks for catching this @ecobux 
Do you want to create this fix? Or I can do this if you like

**Comment by ecobux** [comment]
Please do. It would take some time to set up a development environment and get acquainted with the code.
