### ISSUE TITLE
Update Packages

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#70]
**Describe what problem your feature request solves**
`npm audit` reports 26 vulnerabilities (7 low, 6 moderate, 11 high, 2 critical).  

**Describe the solution you'd like**
Update the dependencies as necessary to remove known vulnerabilities.

**Additional context**
It might make sense to manually audit the package.json file and remove any unused dependencies and scripts while looking at this.

**Comment by jgadsden** [comment]
Yes, this is a good thing to do for sure. The main problem is the JointJS package - when I last tried updating to something like 3.x it was too big a breaking change for me ... and we want to swap this out for [mxgraph](https://github.com/jsGraph/mxgraph) anyway.

Other than JointJS I agree there are quite a few dependencies that need looking at.

**Comment by lreading** [comment]
Great to know, thanks for the info! There's some packages hanging around from what appears to be legacy code that can be removed that will reduce the threat landscape as well.  Even if we don't get it down to 0 vulnerabilities, I think it's still worth the effort.

**Comment by lreading** [comment]
There was a major rewrite to `npm audit` not too long ago.  Since the docker container is pointing to node version 14, I think it makes sense to use this version when conducting the audit.  We actually get different results and not just a different format with audit when using the LTS.  Node 14 is EOL in 2023, so we have a bit of time before this becomes an issue.

I'll likely make another issue involving the docker container and build process to solidify this so it's consistent.  Additionally, the future rewrite will resolve some of these issues and we may move to a different version of node by then.

**Comment by jgadsden** [comment]
As you have the package.json open, and at the risk of adding to your task, I liked your suggestion of [splitting the shared package.json](https://github.com/OWASP/threat-dragon/discussions/69#discussioncomment-660564) out to frontend and backend. Did you want to consider this for this issue, or should that be another issue?

**Comment by lreading** [comment]
I like that idea. This will involve some changes to the Dockerfile as well.  At the risk of scope creep, I'll likely update it to ensure it's not using the root user, remove apt lists, limit `su` use, etc etc. 

I'm still going back and forth on my comment about Node versions.  I need to research how the npm dependency graph works between different versions of node/npm... It may make more sense to keep it on a newer version? Open to suggestions and discussion!

**Comment by lreading** [comment]
After exploring for a bit, I'll open separate issues for migrating the package.json for both back-end and front-end.  This will be a non-trivial task since the build process will need to be changed and updated quite a bit.

**Comment by lreading** [comment]
Updating Karma to the latest version would resolve many of these.  Where Karma is a dev dependency and not deployed, I am less concerned with this.  It is a breaking change and a non-trivial fix.

rework (rework-npm-cli) was last published 4 years ago and will likely be removed with #74 

As mentioned above, jointjs is a common issue as well that will be addressed with v2.0

There are a handful of other dependencies from owasp-threat-drgaon-core that could be addressed in that repo.

Pug is another library at risk that hasn't had recent updates and will be addressed in the v2.0 rewrite when the front-end is rewritten.

There are no packages that we can update to reduce the number of vulnerabilities without significant rewrite, which is already planned.  I'll be closing this issue.  

If anyone disagrees, please feel free to comment and/or reopen.
