### ISSUE TITLE
Unhandled exception breaks the app

### ISSUE THREAD

**Issue by brandon-edmunds** [OWASP/threat-dragon#71]
**Describe the bug**
When attempting to login to the web application, the following error is produced: 
```
    var primaryKey = keys.find(function(key) { return key.isPrimary; });
                          ^

TypeError: keys.find is not a function
    at getPrimaryKey (/app/td/helpers/encryption.helper.js:18:27)
    at /app/td/helpers/encryption.helper.js:60:19
    at AsyncWrap.<anonymous> (/app/td/helpers/encryption.helper.js:11:9)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:64:14)

```
**Expected behavior**
Not sure if the issue is on my side, doesn't seem like this file was touched in recent commits?

**Environment**
 - Version: Latest Commit: 59f2a1f4bc05b8fe41394a907f18e3c14543fa48
 - Platform: Web App
 - OS: Docker
 - Browser: Chrome
**To Reproduce**
1. Pull git
2. Set .env file
3. Docker Build
`docker build -t owasp-threat-dragon:dev .`
4. Docker Run 
`docker run -ti -p3000:3000 --env-file ./.env  owasp-threat-dragon:dev`

From here, I can browse to my local host, hit the login, and the app crashes with the posted error.

**Comment by lreading** [comment]
Currently there's no .dockerignore file present, so your `.env` file should be getting copied into the docker image.  This is not ideal and will be addressed in the future, but you probably don't need the `--env-file` flag.  When I run it without that flag, it works as expected.  Running it with that flag I actually get a different error:

```
TokenError: The client_id and/or client_secret passed are incorrect.
    at Strategy.OAuth2Strategy.parseErrorResponse (/app/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /app/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /app/node_modules/passport-github/lib/strategy.js:77:16
    at /app/node_modules/oauth/lib/oauth2.js:209:7
    at passBackControl (/app/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
As a temporary workaround, I would recommend mounting the .env file in the container.  We should consider this use-case though, as well as docker-secrets and k8s deployments.
`docker run -ti -p3000:3000 -v $(pwd)/.env:/app/td.server/.env owasp-threat-dragon:dev`

**Comment by brandon-edmunds** [comment]
Perfect! This worked! 

Do you want me to open a feature request for secret handling?

**Comment by lreading** [comment]
Yes, that'd be great, please!
I'll open a PR to include documentation in the readme about how to build/run the docker container for the interim.  Thanks for raising the issue!

**Comment by brandon-edmunds** [comment]
No problem, I'll close this one and open a feature request. Thanks for the quick response!
