### ISSUE TITLE
Better Secret Handling for  Docker Instance

### ISSUE THREAD

**Issue by brandon-edmunds** [OWASP/threat-dragon#73]
**Describe what problem your feature request solves**
For running the web application in Docker, the secret handling is not ideal. What happens is either your secrets are coded into the image, or have to be mounted by a volume. 

**Describe the solution you'd like**
- Utilize Docker Secrets
- Consider Use-cases for various builds (i.e. local docker, vs. Cloud)
- Consider Cloud-based solutions (e.g. AWS Secret Manager or Secure Parameter Store

**Additional context**
See: [https://github.com/OWASP/threat-dragon/issues/71](https://github.com/OWASP/threat-dragon/issues/71)

**Comment by lreading** [comment]
I'm wondering if it'd make sense to have a configuration abstraction later.  

What I'm thinking is some class that defines all of the environment variables and attempts to read them from whatever configuration provider is available, eg environment variables or from a file for docker secrets or similar.

Another benefit would be that we would have all possible environment variables / configuration options listed in a single place, and help us avoid things like #95

**Comment by jgadsden** [comment]
Yes, good point, and the configuration is set to become more complicated as we add : 

- gitlab
- Google Drive
- OneDrive
- Dropbox
- along with local filesystem device (but only  for desktop app?)

So this needs some thinking through. Maybe should have a look at what draw.io does here.

**Comment by lreading** [comment]
I have a few thoughts on this, but I think it'd make sense to wait for #94 to get across the line.

There's a few different types of configuration that I can see happening:
1. local development/deployment (environment variables, dotenv or env-file)
2. k8s deployment (could probably wrangle a secret into a dotenv format, but much easier as environment variables)
3. Docker swarm - Either mount a volume with a .env file, or create secrets and have the configuration be able to read from other files
4. Manual deployment on a webserver (can use .env or environment variables)

I think with the number of secrets, it would make sense to continue supporting both file and environment variable based secrets. I have a few rough ideas on how we could accomplish that.  A very hand-wavy idea would be to have a config class that's responsible for gathering all of the different possible configs as well as handing out the config data when it's requested, and then we can have as many provider specific implementations as we want.

BaseConfiguration:
```
class BaseConfiguration {
    defaultConfigFile = '.env';

    configParams = [ 'PORT' ];

    config = {};

    constructor() {
        this.configDir = process.env.CONFIG_DIR || './.env`;
    }

    loadConfig() {
        this.config.github = loadGithubConfig();
        this.config.bitbucket = loadBitbucketConfig();
        // ... etc
    }

    _loadConfig() {
        configParams.forEach(param => {
            // Check if there's a .env file matching defaultConfigFile,
            // if so, load from that.  If not, try to load from process.env[param]
            // finally, use a default if there is one and assign it to this.confg
        });
    }

    getConfig() {
        return this.config;
    }
}
```

GithubConfig
```
class GithubConfig extends BaseConfiguration {
    defaultConfigFile = 'github.env';
    configParams = ['GITHUB_SCOPE', 'GITHUB_CLIENT_ID'];

    constructor() {
        super();
    }

    _loadConfig() {
        // anything that would be specific to just the github config
    }
}
```
