### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [OWASP/threat-dragon#740]
**Describe the bug**:
The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this

Screenshot
<img width="960" alt="Screenshot 2023-09-08 161423" src="https://github.com/OWASP/threat-dragon/assets/91591901/55b8af78-0515-4c57-8861-0c50f8e981cd">

**Expected behaviour**:
Twitter logo should be changed to X

**Environment**:

- Version: (e.g. 1.3.1)
- Platform: (Web App / Desktop App)
- OS: (MacOS / Windows / Linux)
- Browser: (e.g. chrome, firefox, safari)

**To Reproduce**:
Scroll to bottom and see twitter old logo

**Any additional context, screenshots, etc**:

@hwine 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by jgadsden** [comment]
Hello @lalitkumawat1m , thanks for noticing this, but that content is not supplied by Threat Dragon. Our project pages have content supplied by repo [www-project-threat-dragon](https://github.com/OWASP/www-project-threat-dragon), but the surrounding content is supplied by the OWASP organisation itself.
Not sure who to contact within OWASP, you could try the OWASP slack channel
