### ISSUE TITLE
Guard for unsaved changes

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#753]
**Describe what problem your feature request solves**:
At present it is possible to lose changes to a threat model via the logout button
Also if a new model is selected from Electron pull down menu then unsaved changes are lost

**Describe the solution you'd like**:
If the model has been modified, display pop-up to confirm the action

**Additional context**:

**Comment by AdityaRaimec22** [comment]
Hii @jgadsden I just want to know this org/repo will take part in GSOC-24 or not. Thanks!

**Comment by jgadsden** [comment]
No plans as yet to take part in GSOC this year @AdityaRaimec22
