### ISSUE TITLE
EL translation: Several menu items are not translated

### ISSUE THREAD

**Issue by kostasadriano** [OWASP/threat-dragon#776]
**Describe the bug**:
Several menu items, such as view, window, open recent, new model, etc are not translated.
In the i18n file, those items do not exist, so it is not possible to provide the translation.
See screenshot for Greek (el).

**Expected behaviour**:
All menu items and other strings should be translated.

**Environment**:

- Version: 2.1.1
- Platform: Desktop App
- OS: All

**To Reproduce**:
Open desktop app.
Choose a language other than English.

**Any additional context, screenshots, etc**:
![2023-11-03 09_38_22-OWASP Threat Dragon](https://github.com/OWASP/threat-dragon/assets/6406427/73878c1d-afc7-4b50-8557-8aaaa0a47d08)

**Comment by jgadsden** [comment]
Hello @kostasadriano , the greek translation has fallen behind, could you update it ?
the file that needs to be updated is: https://github.com/OWASP/threat-dragon/blob/main/td.vue/src/i18n/el.js
Many thanks!

**Comment by kostasadriano** [comment]
Hi, I created pr 777 with a few more translated strings.
Please note that Menu items View, Window, Edit are not available to translate in the *.js translation files. 
For this reason, they are not translated in any other language as well (see french for example).
The issue was not about only the Greek translation.

**Comment by jgadsden** [comment]
Yes, very good point @kostasadriano about the drop down menu items - these are roles within the desktop menu:

```
                { type: 'separator' },
                { role: 'close' }
```

and 

```
                {
                    role: 'recentdocuments',
                    submenu: [
                        { role: 'clearrecentdocuments' }
                    ]
                },
```

and I am not sure yet how to give them translation strings like the other entries
