### ISSUE TITLE
Bug: dataflow threat selection and properties wrongly applied to other nodes

### ISSUE THREAD

**Issue by jbaptistemariebio** [OWASP/threat-dragon#786]
**Describe the bug**:
When adding an actor to a diagram, the properties accessible for that component are not consisent. Sometimes there is a "Provides authentication" checkbox in the properties, sometimes its not here and replaced by the properties of data flow (Bidirectional, Out of Scope...)

**Expected behaviour**:
An actor should always has the actor properties ("Provide authentication")

**Environment**:

- Version: 2.1.1
- Platform: Desktop App
- OS: MacOS
- Browser: N/A

**To Reproduce**:
1. Add an actor to the diagram
2. Observe its properties

**Any additional context, screenshots, etc**:
![Capture d’écran 2023-11-15 à 11 44 16](https://github.com/OWASP/threat-dragon/assets/146077626/c740b3cc-6e73-4c13-8287-1c5f9f4a8501)

**Comment by TheComamba** [comment]
I also encounterered this behaviour, using the Desktop App on Windows. I think the behaviour *is* consistent, but wrong:

To reproduce:
* Add either a process, a store or an actor to the canvas.
* Ensure that this object is selected.
* Drag and drop a Data Flow on the canvas.
* The highlighted object is converted to a data flow (as evident from the presented checkboxes, but also from the json).

**Comment by jgadsden** [comment]
thanks @jbaptistemariebio and @TheComamba , I agree that if a diagram component is selected and then a data flow is added, the original component remains selected but the properties box shows the recently added dataflow - and this is confusing
This is behaviour inherited from the drawing package, and can probably be fixed using the event of adding a component provided by the drawing package?

**Comment by jgadsden** [comment]
it would be good to fix this for version 2.2, adding label

**Comment by jbaptistemariebio** [comment]
@jgadsden thanks for your feedback. I am afraid there is a misunderstanding in your comments. As you can see in the screenshot I posted, the actor element is selected (its name is properly displayed in the properties) but it does not have proper actor properties available. Unselecting it and reselecting it does not solve the issue, it will permanently keep those property fields.

**Comment by jgadsden** [comment]
yes agreed @jbaptistemariebio , thanks for pointing this out
a new dataflow is added when a node is double clicked, but then the node properties are overwritten with the properties of a data flow

**Comment by jgadsden** [comment]
Thanks to both @jbaptistemariebio and @TheComamba for making it clear what is going on:

If a diagram node is selected when a dataflow is added, data-flow attributes are wrongly applied to the selected node. This has the consequences that :

* the threat selection is wrongly truncated for the node
* the properties of the node are over written

this happens when either a dataflow is added by double click or when the dataflow is added from the pick area - all it needs is that a node is selected when a dataflow is added

**Comment by jgadsden** [comment]
I can take this one on, will work on it as a priority - target for version 2.1.2

**Comment by jgadsden** [comment]
@jbaptistemariebio and @TheComamba could you try out these new changes? They are now in the main branch

**Comment by jbaptistemariebio** [comment]
@jgadsden I am willing to test it. I know how to test a development version of the web application running it locally, but how can I test the desktop version? Is there an instruction to build a develoment version for desktop app?

**Comment by jgadsden** [comment]
if you have the main branch cloned to your local drive, then from the top directory:

```
npm install
npm run start:desktop
```

It will build and then run locally - many thanks @jbaptistemariebio for doing this 👍🏾

**Comment by jbaptistemariebio** [comment]
@jgadsden Just tested the desktop app, it now works properly. And it seems that previously created component having the issues have been corrected too, which is helpful.
Thanks

**Comment by jgadsden** [comment]
superb, thanks @jbaptistemariebio , and this will be included in release 2.1.2 - planned for this weekend
