### ISSUE TITLE
Reinstate automated generation of threats by element

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#792]
**Describe what problem your feature request solves**:
Version 1.x has a feature where the threats are suggested by element, for example if STRIDE:

```
STRIDE per element
          S | T | R | I | D | E
ACTOR   | X |   | X |   |   |
STORE   |   | X | X | X | X |
PROCESS | X | X | X | X | X | X
FLOW    |   | X |   | X | X |
```

**Describe the solution you'd like**:
Reinstate automated generation of threats by element

**Additional context**:

**Comment by ryeqb** [comment]
@jgadsden I'm curious, was this feature removed/deprecated in 2.x for any particular reason?

**Comment by jgadsden** [comment]
Well, only because we just did not have the engineering resource to implement it
Version 2.x is (almost) a complete rewrite of version 1.6.1, and some features we really wanted but could not get the time to do them - such as automated generation of threats by element
If you have some time to do this @ryeqb it would be very good to have

**Comment by ryeqb** [comment]
@jgadsden Im in the process of writing my bachelors thesis on templating threat models for IoT architectures and having had a quick look at Microsofts threat modeling tool, not having automated threat generation definitely stuck out. So did this the existing issue of non-existent templates given that's my thesis' goal https://github.com/OWASP/threat-dragon/issues/220

Hope I can help tacking both issues to some degree

**Comment by jgadsden** [comment]
Absolutely good to have any help you can on both these issues @ryeqb 
Say if you want me to assign an issue to you
Awesome degree thesis by the way 👍🏾

**Comment by itsdheerajdp** [comment]
@jgadsden I am surely work on this. Please assign me this.

**Comment by itsdheerajdp** [comment]
@jgadsden , to automate the generation of threats by elements , we can go for below approach i think
- We can define the elements of the system for which threat analysis is required. This could include actors, data stores, processes, data flows, etc.
- Then we can Implement the STRIDE methodology within the tool or script and Create a mapping between each element/component and the corresponding STRIDE threat categories.
- And then we can  Develop algorithms or rules within the tool/script to automatically generate threats for each element based on the mapped STRIDE categories

**Comment by jgadsden** [comment]
This is a Google Summer of Code project, and the application dates for GSoC contributors are between March 18th and April 2nd

**Comment by professorabhay** [comment]
Hi, @jgadsden! I am interested to contribute this issue under Gsoc. I am looking for some help from you to understand that issue deeply. So, that I can create an outline for the remedy. 🙂
As mentioned the `threats by element` functionality available in v1.x but not in 2.x!
I tried both the versions `2.2.0` and `1.6.1` - 
The difference I found is that - 

In version 2.2.0 -
![image](https://github.com/OWASP/threat-dragon/assets/76243309/b30fc30d-fcbd-45f3-aa7d-be6612885bc8)

In version 1.6.1 - 
![image](https://github.com/OWASP/threat-dragon/assets/76243309/e1c17ed1-67a1-419e-8b8f-c861452b8318)

Can you help me by providing more exposure to it, please?
