### ISSUE TITLE
Not able to setup locally this project

### ISSUE THREAD

**Issue by Rohit-Sharmaa** [OWASP/threat-dragon#795]
I am new to open source and i want not able to setup this project locally .
can someone help me with this 
@quine @hwine @DesHorsley @jeg1972 @sparticvs @

**Comment by jgadsden** [comment]
Hello @Rohit-Sharmaa - a good starting point is the install instructions in the [Threat Dragon documentation](https://owasp.org/www-project-threat-dragon/docs-2/install-desktop/)
