### ISSUE TITLE
Private github repositories are not listed in Github repo selection step

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#8]
This issue has been migrated from : 
https://github.com/mike-goodwin/owasp-threat-dragon/issues/119
and was opened by @rav94 : 

The repository was listed only after I changed the repository permissions to the public mode. Think this would be an important option to have because you are providing the Github credentials expecting to view your private repos as well. Plus people would be reluctant to put their threat model diagrams in public.

**Comment by FrankArchitect** [comment]
Definitely we can't make threat models publicly available, Threat Dragon needs to use a private repo.

**Comment by jgadsden** [comment]
Agreed @FrankArchitect that this is a limitation of TD, and should be changed as soon as we can. Dow you know what needs to be done with TD + github to provide this? Any suggestions welcome

The alternative is to use Threat Dragon desktop version on a locally cloned repo, and then commit+push back up to the private repo when required. I know this is not using the webapp, and is more awkward process, but it may help here.

The desktop release is at :
https://github.com/mike-goodwin/owasp-threat-dragon-desktop/releases/tag/v1.2

**Comment by jgadsden** [comment]
This has a comment from @hemedga https://github.com/mike-goodwin/owasp-threat-dragon/commit/305296d10fc1d310613f28503cc050ede802027b#commitcomment-40338515

"this commit was a good shot for threatdragon.org.

However, we are going to self-host it and we are going to use private repositories.
I suggest moving this to an environment variable i.e. process.env.GITHUB_REPO.
We're going to test it in our environment.:
