### ISSUE TITLE
irritating things with user interface

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#806]
**Describe what problem your feature request solves**:
Some irritating things with the user interface:

- (in progress) selecting the language is via obscure 3 letter ISO codes, it would be good to have it understandable
- the desktop application can take a long time to load, and the spinner in App.vue does not show while loading
- there are others for sure

and these have now been done

- Done in pull request #810 :
- (done) the 'rus' and 'ukr' language options just default to English, possible to disable them until translations available
Done in pull request #815 :
- (done) the desktop menu options 'Save PDF' and 'Save HTML' are export options, not save menu items
- (done) there should be a submenu for the Export / Save menu items, they clutter the 'File' menu
Done in pull request #821 :
- (done) when in the main model page, 'Close' closes the entire model, which is unexpected, maybe 'Exit model'
- (done) exporting to PDF or HTML will lose any unsaved edits (diagram or metadata)
- (done) when editing the model metadata, pressing save button unexpectedly dumps the user back to main screen

**Describe the solution you'd like**:
make user interface more intuitive

**Additional context**:
* pull request #810 hides rus and ukr from i18n menu for now, until translation becomes available
* export options grouped together with pull request #815

**Comment by raghav1030** [comment]
hey @jgadsden ! I would like to work upon this. Can you please assign it to me?

**Comment by jgadsden** [comment]
did you have a particular user interface issue in mind? There are a few to consider:

* when editing the model metadata, pressing save button unexpectedly dumps the user back to main screen
* selecting the language is via obscure 3 letter ISO codes, it would be good to have it understandable
* exporting to PDF or HTML will lose any unsaved edits (diagram or metadata)
* the desktop application can take a long time to load, depending on the machine, so a bootstrap screen while loading would be reassuring

**Comment by raghav1030** [comment]
> did you have a particular user interface issue in mind? There are a few to consider:
> 
> * when editing the model metadata, pressing save button unexpectedly dumps the user back to main screen
> * selecting the language is via obscure 3 letter ISO codes, it would be good to have it understandable
> * exporting to PDF or HTML will lose any unsaved edits (diagram or metadata)
> * the desktop application can take a long time to load, depending on the machine, so a bootstrap screen while loading would be reassuring


Yeah, each issue is solvable here, but I believe we should address one issue at a time. I'll focus on resolving the main issue #804 here. Can I create separate pull requests for individual issues? What do you think?

**Comment by jgadsden** [comment]
Hello @raghav1030 , note that #804 is already being assigned and has had some commits
but the other issues are open to individual pull requests for sure

**Comment by LalitDeore** [comment]
Hi @jgadsden,  I am preparing for GSOC 2024 and have identified the Owasp organization, which aligns with my skills. I am excited about contributing to Owasp, and I would appreciate it if anyone could help me start my contribution journey. Additionally, if the organization is working on any important projects that will be part of GSOC 2024, please let me know.

**Comment by raghav1030** [comment]
> Hello @raghav1030 , note that #804 is already being assigned and has had some commits but the other issues are open to individual pull requests for sure

Hey @jgadsden! I have tried to change the way how languages are getting rendered in the locale select dialog box. The update renders each language in their local transliteration now. This is how it looks like : 

![image](https://github.com/OWASP/threat-dragon/assets/94848646/5c569446-418e-49af-849f-da2604607a1f)

**Comment by raghav1030** [comment]
> > Hello @raghav1030 , note that #804 is already being assigned and has had some commits but the other issues are open to individual pull requests for sure
> 
> Hey @jgadsden! I have tried to change the way how languages are getting rendered in the locale select dialog box. The update renders each language in their local transliteration now. This is how it looks like :
> 
> ![image](https://private-user-images.githubusercontent.com/94848646/294262127-5c569446-418e-49af-849f-da2604607a1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTE5MjcsIm5iZiI6MTcwNDM5MTYyNywicGF0aCI6Ii85NDg0ODY0Ni8yOTQyNjIxMjctNWM1Njk0NDYtNDE4ZS00OWFmLTg0OWYtZGEyNjA0NjA3YTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE4MDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MGZkOGQ3NjIzYjQxN2Q1YWE4NWZlYzc3MjJmYTQ2NmNjNWE2YWM5YWQ1NzliMWE3MDRiN2NmZjA3YTYyYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LOLWW16FcCJrN2t0HiZWYkf-Wb4JSuRtSxRsw7CbW6w)

If it looks fine then I can make a PR?

**Comment by jgadsden** [comment]
superb @raghav1030 , please submit a pull request
many thanks in advance

**Comment by jgadsden** [comment]
Thanks for the pull request @raghav1030 and the last irritation I can move to a new issue #823
