### ISSUE TITLE
Loss of current diagram state when exporting as PDF before saving

### ISSUE THREAD

**Issue by PaulPrpl** [OWASP/threat-dragon#824]
**Bug**:
When user export to PDF before saving the model, current progression is immediately lost without asking for validation.
This could lead to total loss of modification if no save has been made, without being able to go back.

**Expected behaviour**:
Either the progression could be automatically saved when using feature "File" -> "Save PDF" or a confirmation box could be used.

**Environment**:

- Version: 2.1.2
- Platform: Desktop Application
- OS: happened on Windows and Linux version (Arch)

**To Reproduce**:
-Create a new model.
-Edit the diagram
-Save as PDF

**Comment by jgadsden** [comment]
yes, absolutely agree with this
there is a current pull-request that deals with this higg priority bug : #821 , specifically commit bbd3b22eff232129d1d2bf2badeca8986703a84c

Thanks for raising this bug @PaulPrpl
