### ISSUE TITLE
Navbar Elements Not Visible on Mobile Screen When Toggled

### ISSUE THREAD

**Issue by SharanRP** [OWASP/threat-dragon#835]
**Describe the bug**:
When viewing the website on a mobile screen and toggling the navbar, the navbar elements do not appear as expected. It seems that the navbar is overlapping with the background, causing the elements to be hidden. This issue makes it difficult for users to access the navigation menu and navigate through the website on smaller screens. It requires investigation and resolution to ensure a seamless user experience across different devices.

**Expected behaviour**:
The elements should be visible and accessible by the viewers
**Environment**:

- Version: (e.g. 1.3.1)
- Platform: (Web App / Desktop App)
- OS: (MacOS / Windows / Linux)
- Browser: (e.g. chrome, firefox, safari)

**To Reproduce**:
 open the website 
![webpage](https://i.imgur.com/n0SWeiD.png)

**Any additional context, screenshots, etc**:
It should look like :
![solution](https://i.imgur.com/yMSuEkO.png)

**Comment by jgadsden** [comment]
Hello @SharanRP , I am not that there are any users of Threat Dragon that are using it on a mobile phone
For example the diagrams themselves will not be displayed in a useful way on such a small screen
