### ISSUE TITLE
Allow for ES6 development against td.server

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#84]
**Describe what problem your feature request solves**
`td.server` should allow for ES6 development

**Describe the solution you'd like**
Using babel or a similar technology, the back-end code should be able to handle es6 syntax, such as `import './foobar.js'`

**Additional context**
Rather than doing a large refactor all at once, I think it would make sense to create the infrastructure to support ES6 development first, and then chip away at refactoring existing code.

**Comment by jgadsden** [comment]
Yes, agreed, if we could do it gradually then we can see the effect of the changes as we go along.

**Comment by lreading** [comment]
The only problem I'm seeing so far is that if we rewrite a file in es6 syntax, we will have to update everywhere that references it to use the `.default()` property or method. 

somefile.js
```
import fs from 'fs';

const myFunc = () => {};

export default {
  myFunc
};
```

consuming-non-es6-file.js
```
var someFile = require('./somefile.js');

// someFile.myFunc(); // no longer works
someFile.default.myFunc(); 
```

There may be a better way of doing this, or maybe some babel plugin that solves the issue.  
I'm just wondering if this will add more confusion and unnecessary code, or if we should move forward with it this way just to get things started and see where we land?
