### ISSUE TITLE
Multiselect is not working

### ISSUE THREAD

**Issue by Sondrebf** [OWASP/threat-dragon#844]
**Describe the bug**:

Multiselect wont let me drag all selected components

**Expected behaviour**:

Before i could select all the components i wanted to move and move them. Now only one component is moved-

**Environment**:

- Version: 2.1.3-latest
- Browser: chrome -latest

**Comment by jgadsden** [comment]
Hello @Sondrebf , can you provide the version that it worked OK for?

**Comment by Sondrebf** [comment]
Sorry i dont remember, i used the web version last year and it worked.

**Comment by raghav1030** [comment]
I have somehow solved the issue. Hey @Sondrebf, can you please confirm if you're talking about this behavior?

https://github.com/OWASP/threat-dragon/assets/94848646/4423fae9-ed95-432d-95d5-74bd4e3fac7f

**Comment by Sondrebf** [comment]
Yes, thats what i wanted, and had before 👍 Good!

**Comment by jgadsden** [comment]
yes, many thanks @raghav1030, please go ahead
