### ISSUE TITLE
Navbar Icons Should Tell Their UseCases

### ISSUE THREAD

**Issue by itsdheerajdp** [OWASP/threat-dragon#855]
**Current Behavior**
while hovering on navbar icons , i can't figure out which icon is rendering to which page . As a user it is not a better experience for me. So it will be better if each icon of navbar should tell it's functionality

[screen-capture.webm](https://github.com/OWASP/threat-dragon/assets/107138786/dc6c4c5f-5f98-429f-ac8d-5752e64feb7f)

**Describe what problem your feature request solves**:

If We each icons will tell it's functionality on hover then it will be easy for me to figure out what i want and which navbar icon will fulfil it.

**Describe the solution you'd like**:

It will be better if we add a title on hover in each of the navbar icon which will tell it's functionality.

**Additional context**:

**Comment by jgadsden** [comment]
thanks @itsdheerajdp , and if you can also provide a fix that would be great

**Comment by itsdheerajdp** [comment]
Sure @jgadsden , I made a PR to fix this
