### ISSUE TITLE
Enhancement Required in Navbar

### ISSUE THREAD

**Issue by itsdheerajdp** [OWASP/threat-dragon#862]
**Describe what problem your feature request solves**:
In the Hindi version of the page , the navbar appearance doesn't looks understandable for a Hindi user and also the [log out] hover appearance is written in English in place of Hindi . I shown the problem in the below video.

[screen-capture.webm](https://github.com/OWASP/threat-dragon/assets/107138786/ad438f4d-664a-4825-a01a-1e0bf11eded3)

**Describe the solution you'd like**:
We should change the logout hover appearance and also logged in user appearance for better readability

**Additional context**:

**Comment by jgadsden** [comment]
thanks @itsdheerajdp for pointing this out, can you fix up the translation file at `td.vue/src/i18n/hi.js` ?
if it is OK wi will assign this to you

**Comment by itsdheerajdp** [comment]
@jgadsden i made the PR to fix this. Kindly check the PR
