### ISSUE TITLE
Login Status is not visible Clearly in small screen width

### ISSUE THREAD

**Issue by itsdheerajdp** [OWASP/threat-dragon#869]
**Describe what problem your feature request solves**:
When We open our the website in small screen width , the login status is not clearly visible in navbar as i shown below

![Screenshot 2024-02-09 101200](https://github.com/OWASP/threat-dragon/assets/107138786/f5eee33b-1616-4cad-bd6c-22f1a98d5c7b)

**Describe the solution you'd like**:
I can propose two type of the solution either we can have background color as $orange for the login status or we can have the login status in $orange color for small screen width which we can do by updating the media query . i shown both of the results in the below images

![Screenshot 2024-02-09 101717](https://github.com/OWASP/threat-dragon/assets/107138786/0a9c00ef-39c1-424e-b903-86a2a9b11484)

![Screenshot 2024-02-09 101757](https://github.com/OWASP/threat-dragon/assets/107138786/aca1c354-c2b0-44a3-87a3-692bd531b12d)

**Additional context**:

**Comment by itsdheerajdp** [comment]
What do you say @jgadsden

**Comment by jgadsden** [comment]
using a small screen for Threat Dragon is not a high priority - threat modeling with a restricted view is likely to be a poor experience, threat modeling being the creative experience and not about the tool
this could be looked at for sure, but it may not be adopted

**Comment by itsdheerajdp** [comment]
> using a small screen for Threat Dragon is not a high priority - threat modeling with a restricted view is likely to be a poor experience, threat modeling being the creative experience and not about the tool this could be looked at for sure, but it may not be adopted

media query is given for mobile screen width so that i think for this 
however if you want me to close this issue i'll do it further..?

**Comment by jgadsden** [comment]
Hello @itsdheerajdp , this is probably good to have - but if we change the login status as orange then it would not bee seen in a browser using a larger screen:
<img width="211" alt="Screenshot 2024-02-12 at 08 39 59" src="https://github.com/OWASP/threat-dragon/assets/29352392/50941e97-ae71-4e39-825c-0fb39b23e4ee">

Possibly black would work?

**Comment by itsdheerajdp** [comment]
@jgadsden  in large screen this login status will be in same white color but in small screen we'll change it to orange color so that consistency in the application will be maintained 
i'll make this change using updatation in media query so the color in large screen will be unchanged

**Comment by jgadsden** [comment]
OK, thanks @itsdheerajdp , appreciated and please go ahead with whichever solution you like best
