### ISSUE TITLE
Whole dashboard-action block should be clickable

### ISSUE THREAD

**Issue by itsdheerajdp** [OWASP/threat-dragon#871]
**Describe what problem your feature request solves**:

Currently, in the dashboard-action section, the icon is clickable and redirects to the expected page. However, the icon size is relatively small compared to the entire block. This discrepancy in size can lead to a suboptimal user experience. I attached the video below

[screen-capture.webm](https://github.com/OWASP/threat-dragon/assets/107138786/30d1d9a6-0738-4cd6-9c9e-52a4540e67d5)

**Comment by jgadsden** [comment]
yes, certainly @itsdheerajdp this would be a good thing to have
can I assign it to you?

**Comment by itsdheerajdp** [comment]
@jgadsden  i tried to work on this but can't get it till now
It'll be great if you can assist me on this

**Comment by jgadsden** [comment]
ah, I do not know how to do this - we can always open it up with 'help wanted'
