### ISSUE TITLE
update demo model page

### ISSUE THREAD

**Issue by itsdheerajdp** [OWASP/threat-dragon#880]
**Describe what problem your feature request solves**:
UI of demo model page can be improved 

![Screenshot 2024-02-15 232934](https://github.com/OWASP/threat-dragon/assets/107138786/67a2ffbc-a6ef-48c1-a399-3938d7ffef9f)

**Describe the solution you'd like**:

**Additional context**:

**Comment by jgadsden** [comment]
@itsdheerajdp can you provide some detail on what solution you would like to see for this issue

**Comment by itsdheerajdp** [comment]
@jgadsden I thought to update the styling of the containers having demo models to make its ui better

**Comment by jgadsden** [comment]
The pull request #882 does not fit in with the intended behavior so marking this as "Won't Do"
