### ISSUE TITLE
Confusing documentation suggests github has to be used

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#881]
**Describe the bug**:
The documentation suggests that github is a requirement to run Threat Dragon as a web application, which is incorrect

**Expected behaviour**:
The documentation needs to be changed so that it is clear that any of these will work for the web application:

* local file access
* github
* bitbucket
* gitlab

**Environment**:

- Version: 2.1.3
- Platform: Web App
- OS: any
- Browser: all of chrome, firefox, safari

**To Reproduce**:
For example:
_The web application variant of Threat Dragon requires some environment variables; 
follow the documentation on how to set these variables._

this points to the documentation explaining how to configure git, suggesting this is a step you need to take

_The Threat Dragon web application uses GitHub or Bitbucket to store threat models, so you need to go to your GitHub or Bitbucket account and register it as a GitHub application_

_To run Threat Dragon in a docker container, first configure your environment using dotenv_

_There are desktop versions of Threat Dragon which store the threat model files on the local filesystem rather than in a repository_

**Any additional context, screenshots, etc**:

**Comment by itsdheerajdp** [comment]
@jgadsden  can you please explain where will i find this documentation in order to work on this issue?

**Comment by jgadsden** [comment]
I rolled this into the version 2.2 release with commit [d285f07](https://github.com/OWASP/threat-dragon/commit/d285f074e02a3d44cdec51b2b78076e990e0a34a)
but thanks for offering @itsdheerajdp
