### ISSUE TITLE
Multiple access to web application and desktop

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#886]
**Describe what problem your feature request solves**:
Right now the biggest limitation seems to be inability to collaborate with the team on one Model simultaneously
(e.g. like on Mural)

**Describe the solution you'd like**:
Allow multiple users to work on the same model at the same time

**Additional context**:

**Comment by itsdheerajdp** [comment]
@jgadsden so basically we want to have feature so that for one model more than one person can make changes(collaborate) something similar to google docs or Mural

**Comment by jgadsden** [comment]
unlikely to be needed for Threat Dragon, so closing
