### ISSUE TITLE
Threat numbers are dependent on editing unsaved threats.

### ISSUE THREAD

**Issue by mohamedselbohy** [OWASP/threat-dragon#889]
**Describe the bug**:

threat numbers for next created threats are affected by just clicking unsaved threats. 
**Expected behavior**:

It was expected for the new threats to stick to an incremental sequence when creating them and to be independent on unsaved threats the ones that get applied first get the next available threat number.
**Environment**:

- Version: (2.2.0)
- Platform: (Web App)

**To Reproduce**:

I believe the threat top number should only be affected when saving and creating a new threat. instead of affecting the numbers of new threats irrelevantly which may confuse end users.

**Screenshot for clarification**
![image](https://github.com/OWASP/threat-dragon/assets/113469970/4634dcc6-e158-4562-be93-74651a47caa7)
threat 1 was created then saved then threat 0 was created and not applied then was clicked 3 times then threat 6 (should have been 2) was created and saved

**Comment by jgadsden** [comment]
thanks @mohamedselbohy , not necessarily a bug because it is supposed to do this
but it is certainly an enhancement if you want to change the behavior

**Comment by jgadsden** [comment]
Decided not go ahead with this, the desired behavior listed in #899 , so marking as "Won't Do"

**Comment by jgadsden** [comment]
reinstating this issue, because it corrects a bug in the threat creation where the threat number is always initially '0'
