### ISSUE TITLE
[Feature]: We Can have the [Cancel] and [Apply] Button more differentiable

### ISSUE THREAD

**Issue by itsdheerajdp** [OWASP/threat-dragon#897]
**Describe what problem your feature request solves**:
Currently the [Save] and [Cancel] Button in [Threat Edit Page] is very close to each other. We can have them more differentiable with some margins.

![Screenshot 2024-03-03 163715](https://github.com/OWASP/threat-dragon/assets/107138786/ff65137e-3966-4bbd-8190-42c3f50fd088)

![Screenshot 2024-03-03 163728](https://github.com/OWASP/threat-dragon/assets/107138786/e077cc0e-c3f2-472e-b733-45429136ad15)

**Describe the solution you'd like**:
it'll be good if we'll give some margin between these buttons. this will make the buttons more differentiable. After making the solution our buttons can be look like below

![Screenshot 2024-03-03 164042](https://github.com/OWASP/threat-dragon/assets/107138786/f1141fc5-0af9-434f-af84-1b1faabab4a8)

**Additional context**:

**Comment by itsdheerajdp** [comment]
@jgadsden what do you think about this??

**Comment by jgadsden** [comment]
yes, this would certainly be good to have, thanks @itsdheerajdp
