### ISSUE TITLE
Add Gitlab integration

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#9]
This issue has been migrated from : 
https://github.com/mike-goodwin/owasp-threat-dragon/issues/122
and was opened by @micheelengronne : 

Is it possible to add Gitlab integration ?

Thanks.

**Comment by jgadsden** [comment]
This is linked to issue "Request to relax test case requirements #4"

**Comment by jgadsden** [comment]
Most likely @subashsn forked threat dragon from commit: https://github.com/mike-goodwin/owasp-threat-dragon/commit/782b3c24b35df27b9a84d0e5ff9f538cca7edca0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

and the main patch to provide gitlab integration would come from the diff between this and commit : 
https://github.com/appsecco/owasp-threat-dragon-gitlab/commit/31799cfcf2577bad7be995a365ef5c1a12fcf9f4

**Comment by mkkeffeler** [comment]
looking forward to this one!

**Comment by jgadsden** [comment]
yes, agreed, and gitlab support is planned for version 2.0 which we hope is later this year

**Comment by mkkeffeler** [comment]
Is it possible to still see this land this year?

**Comment by jgadsden** [comment]
Hello @mkkeffeler - version 2.0 of Threat Dragon is looking unlikely for this year.

It could be brought into version 1.x Threat Dragon. Are you able to help with the coding? I think it would be a case of porting what  @subashsn  has done back into Threat  Dragon

**Comment by iman4000** [comment]
will threat dragon 2.0 release this year? and does it have gitlab integration? :)

**Comment by jgadsden** [comment]
Possibility that @kuwv can take this on - I can assign this if that goes ahead

**Comment by kuwv** [comment]
@jgadsden I've started looking into it. Why passport being used for testing but axios is doing the lifting in the app?

**Comment by jgadsden** [comment]
Thanks for looking at this @kuwv , and I have assigned this issue to if that is OK
I am not sure where we use passport  / passport-local , I know it is in the dev dependencies but we do not seem to actually use it during testing

@iman4000 apologies for not responding to your message from last year - you have probably already found that version 2.1.1 was released this month but still without gitlab integration

**Comment by kuwv** [comment]
@jgadsden what are your thoughts about me implementing passport for each?

**Comment by steve-winter** [comment]
I would also agree migrating to passport (or similar) would simplify things. Perhaps worth implementing for a single provider first?

**Comment by threatdragon** [comment]
Gitlab [creating a group-owned application](https://docs.gitlab.com/ee/integration/oauth_provider.html#create-a-group-owned-application) for OAuth
possibly use [gitlab-restapi](https://www.npmjs.com/package/gitlab-restapi)

**Comment by vineetpandey** [comment]
@threatdragon @jgadsden : are we having this issue in priority? It's a long awaited feature.

**Comment by steve-winter** [comment]
It's a relatively simple addition based on the previous Bitbucket integration I added. I have been busy elsewhere but can probably pick this up in next 2 weeks.

@jgadsden assuming we do want this feature?

**Comment by jgadsden** [comment]
yes, we would like this feature but it has been a case of finding a volunteer with engineering time to do it - as is the case with most open source projects :)

Yes, absolutely @steve-winter , if you can implement this that would be great, thank you

**Comment by steve-winter** [comment]
Draft can be seen here: https://github.com/steve-winter/threat-dragon/tree/%239-Gitlab

Not implemented testing yet, will add before PR. Have added https://github.com/OWASP/threat-dragon/issues/860 for a refactor of this part of the codebase.

**Comment by jgadsden** [comment]
closed via pull request #870
