### ISSUE TITLE
End-to-end Tests

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#90]
**Describe what problem your feature request solves**
End-to-end testing using [nightwatch](https://github.com/nightwatchjs/nightwatch) or [puppeteer](https://github.com/puppeteer/puppeteer)

**Describe the solution you'd like**
End-to-end testing using [nightwatch](https://github.com/nightwatchjs/nightwatch) or [puppeteer](https://github.com/puppeteer/puppeteer)

**Additional context**
- End-to-end tests should be run as part of a CI system (github action, maybe get a free [browserstack](https://www.browserstack.com/open-source) account for cross-browser testing?)
- Tests can be run locally as well as part of CI

**Comment by lreading** [comment]
This should probably be put on hold until #87 is resolved.  Changing the UI entirely will likely cause duplicated work.

**Comment by jgadsden** [comment]
Agreed @lreading , this will be most useful when applied to the new version of Threat Dragon (Vue + mxgraph).

I also agree that applying end to end tests to the existing code is great, but we already know that it generally works through years of use. Whereas the new version will need a good amount of end to end testing to be sure that we get the same confidence as before.

**Comment by lreading** [comment]
The skeleton for this has been added to the vue migration branch.  I intend to add an option to have threat-dragon-web run without a proper back-end for demo purposes only.  That will be essential to implementing thorough e2e tests, as I'm not totally comfortable putting github credentials into the repo secrets.

**Comment by lreading** [comment]
Closing as this is complete in v2
