### ISSUE TITLE
[Feature] : Enhancement can be done in the contributor form-tag of [Create Empty Threat Model] Page

### ISSUE THREAD

**Issue by itsdheerajdp** [OWASP/threat-dragon#901]
**Describe what problem your feature request solves**:
Currently the Added Contributor alignments are not so good in terms of UI. which we can see in below images

**[Create Empty Threat Model] Page:**

![Screenshot 2024-03-05 191203](https://github.com/OWASP/threat-dragon/assets/107138786/170e7b91-02fc-4c25-8f9f-df49c1f04e45)

**[Contributors form tag]:**

![Screenshot 2024-03-05 191216](https://github.com/OWASP/threat-dragon/assets/107138786/42e5c829-c40a-4a31-ad34-60182b9c5282)

**Describe the solution you'd like**:
I'd Like to have the added contributors in the [contributor form-tag] more clear and differentiable Like shown below:

![Screenshot 2024-03-05 191800](https://github.com/OWASP/threat-dragon/assets/107138786/dcbd42c4-8ff3-4a66-a85c-3cd3805b52d4)

**Additional context**:

**Comment by jgadsden** [comment]
provided by commit 60e18e1b7b57de343a2f0111f966442877a86e40
