### ISSUE TITLE
Threats Available in PLOT4ai Diagram Type

### ISSUE THREAD

**Issue by itsdheerajdp** [OWASP/threat-dragon#919]
**Describe what problem your feature request solves**:
In the threat dragon , there are only 5 threats are given for PLOT4ai diagram type as below shown

![Screenshot 2024-03-16 103702](https://github.com/OWASP/threat-dragon/assets/107138786/4c897c4b-0787-437d-b209-edd3be3ed785)

However , in the official documentation of PLOT4ai , there are 8 types of threats possible as shown below:

![Screenshot 2024-03-16 103645](https://github.com/OWASP/threat-dragon/assets/107138786/7ca76322-e5c5-40ae-b5c2-062d6664dcf2)

**Describe the solution you'd like**:
If we are not knowingly doing this then we can add remaining threats in the PLOT4ai Diagram type.

**Additional context**:

**Comment by jgadsden** [comment]
This is not a bug - Threat Dragon applies PLOT4ai by element, and the selection shown is for a Store or Process. There are different type selections for Actor or DataFlow diagram components and this is correct behavior.
