### ISSUE TITLE
Translation to Japanese

### ISSUE THREAD

**Issue by m10k** [OWASP/threat-dragon#932]
**Describe what problem your feature request solves**:
It would be helpful if it was possible to switch threat dragon to Japanese.

**Describe the solution you'd like**:
Create a new translation file for Japanese.

**Additional context**:
I have already created the translation and will submit a PR shortly. I'm creating this issue because I assume it is part of the process (that is, there are issues for other translations).

**Comment by jgadsden** [comment]
Many thanks for raising this issue @m10k and for also raising the pull request
