### ISSUE TITLE
Contributors field is not saved

### ISSUE THREAD

**Issue by kostasadriano** [OWASP/threat-dragon#935]
**Describe the bug**:
Contributors field is not saved

**Expected behaviour**:
After adding contributors and saving the model, the relevant field should appear as filled.

**Environment**:

- Version: 2.2.0
- Platform:  Desktop App
- OS: Tested on Windows, could affect Linux as well

**To Reproduce**:
1. Added Contributors
2. Clicked Save
3. Successfully saved message appeared
4. 4. When we close the screen and return to the main model page, we do not see the contributors. If we edit it again, the field now is empty as well.

**Any additional context, screenshots, etc**:
![Threat Dragon_contributors not saved_1](https://github.com/OWASP/threat-dragon/assets/6406427/c85358c3-45f4-4b61-941a-cdbfb644deb8)
![Threat Dragon_contributors not saved_2](https://github.com/OWASP/threat-dragon/assets/6406427/248fff52-3997-483c-9e37-c05932f86008)

**Comment by jgadsden** [comment]
Hello @kostasadriano , thanks for raising this. It is a feature of Threat Dragon that you have to click the 'Add' button to enter the contributor - this allows for a list of contributors to be built up, rather than a single text string:
<img width="564" alt="Screenshot 2024-04-03 at 22 02 14" src="https://github.com/OWASP/threat-dragon/assets/29352392/9aff5a16-3687-46a3-8234-75ef85df41fd">

**Comment by jgadsden** [comment]
It may be that the documentation is not clear here, so marking this issue as Documentation for next release

**Comment by kostasadriano** [comment]
It was right in front of my eyes!
Maybe the button is a bit far away and greyed.
The most possible explanation though, is that the button appears only after you have added names, so before adding them I thought that the field worked like the owner and reviewer. Having it from the beginning would make it more clear.

**Comment by jgadsden** [comment]
yes, I agree @kostasadriano , it certainly can be improved - it is just finding someone with the time to do it :)
we can update the documentation until it can be improved
