### ISSUE TITLE
OWASP Threat Dragon - Logo in GitHub dark mode?

### ISSUE THREAD

**Issue by pzrq** [OWASP/threat-dragon#936]
**Describe the bug**:

I'm using the Bug type template, just because it was the first in the list and there's no obvious "other", but this is more of a question than a bug.

When I view the README.md threat dragon SVG logo in GitHub dark mode, it's barely perceptible. Is this intentional?
![Screenshot from 2024-04-04 16-55-54](https://github.com/OWASP/threat-dragon/assets/1217010/edcf029f-4ca4-4b8d-9654-149c67f4555e)

**Expected behaviour**:

Unknown (hence it's one of those not really a bug bug reports which could be closed on this technicality).

**Workaround**

I can work around it by changing my Ubuntu > System Settings >  Appearance > Style from Dark to Light, which was probably what was intended?
![Screenshot from 2024-04-04 16-58-11](https://github.com/OWASP/threat-dragon/assets/1217010/990423b7-e31c-48d9-8b12-0a3a96a8a424)

**Environment**:

- Version: N/A
- Platform: (github.com)
- OS: Ubuntu 22.04 LTS
- Browser: Firefox

**To Reproduce**:

**Any additional context, screenshots, etc**:

**Comment by pzrq** [comment]
@jgadsden Thanks, I think one fix for cupcake, could be to replace the transparent pixels with white or light-coloured pixels. 

Of course there are lots of other options too.

I tend to software engineer stuff, so if there's someone here on the project with actual design experience, they'd be the best person to ask, though I can have a go at the assets to just go transparent -> white in https://github.com/OWASP/threat-dragon/tree/main/td.vue/src/assets if that'd be appropriate too?

**Comment by jgadsden** [comment]
Yes, that seems a good plan @pzrq of you would like to go ahead and make a pull request?
