### ISSUE TITLE
Optional entity properties are not shown in reports

### ISSUE THREAD

**Issue by michaelgrahamevans** [OWASP/threat-dragon#937]
**Describe what problem your feature request solves**:

Some of the optional entity properties (such as `protocol`, `isEncrypted`, `isPublicNetwork`) can be edited in the diagram editing page but they do not appear in the report page.

**Describe the solution you'd like**:

Entity properties are listed with the entity, perhaps between the description and the list of threats.

**Additional context**:

Here's a screenshot of something I hacked together showing the properties of one of the data flow entities of the V2 demo model:

![image](https://github.com/OWASP/threat-dragon/assets/5932424/72092476-beb6-48bb-84ab-2cd64677d17a)

If it looks promising, I can finish it off and open a pull request.

**Comment by jgadsden** [comment]
Hello @michaelgrahamevans , you have a very good point and it would be good to have this information in the report.
I can go ahead and assign this issue to you as you are working on it? Much appreciated

**Comment by jgadsden** [comment]
Hello @michaelgrahamevans , no pressure I promise! but how are you getting on with this? Version 2.3 is due for this month, and I can bump it to later in the year for version 2.4 if you like
