### ISSUE TITLE
"Edit Threat" dialog caches content after Cancel button

### ISSUE THREAD

**Issue by heintmaSICKAG** [OWASP/threat-dragon#941]
**Describe the bug**:
After editing a threat in the  "Edit Threat" dialog the Cancel button is clicked. After opening the same "Edit Threat" dialog  all changes are shown in the dialog.

I don't know if the values edited in the dialog are cached or saved. After closing the dialog with cancel the element of the threat in the Threats area is not updated.

**Expected behaviour**:
Clicking on Cancel in a dialog should throw away every change made.

**Environment**:

- Version: 2.2.0
- Platform: Desktop App
- OS: Windows
- Browser: 

**To Reproduce**:
1. Start Threat Dragon 2.2.0
2. Create a new, empty threat model
3. Add a new diagram
4. Add a Process to your diagram
5. Add New Threat to your process and hit apply
6. Open the New threat again, change something and hit Cancel
7. Open the New Threat again and the previously "Cancelled" changes  are shown

**Any additional context, screenshots, etc**:

**Comment by jgadsden** [comment]
yes, absolutely agree @heintmaSICKAG , and this was an issue we corrected in #899 with a pull request
It has yet to be released in version 2.3

**Comment by heintmaSICKAG** [comment]
Thank you very much for clarification. Although i searched for this bug i did not found it, sorry my fault.

**Comment by jgadsden** [comment]
Not at all @heintmaSICKAG , Threat Dragon front end has had a lot of changes since version 2.2 and we need to get them released in version 2.3
We have an issue with the Windows signing at the moment, so once that is sorted we can get 2.3 out
