### ISSUE TITLE
Implement mousewheel button dragging for graph panning

### ISSUE THREAD

**Issue by save196** [OWASP/threat-dragon#954]
**Describe what problem your feature request solves**:
The current graph panning method requires a combination of keyboard and mouse inputs, and mousewheel button is redundant with left mouse button.

**Describe the solution you'd like**:
Users should be able to press down the mousewheel button and move the mouse to pan around the graph.

**Comment by jgadsden** [comment]
itis possible that pull request 'Migrate to version 2.x antv/x6' https://github.com/OWASP/threat-dragon/pull/1099, may fix this - mousewheel panning is enabled and just needs to be tested
