### ISSUE TITLE
Publish Official Docker Image using build pipeline

### ISSUE THREAD

**Issue by lreading** [OWASP/threat-dragon#96]
**Describe what problem your feature request solves**
Publish an official docker images to a public registry (Docker hub, gcr, something else?)

**Describe the solution you'd like**
Build the docker image as part of the build pipeline and publish the image to an official registry.

**Additional context**
Any official Threat Dragon releases should have a tagged image with the same version.  `latest` could be kept up to date based on the main branch.
Where this is an OWASP project, it would probably make sense to have it published under the [OWASP dockerhub user](https://hub.docker.com/u/owasp).  I don't know what's involved  in getting publish rights there, nor do I know what requirements there are for images pushed there.

**Comment by jgadsden** [comment]
Hello @lreading - do you mind if I take this issue on? I will be preparing the release for web app and desktop app over the next two days and this will / should include the docker image

**Comment by lreading** [comment]
By all means!

**Comment by jgadsden** [comment]
Created a threatdragon user on Docker Hub: https://hub.docker.com/u/threatdragon
With container https://hub.docker.com/r/threatdragon/owasp-threat-dragon

Ideally this would be in the OWASP area of Docker Hub: https://hub.docker.com/u/owasp
We have emailed OWASP to allow us to use this organisation but have had no reply.

This needs integrating with the build/release pipeline

**Comment by lreading** [comment]
We are publishing an image via Github Action now when doing a release (triggered by tags). Do we want to keep this open and continue to try to get access to the OWASP area of Dockerhub, or should we just carry on with the threatdragon user?

**Comment by jgadsden** [comment]
I think it may be some time before we get  access to the OWASP area of Dockerhub, so I agree we can close this issue
