### ISSUE TITLE
Sample threat model from within threat-dragon repo

### ISSUE THREAD

**Issue by jgadsden** [OWASP/threat-dragon#98]
**Describe what problem your feature request solves**
The sample threat model is loaded from a remote repo `mike-goodwin/owasp-threat-dragon-demo/master/Demo Threat Model` which does not make it easy to maintain this file

**Describe the solution you'd like**
It would be good to have this file within the threat-dragon repo so it can be easily updated 

**Additional context**
At present the sample threat model is loaded using `common.js` in threat-dragon-core:

```
        demoModelLocation: {
            organisation: 'mike-goodwin',
            repo: 'owasp-threat-dragon-demo',
            branch: 'master',
            model: 'Demo Threat Model'
```

**Comment by lreading** [comment]
It would definitely be better to have the sample contained within this repo. I think it would be an interesting exercise if we could take it a step further and do a proper threat model for the Threat Dragon application.  I know that's a non-trivial thing to ask for, so if it should be in a separate issue, let me know and I can make one. :smile:

**Comment by jgadsden** [comment]
It sounds like a good (and non-trivial) thing to do - the Threat Dragon application will be running side by side with the example threat model of that very same application, very nice.

We can start off with the simplest model I guess, and then work up to it.

**Comment by jgadsden** [comment]
created  `ThreatDragonModels/demo-threat-model/demo-threat-model.json` and references to the demo model changed to point to this file
