### ISSUE TITLE
Automated generation of threats by element implementation

### ISSUE THREAD

**Issue by mohamedselbohy** [OWASP/threat-dragon#985]
## Implement automated generation of threats by element

As it was implemented in the 1.X versions
![image](https://github.com/OWASP/threat-dragon/assets/113469970/972c2cd3-efc7-4cba-8e62-0830a0f0e77a)

We only had the option to accept or ignore each threat suggestion in the series as a form of brainstorming with minimal suggestion features

Which was the motivation to redesign the same feature with an additional option to skip the whole process accompanying a suggestive feature inherently suggesting the next threat type from within the default threat creation process
as per the original issue #792

**Comment by jgadsden** [comment]
implemented in pull request #1033 , thanks @mohamedselbohy ,  so can now close this issue
