### ISSUE TITLE
arm64 builds for macOS

### ISSUE THREAD

**Issue by sebdanielsson** [OWASP/threat-dragon#991]
**Describe what problem your feature request solves**:
Currently this is the only app on my Mac not running natively. An arm64 build for macOS would be greatly appreciated.

**Describe the solution you'd like**:
Add arm64 electron builds.

**Additional context**:

**Comment by cybermnemosyne** [comment]
Likewise arm64 Linux - if you are running a linux VM on Mac Silicon - same problem.

**Comment by jgadsden** [comment]
yes, good point - these can be built within the pipeline, probably just by adding another stage to the existing step

**Comment by jgadsden** [comment]
@cybermnemosyne are you running snap or appimage in your Linux VM on arm64 mac?

**Comment by cybermnemosyne** [comment]
snap

**Comment by jgadsden** [comment]
OK, thanks @cybermnemosyne - I will try to add the arm64 architecture to both AppImage and Snap
If I am successful I can add to the documentation on how to build/run locally, and then include it in the version 2.3 release scheduled for August (2024)

**Comment by sebdanielsson** [comment]
If it's not too much work it might be good to add Windows arm64 too since Microsoft and hardware vendors seems to be pushing it hard now😎

**Comment by jgadsden** [comment]
yes, good point, and it is probably time to retire ia32 :)
